# ASR Assignment 2025-26

This notebook has been provided as a template to get you started on the assignment.  Feel free to use it for your development, or do your development directly in Python.

You can find a full description of the assignment [here](https://www.inf.ed.ac.uk/teaching/courses/asr/coursework-2026.html).

You are provided with two Python modules `observation_model.py` and `wer.py`.  The first was described in [Lab 3](https://github.com/geoph9/asr_labs/blob/main/asr_lab3_4.ipynb).  The second can be used to compute the number of substitution, deletion and insertion errors between ASR output and a reference text.

It can be used as follows:

```python
import wer

my_refence = 'A B C'
my_output = 'A C C D'

wer.compute_alignment_errors(my_reference, my_output)
```

This produces a tuple $(s,d,i)$ giving counts of substitution,
deletion and insertion errors respectively - in this example (1, 0, 1).  The function accepts either two strings, as in the example above, or two lists.  Matching is case sensitive.

## Template code

Assuming that you have already made a function to generate an WFST, `create_wfst()` and a decoder class, `MyViterbiDecoder`, you can perform recognition on all the audio files as follows:

In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /afs/inf.ed.ac.uk/user/s29/s2932989/.local/lib/python3.7/site-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /afs/inf.ed.ac.uk/user/s29/s2932989/.local/lib/python3.7/site-packages (from pandas) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /group/teaching/asr/labs/conda_install/conda_env/lib/python3.7/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2017.3 in /group/teaching/asr/labs/conda_install/conda_env/lib/python3.7/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /group/teaching/asr/labs/conda_install/conda_env/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.17.0)

In [2]:
import math
import time
import openfst_python as fst
import observation_model
import wer

In [3]:
# Copied from asr_lab2_solutions.ipynb
# Just for you to debug your code

def parse_lexicon(lex_file):
    """
    Parse the lexicon file and return it in dictionary form.
    
    Args:
        lex_file (str): filename of lexicon file with structure '<word> <phone1> <phone2>...'
                        eg. peppers p eh p er z

    Returns:
        lex (dict): dictionary mapping words to list of phones
    """
    
    lex = {}  # create a dictionary for the lexicon entries (this could be a problem with larger lexica)
    with open(lex_file, 'r') as f:
        for line in f:
            line = line.split()  # split at each space
            lex[line[0]] = line[1:]  # first field the word, the rest is the phones
    return lex

def generate_symbol_tables(lexicon, n=3):
    '''
    Return word, phone and state symbol tables based on the supplied lexicon
        
    Args:
        lexicon (dict): lexicon to use, created from the parse_lexicon() function
        n (int): number of states for each phone HMM
        
    Returns:
        word_table (fst.SymbolTable): table of words
        phone_table (fst.SymbolTable): table of phones
        state_table (fst.SymbolTable): table of HMM phone-state IDs
    '''
    
    state_table = fst.SymbolTable()
    phone_table = fst.SymbolTable()
    word_table = fst.SymbolTable()
    
    # add empty <eps> symbol to all tables
    state_table.add_symbol('<eps>')
    phone_table.add_symbol('<eps>')
    word_table.add_symbol('<eps>')
    
    for word, phones  in lexicon.items():
        
        word_table.add_symbol(word)
        
        for p in phones: # for each phone
            
            phone_table.add_symbol(p)
            for i in range(1,n+1): # for each state 1 to n
                state_table.add_symbol('{}_{}'.format(p, i))
            
    return word_table, phone_table, state_table


# call these two functions
lex = parse_lexicon('lexicon.txt')
word_table, phone_table, state_table = generate_symbol_tables(lex)

# add silence states (REQUIRED for Task 2)
for i in range(1, 6):
    if state_table.find(f"sil_{i}") == -1:
        state_table.add_symbol(f"sil_{i}")

def generate_phone_wfst(f, start_state, phone, n, self_loop_prob=0.1):
    """
    Generate a WFST representating an n-state left-to-right phone HMM
    
    Args:
        f (fst.Fst()): an FST object, assumed to exist already
        start_state (int): the index of the first state, assmed to exist already
        phone (str): the phone label 
        n (int): number of states for each phone HMM
        
    Returns:
        the final state of the FST
    """
    
    current_state = start_state
    
    for i in range(1, n+1):
        
        in_label = state_table.find('{}_{}'.format(phone, i))
        forward_prob = 1.0 - self_loop_prob

        sl_weight = fst.Weight('log', -math.log(self_loop_prob))  # weight for self-loop
        # self-loop back to current state
        f.add_arc(current_state, fst.Arc(in_label, 0, sl_weight, current_state))
        
        # transition to next state
        
        # we want to output the phone label on the final state
        # note: if outputting words instead this code should be modified
        if i == n:
            out_label = phone_table.find(phone)
        else:
            out_label = 0   # output empty <eps> label
            
        next_state = f.add_state()
        next_weight = fst.Weight('log', -math.log(forward_prob)) # weight to next state
        f.add_arc(current_state, fst.Arc(in_label, out_label, next_weight, next_state))    
       
        current_state = next_state
        
    return current_state

def generate_silence_wfst(f, start_state):
    """
    Generate a simple optional silence HMM using 5 silence states.
    We do not need to match the exact training topology.
    """
    current_state = start_state

    # use 5 silence states: sil_1 ... sil_5
    for i in range(1, 6):
        in_label = state_table.find(f"sil_{i}")

        next_state = f.add_state()

        # self-loop
        f.add_arc(
            current_state,
            fst.Arc(
                in_label,
                0,
                fst.Weight('log', -math.log(0.3)),
                current_state
            )
        )

        # forward transition
        f.add_arc(
            current_state,
            fst.Arc(
                in_label,
                0,
                fst.Weight('log', -math.log(0.7)),
                next_state
            )
        )

        current_state = next_state

    return current_state

def generate_word_wfst(word, self_loop_prob=0.1):
    """
    Generate a WFST for one word, but output the WORD once at the end.
    """
    f = fst.Fst('log')

    start_state = f.add_state()
    f.set_start(start_state)

    current_state = start_state
    phones = lex[word]

    for phone in phones:
        current_state = generate_phone_wfst(
            f, current_state, phone, 3, self_loop_prob=self_loop_prob)

    # add one epsilon-input arc that outputs the whole word
    final_state = f.add_state()
    f.add_arc(
        current_state,
        fst.Arc(
            0,  # epsilon input
            word_table.find(word),  # output the whole word
            fst.Weight('log', 0.0),  # probability 1
            final_state
        )
    )

    f.set_final(final_state)
    return f

def build_unigram_model(audio_to_reference, smoothing=1.0):
    """
    Estimate unigram probabilities from reference transcriptions.

    smoothing=1.0 gives simple add-one smoothing so no in-vocabulary word
    gets zero probability.
    """
    unigram_counts = {word: 0 for word in lex.keys()}
    total_count = 0

    for ref in audio_to_reference.values():
        words = normalize_text(ref).split()
        for w in words:
            if w in unigram_counts:
                unigram_counts[w] += 1
                total_count += 1

    vocab_size = len(unigram_counts)

    unigram_probs = {}
    for word, count in unigram_counts.items():
        unigram_probs[word] = (count + smoothing) / (total_count + smoothing * vocab_size)

    return unigram_probs


def build_bigram_model(audio_to_reference, smoothing=0.0):
    """
    Optional helper for later experiments.
    This builds actual conditional bigram probabilities P(w_i | w_{i-1}),
    although your current WFST structure does not yet use them properly.
    """
    bigram_counts = {}
    unigram_context_counts = {}

    for ref in audio_to_reference.values():
        words = normalize_text(ref).split()

        for i in range(1, len(words)):
            prev_w = words[i - 1]
            curr_w = words[i]

            if prev_w not in bigram_counts:
                bigram_counts[prev_w] = {}

            bigram_counts[prev_w][curr_w] = bigram_counts[prev_w].get(curr_w, 0) + 1
            unigram_context_counts[prev_w] = unigram_context_counts.get(prev_w, 0) + 1

    bigram_probs = {}
    vocab = list(lex.keys())
    vocab_size = len(vocab)

    for prev_w in bigram_counts:
        bigram_probs[prev_w] = {}
        denom = unigram_context_counts[prev_w] + smoothing * vocab_size

        for curr_w in vocab:
            count = bigram_counts[prev_w].get(curr_w, 0)
            bigram_probs[prev_w][curr_w] = (count + smoothing) / denom

    return bigram_probs


def create_wfst(
    continue_prob=1.0,
    self_loop_prob=0.1,
    use_unigram=False,
    use_silence=False,
    bigram_probs=None,
    unigram_probs=None
):
    f = fst.Fst('log')

    start_state = f.add_state()
    f.set_start(start_state)

    continue_weight = fst.Weight('log', -math.log(continue_prob))

    for word, phones in lex.items():
        current_state = start_state

        for phone in phones:
            current_state = generate_phone_wfst(
                f, current_state, phone, 3, self_loop_prob=self_loop_prob
            )

        word_output_state = f.add_state()

        # Per-word output weight
        if use_unigram and unigram_probs is not None:
            prob = unigram_probs.get(word, 1e-12)
            word_weight = fst.Weight('log', -math.log(prob))
        else:
            word_weight = fst.Weight('log', 0.0)

        f.add_arc(
            current_state,
            fst.Arc(
                0,
                word_table.find(word),
                word_weight,
                word_output_state
            )
        )

        f.set_final(word_output_state)

        # Keep this simple for now.
        # We are not claiming this is a real bigram WFST yet.
        f.add_arc(
            word_output_state,
            fst.Arc(
                0,
                0,
                continue_weight,
                start_state
            )
        )

        if use_silence:
            silence_start = f.add_state()

            f.add_arc(
                word_output_state,
                fst.Arc(
                    0,
                    0,
                    fst.Weight('log', 0.0),
                    silence_start
                )
            )

            silence_end = generate_silence_wfst(f, silence_start)

            f.add_arc(
                silence_end,
                fst.Arc(
                    0,
                    0,
                    continue_weight,
                    start_state
                )
            )
            
    f.set_input_symbols(state_table)
    f.set_output_symbols(word_table)

    return f

In [4]:
print(list(lex.items())[:3])
print("num words:", word_table.num_symbols())
print("num phones:", phone_table.num_symbols())
print("num states:", state_table.num_symbols())

[('a', ['ey']), ('of', ['ah', 'v']), ('peck', ['p', 'eh', 'k'])]
num words: 11
num phones: 18
num states: 57

In [5]:
class MyViterbiDecoder:
    NLL_ZERO = 1e10  # approximate -log(0) with a very large number

    def __init__(self, f, audio_file_name, pruning_threshold=None):
        """Set up the decoder class with an audio file and WFST f"""
        self.om = observation_model.ObservationModel()
        self.f = f
        self.forward_computations = 0
        self.pruning_threshold = pruning_threshold

        if audio_file_name:
            self.om.load_audio(audio_file_name)
        else:
            self.om.load_dummy_audio()

        self.initialise_decoding()

    def initialise_decoding(self):
        """set up the values for V_j(0) (as negative log-likelihoods)
        
        """
        
        self.V = []   # stores likelihood along best path reaching state j
        self.B = []   # stores identity of best previous state reaching state j
        self.W = []   # stores output labels sequence along arc reaching j - this removes need for 
                      # extra code to read the output sequence along the best path
        
        for t in range(self.om.observation_length()+1):
            self.V.append([self.NLL_ZERO]*self.f.num_states())
            self.B.append([-1]*self.f.num_states())
            self.W.append([[] for i in range(self.f.num_states())])  #  multiplying the empty list doesn't make multiple
        
        # The above code means that self.V[t][j] for t = 0, ... T gives the Viterbi cost
        # of state j, time t (in negative log-likelihood form)
        # Initialising the costs to NLL_ZERO effectively means zero probability    
        
        # give the WFST start state a probability of 1.0   (NLL = 0.0)
        self.V[0][self.f.start()] = 0.0
        
        # some WFSTs might have arcs with epsilon on the input (you might have already created 
        # examples of these in earlier labs) these correspond to non-emitting states, 
        # which means that we need to process them without stepping forward in time.  
        # Don't worry too much about this!  
        self.traverse_epsilon_arcs(0)        

    def traverse_epsilon_arcs(self, t):
        """Traverse arcs with <eps> on the input at time t
        
        These correspond to transitions that don't emit an observation
        
        We've implemented this function for you as it's slightly trickier than
        the normal case.  You might like to look at it to see what's going on, but
        don't worry if you can't fully follow it.
        
        """
        
        states_to_traverse = list(self.f.states()) # traverse all states
        while states_to_traverse:
            
            # Set i to the ID of the current state, the first 
            # item in the list (and remove it from the list)
            i = states_to_traverse.pop(0)   
        
            # don't bother traversing states which have zero probability
            if self.V[t][i] == self.NLL_ZERO:
                    continue
        
            for arc in self.f.arcs(i):
                
                if arc.ilabel == 0:     # if <eps> transition
                  
                    j = arc.nextstate   # ID of next state  
                
                    if self.V[t][j] > self.V[t][i] + float(arc.weight):
                        
                        # this means we've found a lower-cost path to
                        # state j at time t.  We might need to add it
                        # back to the processing queue.
                        self.V[t][j] = self.V[t][i] + float(arc.weight)
                        
                        # save backtrace information.  In the case of an epsilon transition, 
                        # we save the identity of the best state at t-1.  This means we may not
                        # be able to fully recover the best path, but to do otherwise would
                        # require a more complicated way of storing backtrace information
                        self.B[t][j] = self.B[t][i] 
                        
                        # and save the output labels encountered - this is a list, because
                        # there could be multiple output labels (in the case of <eps> arcs)
                        if arc.olabel != 0:
                            self.W[t][j] = self.W[t][i] + [arc.olabel]
                        else:
                            self.W[t][j] = self.W[t][i]
                        
                        if j not in states_to_traverse:
                            states_to_traverse.append(j)

    

    def forward_step(self, t):
        
        active_costs = [v for v in self.V[t-1] if v != self.NLL_ZERO]
        if not active_costs:
            return

        best_prev_cost = min(active_costs)
          
        for i in self.f.states():

            if self.V[t-1][i] == self.NLL_ZERO:
                continue

            if self.pruning_threshold is not None:
                dynamic_threshold = self.pruning_threshold

                # prune more aggressively in later frames
                if t > self.om.observation_length() * 0.5:
                    dynamic_threshold *= 0.85

                if self.V[t-1][i] > best_prev_cost + dynamic_threshold:
                    continue

            for arc in self.f.arcs(i):
                if arc.ilabel != 0:
                    j = arc.nextstate
                    tp = float(arc.weight)
                    ep = -self.om.log_observation_probability(
                        self.f.input_symbols().find(arc.ilabel), t
                    )
                    self.forward_computations += 1
                    prob = tp + ep + self.V[t-1][i]

                    if prob < self.V[t][j]:
                        self.V[t][j] = prob
                        self.B[t][j] = i

                        if arc.olabel != 0:
                            self.W[t][j] = [arc.olabel]
                        else:
                            self.W[t][j] = []

    def finalise_decoding(self):
        """Add final-state costs and invalidate non-final endings."""
        T = self.om.observation_length()

        for state in self.f.states():
            if self.V[T][state] == self.NLL_ZERO:
                continue

            final_weight = float(self.f.final(state))
            if final_weight == math.inf:
                # cannot end in a non-final state
                self.V[T][state] = self.NLL_ZERO
            else:
                self.V[T][state] += final_weight

        # optional message if nothing reached the end
        if not any(v < self.NLL_ZERO for v in self.V[T]):
            print("No path got to the end of the observations.")

    def decode(self):
        """Run Viterbi forward pass + epsilon traversals, then apply final weights."""
        self.initialise_decoding()
        t = 1
        while t <= self.om.observation_length():
            self.forward_step(t)
            self.traverse_epsilon_arcs(t)
            t += 1
        self.finalise_decoding()

    def backtrace(self):
        """Recover best state sequence and output label sequence."""
        T = self.om.observation_length()

        final_candidates = [
            s for s in self.f.states()
            if float(self.f.final(s)) != math.inf and self.V[T][s] < self.NLL_ZERO
        ]

        if not final_candidates:
            return ([], "")

        best_final_state = min(final_candidates, key=lambda s: self.V[T][s])

        best_state_sequence = [best_final_state]
        best_out_sequence = []

        t = T
        j = best_final_state

        while t >= 0:
            i = self.B[t][j]
            best_state_sequence.append(i)

            best_out_sequence = self.W[t][j] + best_out_sequence

            if i == -1:
                break

            j = i
            t -= 1

        best_state_sequence.reverse()
        best_out_sequence = ' '.join(
            [self.f.output_symbols().find(label) for label in best_out_sequence if label != 0]
        )

        return (best_state_sequence, best_out_sequence)

In [6]:
def normalize_text(text):
    """
    Lowercase and remove simple punctuation so references and hypotheses
    are compared consistently.
    """
    text = text.lower()
    for ch in [".", ",", "?", "!", "'", '"', ":", ";", "…", "-", "(", ")", "[", "]"]:
        text = text.replace(ch, "")
    text = " ".join(text.split())
    return text

In [7]:
import os

def load_transcripts(transcript_file, recordings_dir):
    audio_to_reference = {}

    with open(transcript_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            parts = line.split()
            filename = parts[0]
            transcription = " ".join(parts[1:])
            transcription = normalize_text(transcription)

            full_path = os.path.join(recordings_dir, filename)
            audio_to_reference[full_path] = transcription

    return audio_to_reference

In [8]:
def evaluate_utterance(f, audio_file, reference, pruning_threshold = None):
    """
    Decode one utterance and return metrics.
    """
    decoder = MyViterbiDecoder(f, audio_file, pruning_threshold=pruning_threshold)

    decode_start = time.time()
    decoder.decode()
    decode_end = time.time()

    backtrace_start = time.time()
    _, hypothesis = decoder.backtrace()
    if hypothesis == "":
        print("Warning: pruning removed all valid final paths for this utterance.")
    backtrace_end = time.time()

    reference = normalize_text(reference)
    hypothesis = normalize_text(hypothesis)

    s, d, i = wer.compute_alignment_errors(reference, hypothesis)

    return {
        "audio_file": audio_file,
        "reference": reference,
        "hypothesis": hypothesis,
        "S": s,
        "D": d,
        "I": i,
        "N": len(reference.split()),
        "decode_time_sec": decode_end - decode_start,
        "backtrace_time_sec": backtrace_end - backtrace_start,
        "time_sec": (decode_end - decode_start) + (backtrace_end - backtrace_start),
        "forward_computations": decoder.forward_computations
    }

In [9]:
def evaluate_dataset(
    audio_to_reference,
    continue_prob=1.0,
    self_loop_prob=0.1,
    use_unigram=False,
    use_silence=False,
    pruning_threshold=None,
    bigram_probs=None,
    unigram_probs=None,
    experiment_name=None
):
    """
    Run decoding on all utterances and aggregate Task 1/2/3/4 metrics.
    """
    f = create_wfst(
        continue_prob=continue_prob,
        self_loop_prob=self_loop_prob,
        use_unigram=use_unigram,
        use_silence=use_silence,
        bigram_probs=bigram_probs,
        unigram_probs=unigram_probs
    )

    num_states = f.num_states()
    num_arcs = sum(1 for s in f.states() for _ in f.arcs(s))

    results = []

    total_S = 0
    total_D = 0
    total_I = 0
    total_N = 0
    total_time = 0.0
    total_decode_time = 0.0
    total_backtrace_time = 0.0
    total_forward = 0
    empty_hyp_count = 0

    for audio_file, reference in audio_to_reference.items():
        result = evaluate_utterance(
            f,
            audio_file,
            reference,
            pruning_threshold=pruning_threshold
        )
        results.append(result)

        total_S += result["S"]
        total_D += result["D"]
        total_I += result["I"]
        total_N += result["N"]
        total_time += result["time_sec"]
        total_decode_time += result["decode_time_sec"]
        total_backtrace_time += result["backtrace_time_sec"]
        total_forward += result["forward_computations"]

        if result["hypothesis"] == "":
            empty_hyp_count += 1

        print("=" * 60)
        print("Audio:", result["audio_file"])
        print("Reference:", result["reference"])
        print("Hypothesis:", result["hypothesis"])
        print("S, D, I:", result["S"], result["D"], result["I"])
        print("Decode time:", result["decode_time_sec"])
        print("Backtrace time:", result["backtrace_time_sec"])
        print("Total time:", result["time_sec"])
        print("Forward computations:", result["forward_computations"])

    wer_value = (total_S + total_D + total_I) / total_N if total_N > 0 else float("inf")

    summary = {
        "experiment_name": experiment_name,
        "num_states": num_states,
        "num_arcs": num_arcs,
        "total_S": total_S,
        "total_D": total_D,
        "total_I": total_I,
        "total_N": total_N,
        "WER": wer_value,
        "total_time_sec": total_time,
        "avg_time_sec": total_time / len(results) if results else 0.0,
        "total_decode_time_sec": total_decode_time,
        "avg_decode_time_sec": total_decode_time / len(results) if results else 0.0,
        "total_backtrace_time_sec": total_backtrace_time,
        "avg_backtrace_time_sec": total_backtrace_time / len(results) if results else 0.0,
        "total_forward_computations": total_forward,
        "avg_forward_computations": total_forward / len(results) if results else 0.0,
        "empty_hypothesis_count": empty_hyp_count,
        "pruning_threshold": pruning_threshold,
        "continue_prob": continue_prob,
        "self_loop_prob": self_loop_prob,
        "use_unigram": use_unigram,
        "use_silence": use_silence,
    }

    return results, summary

In [10]:
import os
import wave
import audioop

src_dir = "recordings"
dst_dir = "recordings_fixed"
os.makedirs(dst_dir, exist_ok=True)

for fname in os.listdir(src_dir):
    if not fname.endswith(".wav"):
        continue

    src_path = os.path.join(src_dir, fname)
    dst_path = os.path.join(dst_dir, fname)

    with wave.open(src_path, "rb") as wf:
        n_channels = wf.getnchannels()
        sampwidth = wf.getsampwidth()
        framerate = wf.getframerate()
        n_frames = wf.getnframes()
        frames = wf.readframes(n_frames)

    # Convert stereo to mono if needed
    if n_channels == 2:
        frames = audioop.tomono(frames, sampwidth, 0.5, 0.5)
        n_channels = 1

    # Convert sample width to 16-bit if needed
    if sampwidth != 2:
        frames = audioop.lin2lin(frames, sampwidth, 2)
        sampwidth = 2

    # Resample to 16000 Hz if needed
    if framerate != 16000:
        frames, _ = audioop.ratecv(frames, sampwidth, n_channels, framerate, 16000, None)
        framerate = 16000

    with wave.open(dst_path, "wb") as wf:
        wf.setnchannels(n_channels)
        wf.setsampwidth(sampwidth)
        wf.setframerate(framerate)
        wf.writeframes(frames)

print("Done converting WAV files.")
print("Converted files:", len([f for f in os.listdir(dst_dir) if f.endswith('.wav')]))

Done converting WAV files.
Converted files: 48

In [11]:
recordings_dir = "recordings_fixed"
transcript_file = "recordings/my_recordings.txt"

audio_to_reference = load_transcripts(transcript_file, recordings_dir)

print("Number of recordings loaded:", len(audio_to_reference))

missing_files = [path for path in audio_to_reference if not os.path.exists(path)]
print("Missing files:", len(missing_files))
if missing_files[:10]:
    print("Examples of missing files:")
    for p in missing_files[:10]:
        print(p)

for k, v in list(audio_to_reference.items())[:5]:
    print(k, "->", v)

Number of recordings loaded: 48
Missing files: 0
recordings_fixed/1.wav -> peter piper picked
recordings_fixed/2.wav -> picked a peck
recordings_fixed/3.wav -> piper picked a
recordings_fixed/4.wav -> a peck of
recordings_fixed/5.wav -> peck of pickled

In [12]:
def check_transcripts_against_lexicon(audio_to_reference, lexicon):
    bad = []

    for audio_file, ref in audio_to_reference.items():
        words = normalize_text(ref).split()
        oov = [w for w in words if w not in lexicon]
        if oov:
            bad.append((audio_file, ref, oov))

    return bad

bad_transcripts = check_transcripts_against_lexicon(audio_to_reference, lex)

print("Number of transcript lines with OOV words:", len(bad_transcripts))
for item in bad_transcripts[:10]:
    print(item)

Number of transcript lines with OOV words: 0

In [13]:
experiments = [
    {
        "name": "Task 1 baseline",
        "continue_prob": 1.0,
        "self_loop_prob": 0.1,
        "use_unigram": False,
        "use_silence": False,
        "pruning_threshold": None,
        "unigram_probs": None
    },
    {
        "name": "Task 2: loop penalty",
        "continue_prob": 0.1,
        "self_loop_prob": 0.1,
        "use_unigram": False,
        "use_silence": False,
        "pruning_threshold": None,
        "unigram_probs": None
    },
    {
        "name": "Task 2: self-loop 0.4",
        "continue_prob": 0.1,
        "self_loop_prob": 0.4,
        "use_unigram": False,
        "use_silence": False,
        "pruning_threshold": None,
        "unigram_probs": None
    },
    {
        "name": "Task 2: + silence",
        "continue_prob": 0.1,
        "self_loop_prob": 0.4,
        "use_unigram": False,
        "use_silence": True,
        "pruning_threshold": None,
        "unigram_probs": None
    },
]

experiment_summaries = []
all_results = []

for exp in experiments:
    print("\n" + "#" * 70)
    print(exp["name"])
    print("#" * 70)

    results, summary = evaluate_dataset(
        audio_to_reference,
        continue_prob=exp["continue_prob"],
        self_loop_prob=exp["self_loop_prob"],
        use_unigram=exp["use_unigram"],
        use_silence=exp["use_silence"],
        pruning_threshold=exp["pruning_threshold"],
        unigram_probs=exp["unigram_probs"],
        experiment_name=exp["name"]
    )

    experiment_summaries.append(summary)

    for r in results:
        row = dict(r)
        row["experiment_name"] = exp["name"]
        all_results.append(row)

    for k, v in summary.items():
        print(f"{k}: {v}")

######################################################################
Task 1 baseline
######################################################################
============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: peppers picked wheres picked of peck of the the the the of peck of peppers peppers pickled piper of peck of the the peter piper wheres peppers picked wheres picked the the the the
S, D, I: 0 0 31
Decode time: 1.7428061962127686
Backtrace time: 0.0005471706390380859
Total time: 1.7433533668518066
Forward computations: 71898
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: peppers peter picked peck peppers picked wheres picked peter piper wheres the the the the of peck of the the peppers picked wheres picked peppers picked wheres picked the the the the
S, D, I: 1 0 29
Decode time: 1.1877102851867676
Backtrace time: 0.0004420280456542969
Total time: 1.1881523132324219
Forward computations: 52158
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peppers picked wheres picked peter piper wheres of peck of the the the the a a a a a a a a peppers picked wheres picked peter piper wheres the the
S, D, I: 1 0 30
Decode time: 1.2007005214691162
Backtrace time: 0.00046133995056152344
Total time: 1.2011618614196777
Forward computations: 52158
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a peppers picked wheres picked peter piper wheres the the of peck of the the peter piper wheres peppers picked wheres picked the the the the the the
S, D, I: 0 0 26
Decode time: 1.0291962623596191
Backtrace time: 0.0004012584686279297
Total time: 1.029597520828247
Forward computations: 46698
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: peppers picked wheres picked peppers picked wheres picked peter piper wheres the the of peck of the the of peck of the the peppers picked wheres picked the the
S, D, I: 1 0 26
Decode time: 1.2014763355255127
Backtrace time: 0.0004246234893798828
Total time: 1.2019009590148926
Forward computations: 54048
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: peppers peter picked peck peppers picked wheres picked peter piper wheres of peck of the the of peck of the the peppers picked wheres picked of peck of the the of peck of peter piper wheres peppers picked wheres picked peppers picked wheres picked
S, D, I: 1 0 41
Decode time: 1.304732084274292
Backtrace time: 0.0004725456237792969
Total time: 1.3052046298980713
Forward computations: 54048
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peter piper wheres of peck of peter piper wheres of peck of the the peppers peter peppers pickled piper peppers the the peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked the the the the
S, D, I: 1 0 44
Decode time: 1.883150339126587
Backtrace time: 0.0005292892456054688
Total time: 1.8836796283721924
Forward computations: 80928
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peppers picked wheres picked peter piper wheres the the the the of peck of peppers peppers pickled piper peppers picked wheres picked peppers picked wheres picked the the
S, D, I: 0 0 27
Decode time: 1.2596430778503418
Backtrace time: 0.00047659873962402344
Total time: 1.2601196765899658
Forward computations: 55728
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: peppers peter picked peck peppers picked wheres picked the the of peck of the the peppers picked wheres picked the the a a a a a a a a a a the the peppers picked wheres picked of peck of a a of peck of peter piper wheres peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked the the the the the the
S, D, I: 0 0 63
Decode time: 2.2219436168670654
Backtrace time: 0.0006177425384521484
Total time: 2.2225613594055176
Forward computations: 96888
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a a a peter piper wheres peter piper wheres of peck of peter piper wheres of peck of the the peppers picked of pickled of peck of a a of peck of peter piper wheres peter piper wheres the the
S, D, I: 1 0 38
Decode time: 1.5123827457427979
Backtrace time: 0.0004999637603759766
Total time: 1.5128827095031738
Forward computations: 68328
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: of peck of peppers picked wheres picked the the of peck of peppers peppers pickled piper of peck of the the of peck of a a a a peppers picked wheres picked peppers picked wheres picked the the
S, D, I: 3 0 33
Decode time: 1.4586846828460693
Backtrace time: 0.00047850608825683594
Total time: 1.4591631889343262
Forward computations: 66438
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: peppers peter picked peck peppers picked wheres picked a a a a of peck of the the the the of peck of the the of peck of of peck of a a a a a a a a peppers picked wheres picked peter piper wheres peppers picked wheres picked the the the the peppers picked wheres picked the the peter piper wheres the the the the the the
S, D, I: 1 0 63
Decode time: 2.0001072883605957
Backtrace time: 0.0006146430969238281
Total time: 2.0007219314575195
Forward computations: 88068
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: peppers peter picked peck peppers picked wheres picked the the peter piper wheres of peck of the the of peck of the the a a a a a a of peck of peppers picked wheres picked peppers picked wheres picked the the the the the the peppers picked wheres picked
S, D, I: 1 0 45
Decode time: 1.5541861057281494
Backtrace time: 0.0005612373352050781
Total time: 1.5547473430633545
Forward computations: 70008
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a peppers picked wheres picked the the of peck of the the the the the the the the the the of peck of peter piper wheres of peck of peter piper wheres peppers picked wheres picked the the the the the the the the the the the the
S, D, I: 1 0 44
Decode time: 1.9135358333587646
Backtrace time: 0.0005943775177001953
Total time: 1.9141302108764648
Forward computations: 80928
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: of peck of the the the the of peck of the the a a a a a a the the of peck of a a a a a a a a a a peppers picked wheres picked the the the the
S, D, I: 2 0 37
Decode time: 1.789160966873169
Backtrace time: 0.0005185604095458984
Total time: 1.7896795272827148
Forward computations: 79038
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peppers picked wheres picked a a a a a a of peck of peppers picked wheres picked the the peppers picked wheres picked the the of peck of the the peppers picked wheres picked the the
S, D, I: 1 0 34
Decode time: 1.236257791519165
Backtrace time: 0.0004780292510986328
Total time: 1.2367358207702637
Forward computations: 54048
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: the the of peck of peppers picked wheres picked the the the the of peck of of peck of the the a a a a the the peppers picked wheres picked of peck of the the peter piper wheres peppers picked wheres picked the the the the peppers picked wheres picked
S, D, I: 1 0 47
Decode time: 1.5721278190612793
Backtrace time: 0.0005018711090087891
Total time: 1.572629690170288
Forward computations: 70008

============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: peppers picked wheres picked of peck of a a a a of peck of the the the the the the a a a a a a a a the the peppers picked wheres picked the the of peck of peter piper wheres peppers peter picked peck the the peppers picked wheres picked the the the the the the
S, D, I: 1 0 54
Decode time: 1.834118127822876
Backtrace time: 0.0005517005920410156
Total time: 1.834669828414917
Forward computations: 80928
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: peppers picked wheres picked the the the the of peck of peter piper wheres a a of peck of peppers picked wheres picked the the the the peter piper wheres of peck of peter piper wheres peppers picked wheres picked
S, D, I: 0 0 36
Decode time: 1.3652994632720947
Backtrace time: 0.0004749298095703125
Total time: 1.365774393081665
Forward computations: 61188
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: peppers picked wheres picked peppers picked wheres picked the the of peck of peter piper wheres of peck of peter piper wheres the the the the of peck of peter piper wheres peppers picked wheres picked peppers picked wheres picked the the
S, D, I: 0 0 38
Decode time: 1.667220115661621
Backtrace time: 0.0005230903625488281
Total time: 1.66774320602417
Forward computations: 75468
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: peppers picked wheres picked peppers picked wheres picked peter piper wheres the the of peck of a a a a peppers picked wheres picked peppers picked wheres picked the the the the the the
S, D, I: 0 0 31
Decode time: 1.3091230392456055
Backtrace time: 0.00046181678771972656
Total time: 1.3095848560333252
Forward computations: 59298
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: peppers picked wheres picked peter piper wheres the the of peck of a a a a a a a a of peck of peter piper wheres the the peppers picked of pickled of peck of the the peter piper wheres the the the the
S, D, I: 1 0 38
Decode time: 1.9521033763885498
Backtrace time: 0.0005781650543212891
Total time: 1.952681541442871
Forward computations: 88068
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: peppers picked wheres picked peppers picked wheres picked peter piper wheres peter piper wheres peter piper wheres of peck of peter piper wheres of peck of a a a a a a a a a a peppers picked wheres picked peppers the wheres pickled peter peppers picked wheres picked the the a a a a a a a a a a the the the the the the the the
S, D, I: 1 0 64
Decode time: 2.2212445735931396
Backtrace time: 0.0007531642913818359
Total time: 2.2219977378845215
Forward computations: 96888
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: the the peppers picked wheres picked peter piper wheres the the peter piper wheres the the of peck of a a peppers picked wheres picked peter piper wheres peppers picked wheres picked peter piper wheres the the the the the the the the
S, D, I: 0 0 38
Decode time: 2.0621862411499023
Backtrace time: 0.0012331008911132812
Total time: 2.0634193420410156
Forward computations: 86178
============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: the the peppers picked wheres picked peter piper wheres peter piper wheres the the of peck of a a a a a a a a a a peppers picked wheres picked of peck of peppers peppers pickled piper the the a a a a a a peppers picked wheres picked the the the the
S, D, I: 0 0 49
Decode time: 2.1477906703948975
Backtrace time: 0.0006356239318847656
Total time: 2.1484262943267822
Forward computations: 95208
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: peppers picked wheres picked of peck of peter piper wheres peppers the wheres pickled peter of peck of peppers peppers pickled piper peppers picked wheres picked peppers peter picked peck peppers picked wheres picked
S, D, I: 0 0 31
Decode time: 1.65470290184021
Backtrace time: 0.0004942417144775391
Total time: 1.6551971435546875
Forward computations: 71898
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: the the peppers picked wheres picked peter piper wheres the the of peck of the the peppers picked of pickled of peck of peppers picked wheres picked the the a a a a peppers picked wheres picked peppers picked wheres picked the the peppers picked wheres picked
S, D, I: 0 0 43
Decode time: 1.910691499710083
Backtrace time: 0.0005631446838378906
Total time: 1.911254644393921
Forward computations: 86178
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: the the peppers picked wheres picked peter piper wheres of peck of the the of peck of the the peppers picked wheres picked of peck of the the peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked the the peppers picked wheres picked
S, D, I: 1 0 41
Decode time: 1.7266173362731934
Backtrace time: 0.0005176067352294922
Total time: 1.7271349430084229
Forward computations: 77148
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: peppers picked wheres picked peter piper wheres of peck of of peck of the the of peck of of peck of peter piper wheres peppers picked wheres picked the the the the peppers picked wheres picked
S, D, I: 0 0 33
Decode time: 1.4742634296417236
Backtrace time: 0.0004923343658447266
Total time: 1.4747557640075684
Forward computations: 66438
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: peppers picked wheres picked peppers picked wheres picked the the peter piper wheres of peck of a a a a a a a a a a peppers peter picked peck the the peppers peter peppers pickled piper peppers of peck of peppers the wheres pickled peter of peck of a a a a a a a a peppers picked wheres picked the the the the
S, D, I: 0 0 58
Decode time: 2.5036122798919678
Backtrace time: 0.0006685256958007812
Total time: 2.5042808055877686
Forward computations: 111378
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: the the peppers picked wheres picked the the the the of peck of peppers peppers pickled piper the the the the of peck of the the peter piper wheres the the peppers picked wheres picked of peck of the the a a peter piper wheres peppers picked wheres picked peppers picked wheres picked the the the the
S, D, I: 2 0 49
Decode time: 2.5425944328308105
Backtrace time: 0.0006849765777587891
Total time: 2.5432794094085693
Forward computations: 113058
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: the the peppers picked wheres picked peppers picked of pickled peter piper wheres of peck of peppers picked wheres picked peter piper wheres peppers picked of pickled peppers picked wheres picked peter piper wheres peppers peter picked peck the the the the the the peppers picked wheres picked peppers peppers pickled piper peppers picked wheres picked a a a a a a peppers picked wheres picked peppers picked wheres picked the the the the the the the the peppers peter picked peck
S, D, I: 1 0 73
Decode time: 2.9093565940856934
Backtrace time: 0.0008132457733154297
Total time: 2.910169839859009
Forward computations: 129228

============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: peppers peter picked peck peppers picked wheres picked peter piper wheres peter piper wheres peter piper wheres peter piper wheres the the the the of peck of of peck of a a peppers picked wheres picked of peck of peppers picked wheres picked the the the the a a a a a a the the peppers peppers pickled piper a a peppers picked wheres picked peppers picked of pickled the the a a peppers picked of pickled peppers picked wheres picked the the a a peter piper wheres peppers picked wheres picked the the the the
S, D, I: 0 0 89
Decode time: 3.506291151046753
Backtrace time: 0.0009007453918457031
Total time: 3.5071918964385986
Forward computations: 154218
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: peppers picked wheres picked peppers peppers pickled piper the the the the the the of peck of peppers picked wheres picked a a a a a a peppers picked wheres picked the the a a a a peppers picked wheres picked peter piper wheres the the peppers picked of pickled peppers picked wheres picked the the a a peter piper wheres peppers picked wheres picked the the the the the the the the the the
S, D, I: 1 0 69
Decode time: 2.8192176818847656
Backtrace time: 0.0007488727569580078
Total time: 2.8199665546417236
Forward computations: 123768
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: the the peppers peter picked peck the the the the of peck of peppers picked wheres picked a a a a the the peppers picked wheres picked peppers picked wheres picked a a a a a a peter piper wheres the the a a peter piper wheres peppers peter picked peck the the of peck of peter piper wheres peppers picked wheres picked peppers picked wheres picked the the
S, D, I: 1 0 64
Decode time: 2.6465260982513428
Backtrace time: 0.0012001991271972656
Total time: 2.64772629737854
Forward computations: 118518
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: the the peppers picked wheres picked peter piper wheres the the the the of peck of peppers picked wheres picked a a a a a a peppers picked wheres picked the the peppers peter peppers pickled piper peppers peppers picked wheres picked the the of peck of peppers peppers pickled piper peppers picked wheres picked the the a a a a a a a a a a peppers picked wheres picked peppers picked wheres picked the the peppers peter peppers pickled piper peppers peppers picked wheres picked the the peppers picked wheres picked the the
S, D, I: 0 0 89
Decode time: 3.480517625808716
Backtrace time: 0.0009014606475830078
Total time: 3.481419086456299
Forward computations: 154218
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: the the peppers picked wheres picked the the peter piper wheres the the the the a a the the of peck of peppers picked wheres picked peppers peppers pickled piper peppers picked wheres picked a a a a the the of peck of a a a a a a peppers picked wheres picked the the the the the the the the the the
S, D, I: 0 0 58
Decode time: 2.73711895942688
Backtrace time: 0.0006840229034423828
Total time: 2.7378029823303223
Forward computations: 114948
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: peppers peter picked peck peppers picked wheres picked the the the the of peck of the the a a a a a a the the of peck of peppers picked wheres picked the the a a a a peppers picked wheres picked peppers peppers pickled piper peppers picked of pickled a a of peck of of peck of peppers picked wheres picked peppers peter picked peck the the peppers picked wheres picked
S, D, I: 0 0 65
Decode time: 2.4253149032592773
Backtrace time: 0.0006999969482421875
Total time: 2.4260149002075195
Forward computations: 105918
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: the the of peck of the the the the of peck of peppers picked wheres picked peter piper wheres peppers picked wheres picked peppers picked wheres picked a a a a of peck of the the a a of peck of peter piper wheres the the peter piper wheres peppers peppers pickled piper of peck of peppers picked wheres picked the the a a peppers picked wheres picked of peck of the the a a of peck of peppers picked wheres picked peter piper wheres the the the the
S, D, I: 0 0 77
Decode time: 3.1010022163391113
Backtrace time: 0.0008192062377929688
Total time: 3.1018214225769043
Forward computations: 138258
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: the the peppers picked wheres picked peter piper wheres of peck of the the the the the the peppers picked wheres picked peppers picked wheres picked peter piper wheres peppers picked wheres picked peppers picked wheres picked the the the the the the peppers picked wheres picked the the the the the the the the the the the the peppers picked wheres picked peppers picked wheres picked
S, D, I: 2 0 61
Decode time: 1.9872009754180908
Backtrace time: 0.0006282329559326172
Total time: 1.9878292083740234
Forward computations: 88068
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peter piper wheres the the the the the the of peck of peppers peter picked peck peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked the the peter piper wheres peppers picked wheres picked peppers picked of pickled peppers picked wheres picked of peck of peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked of peck of peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked the the
S, D, I: 1 0 108
Decode time: 3.191636562347412
Backtrace time: 0.0008921623229980469
Total time: 3.19252872467041
Forward computations: 138258
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked peppers peter picked peck peppers picked wheres picked peter piper wheres peter piper wheres the the peter piper wheres the the peter piper wheres peppers peppers pickled piper the the of peck of peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked the the the the the the the the the the a a peter piper wheres peppers peter picked peck peppers picked wheres picked the the of peck of a a a a peppers picked wheres picked the the peppers picked wheres picked a a peppers picked wheres picked
S, D, I: 0 0 96
Decode time: 3.390077590942383
Backtrace time: 0.0008461475372314453
Total time: 3.3909237384796143
Forward computations: 141828
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: peppers picked wheres picked the the of peck of of peck of peter piper wheres of peck of of peck of of peck of of peck of the the peter piper wheres peppers peppers pickled piper a a a a a a a a a a a a of peck of peppers picked wheres picked peppers picked wheres picked the the the the peppers peppers pickled piper the the peppers picked wheres picked peppers peter picked peck peter piper wheres the the peppers picked of pickled peppers picked wheres picked the the of peck of peter piper wheres peppers peter picked peck peppers picked wheres picked peppers picked wheres picked the the peppers picked wheres picked
S, D, I: 1 0 108
Decode time: 3.2718141078948975
Backtrace time: 0.0009098052978515625
Total time: 3.272723913192749
Forward computations: 145398

============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: the the peppers picked wheres picked peter piper wheres of peck of the the of peck of peppers picked wheres picked the the the the the the a a a a the the peppers peppers pickled piper the the a a a a peppers picked wheres picked the the peppers picked wheres picked of peck of the the a a a a peter piper wheres peppers picked wheres picked the the peppers picked wheres picked peter piper wheres peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked a a a a a a peppers picked wheres picked
S, D, I: 1 0 93
Decode time: 3.9234166145324707
Backtrace time: 0.0009763240814208984
Total time: 3.9243929386138916
Forward computations: 172278
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peppers picked wheres picked the the peter piper wheres of peck of the the peter piper wheres of peck of a a a a peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked the the the the the the the the peppers picked wheres picked the the the the of peck of peppers picked wheres picked of peck of peter piper wheres peppers peter picked peck peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers peppers pickled piper peppers picked wheres picked
S, D, I: 0 0 85
Decode time: 2.8569891452789307
Backtrace time: 0.0008013248443603516
Total time: 2.857790470123291
Forward computations: 127338
============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: of peck of the the of peck of of peck of a a a a a a of peck of the the of peck of the the of peck of the the peppers picked wheres picked peter piper wheres peppers picked wheres picked the the the the the the peppers picked wheres picked the the peppers picked wheres picked peter piper wheres peppers peter picked peck peppers picked wheres picked peppers picked wheres picked
S, D, I: 1 0 69
Decode time: 2.9200961589813232
Backtrace time: 0.0007343292236328125
Total time: 2.920830488204956
Forward computations: 129228
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked peppers picked wheres picked peter piper wheres peter piper wheres the the the the peppers picked wheres picked peppers picked wheres picked peppers peppers pickled piper peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked of peck of peppers picked wheres picked a a peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked the the
S, D, I: 1 0 60
Decode time: 3.2289371490478516
Backtrace time: 0.0007724761962890625
Total time: 3.2297096252441406
Forward computations: 138258
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: peppers picked wheres picked peter piper wheres of peck of peter piper wheres peter piper wheres peter piper wheres of peck of a a a a a a of peck of peppers picked wheres picked the the the the the the peppers peter picked peck peppers picked wheres picked peppers peter picked peck peppers picked wheres picked the the the the the the a a peppers peppers pickled piper a a a a a a a a peppers peppers pickled piper peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked of pickled
S, D, I: 0 0 92
Decode time: 3.5783801078796387
Backtrace time: 0.0009160041809082031
Total time: 3.579296112060547
Forward computations: 157788
experiment_name: Task 1 baseline
num_states: 116
num_arcs: 230
total_S: 32
total_D: 0
total_I: 2617
total_N: 237
WER: 11.177215189873417
total_time_sec: 104.44475984573364
avg_time_sec: 2.1759324967861176
total_decode_time_sec: 104.41326308250427
avg_decode_time_sec: 2.175276314218839
total_backtrace_time_sec: 0.03149676322937012
avg_backtrace_time_sec: 0.0006561825672785441
total_forward_computations: 4588254
avg_forward_computations: 95588.625
empty_hypothesis_count: 0
pruning_threshold: None
continue_prob: 1.0
self_loop_prob: 0.1
use_unigram: False
use_silence: False

######################################################################
Task 2: loop penalty
######################################################################
============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: peppers picked wheres picked the the the the of peck of peppers peppers pickled piper of peck of the the peter piper wheres the the
S, D, I: 1 0 22
Decode time: 1.6026015281677246
Backtrace time: 0.0004687309265136719
Total time: 1.6030702590942383
Forward computations: 71898
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: peppers peter picked peck peppers picked wheres picked the the the the of peck of the the peppers picked wheres picked the the
S, D, I: 1 0 20
Decode time: 1.2060949802398682
Backtrace time: 0.00041365623474121094
Total time: 1.2065086364746094
Forward computations: 52158
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: peppers picked wheres picked peter piper wheres of peck of the the the the a a peppers picked wheres picked peter piper wheres the the
S, D, I: 1 0 22
Decode time: 1.2016124725341797
Backtrace time: 0.0009951591491699219
Total time: 1.2026076316833496
Forward computations: 52158
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: peppers picked wheres picked the the of peck of the the peter piper wheres peppers picked wheres picked the the
S, D, I: 1 0 17
Decode time: 1.074178695678711
Backtrace time: 0.0003955364227294922
Total time: 1.0745742321014404
Forward computations: 46698
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: peppers picked wheres picked peppers picked wheres picked peter piper wheres the the of peck of the the of peck of the the
S, D, I: 1 0 20
Decode time: 1.289318323135376
Backtrace time: 0.0004203319549560547
Total time: 1.289738655090332
Forward computations: 54048
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: peppers peter picked peck peppers picked wheres picked peter piper wheres the the of peck of the the peppers picked wheres picked of peck of the the peter piper wheres peppers picked wheres picked peppers picked wheres picked
S, D, I: 1 0 35
Decode time: 1.2858879566192627
Backtrace time: 0.0004417896270751953
Total time: 1.286329746246338
Forward computations: 54048
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: peppers picked wheres picked peppers picked wheres picked of peck of the the peppers peter peppers pickled piper peppers the the peppers picked wheres picked the the the the
S, D, I: 1 0 26
Decode time: 1.8086655139923096
Backtrace time: 0.0004897117614746094
Total time: 1.8091552257537842
Forward computations: 80928
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: peppers picked wheres picked peter piper wheres the the the the of peck of peppers peppers pickled piper peppers picked wheres picked the the
S, D, I: 0 0 21
Decode time: 1.2562336921691895
Backtrace time: 0.0004258155822753906
Total time: 1.2566595077514648
Forward computations: 55728
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: peppers picked wheres picked the the of peck of the the peppers picked wheres picked the the a a peppers picked wheres picked of peck of of peck of peter piper wheres peppers picked wheres picked the the
S, D, I: 1 0 35
Decode time: 2.1994590759277344
Backtrace time: 0.0005509853363037109
Total time: 2.200010061264038
Forward computations: 96888

============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peter piper wheres of peck of the the peppers picked of pickled of peck of a a of peck of peter piper wheres the the
S, D, I: 1 0 33
Decode time: 1.5956826210021973
Backtrace time: 0.00048542022705078125
Total time: 1.596168041229248
Forward computations: 68328
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: of peck of peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a peppers picked wheres picked peppers picked wheres picked the the
S, D, I: 3 0 26
Decode time: 1.5307347774505615
Backtrace time: 0.0004646778106689453
Total time: 1.5311994552612305
Forward computations: 66438
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: peppers picked wheres picked a a of peck of the the of peck of the the of peck of of peck of a a peppers picked wheres picked peter piper wheres peppers picked wheres picked peter piper wheres the the the the
S, D, I: 1 0 37
Decode time: 2.0632851123809814
Backtrace time: 0.0005550384521484375
Total time: 2.06384015083313
Forward computations: 88068
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: peppers peter picked peck peppers picked wheres picked the the peter piper wheres of peck of the the of peck of the the a a of peck of peppers picked wheres picked the the peppers picked wheres picked
S, D, I: 1 0 33
Decode time: 1.6167292594909668
Backtrace time: 0.0004763603210449219
Total time: 1.6172056198120117
Forward computations: 70008
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a peppers picked wheres picked of peck of the the the the the the the the of peck of peter piper wheres of peck of peter piper wheres peppers picked wheres picked the the the the
S, D, I: 1 0 32
Decode time: 1.8650546073913574
Backtrace time: 0.0005185604095458984
Total time: 1.8655731678009033
Forward computations: 80928
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: of peck of the the the the of peck of the the a a peter piper wheres a a peppers picked wheres picked the the
S, D, I: 2 0 21
Decode time: 1.8575506210327148
Backtrace time: 0.0005011558532714844
Total time: 1.8580517768859863
Forward computations: 79038
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peppers picked wheres picked peter piper wheres the the peppers picked wheres picked of peck of the the peppers picked wheres picked the the
S, D, I: 1 0 22
Decode time: 1.2354717254638672
Backtrace time: 0.0004546642303466797
Total time: 1.2359263896942139
Forward computations: 54048
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: the the peppers picked wheres picked the the the the of peck of the the a a the the peppers picked wheres picked of peck of the the peter piper wheres peppers picked wheres picked peppers picked wheres picked
S, D, I: 1 0 35
Decode time: 1.5518195629119873
Backtrace time: 0.0004799365997314453
Total time: 1.5522994995117188
Forward computations: 70008
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: peppers picked wheres picked a a of peck of peppers picked wheres picked the the a a a a the the peppers picked wheres picked the the of peck of peter piper wheres peppers peter picked peck the the the the
S, D, I: 2 0 37
Decode time: 1.82039475440979
Backtrace time: 0.0005178451538085938
Total time: 1.8209125995635986
Forward computations: 80928
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: peppers picked wheres picked the the the the of peck of peter piper wheres a a of peck of peppers picked wheres picked the the the the peter piper wheres of peck of peter piper wheres peppers picked wheres picked
S, D, I: 0 0 36
Decode time: 1.3390154838562012
Backtrace time: 0.0004458427429199219
Total time: 1.339461326599121
Forward computations: 61188
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: peppers picked wheres picked peppers picked wheres picked the the of peck of peter piper wheres of peck of peter piper wheres the the the the of peck of peter piper wheres peppers picked wheres picked the the
S, D, I: 0 0 34
Decode time: 1.7539618015289307
Backtrace time: 0.0009057521820068359
Total time: 1.7548675537109375
Forward computations: 75468
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: peppers picked wheres picked peppers picked wheres picked peter piper wheres the the of peck of a a peppers picked wheres picked peppers picked wheres picked the the
S, D, I: 0 0 25
Decode time: 1.4149038791656494
Backtrace time: 0.00044083595275878906
Total time: 1.4153447151184082
Forward computations: 59298
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: peppers picked wheres picked peter piper wheres the the of peck of a a of peck of peter piper wheres the the peppers picked of pickled of peck of the the peter piper wheres the the
S, D, I: 1 0 30
Decode time: 2.0848822593688965
Backtrace time: 0.0011644363403320312
Total time: 2.0860466957092285
Forward computations: 88068
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: peppers picked wheres picked peppers picked wheres picked peter piper wheres peter piper wheres of peck of peter piper wheres of peck of a a peppers picked wheres picked peppers the wheres pickled peter peppers picked wheres picked the the a a a a a a a a peppers picked wheres picked the the
S, D, I: 1 0 49
Decode time: 2.302964448928833
Backtrace time: 0.0005946159362792969
Total time: 2.3035590648651123
Forward computations: 96888
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: the the peppers picked wheres picked the the peter piper wheres the the of peck of a a peppers picked wheres picked peter piper wheres peppers picked wheres picked peter piper wheres the the the the
S, D, I: 0 0 31
Decode time: 2.2149410247802734
Backtrace time: 0.000537872314453125
Total time: 2.2154788970947266
Forward computations: 86178
============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: the the peppers picked wheres picked peter piper wheres the the of peck of a a peppers picked wheres picked of peck of peppers peppers pickled piper the the a a a a peppers picked wheres picked the the
S, D, I: 0 0 34
Decode time: 2.3937556743621826
Backtrace time: 0.0005490779876708984
Total time: 2.3943047523498535
Forward computations: 95208
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: peppers picked wheres picked peter piper wheres peppers the wheres pickled peter of peck of peppers peppers pickled piper peppers picked wheres picked
S, D, I: 0 0 20
Decode time: 1.8780531883239746
Backtrace time: 0.0006666183471679688
Total time: 1.8787198066711426
Forward computations: 71898
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: peppers picked wheres picked peter piper wheres the the of peck of the the peppers picked of pickled of peck of peppers picked wheres picked a a peppers picked wheres picked peppers picked wheres picked
S, D, I: 0 0 31
Decode time: 2.0086042881011963
Backtrace time: 0.0005230903625488281
Total time: 2.009127378463745
Forward computations: 86178

============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: the the peppers picked wheres picked peter piper wheres of peck of the the of peck of the the peppers picked wheres picked of peck of the the peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked
S, D, I: 1 0 39
Decode time: 2.036686420440674
Backtrace time: 0.0012614727020263672
Total time: 2.0379478931427
Forward computations: 77148
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: peppers picked wheres picked peter piper wheres of peck of of peck of of peck of of peck of peter piper wheres peppers picked wheres picked peppers picked wheres picked
S, D, I: 1 0 27
Decode time: 2.1089601516723633
Backtrace time: 0.00046634674072265625
Total time: 2.109426498413086
Forward computations: 66438
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: peppers picked wheres picked peppers picked wheres picked the the peter piper wheres of peck of a a a a peppers peter picked peck the the peppers peter peppers pickled piper peppers of peck of peppers the wheres pickled peter of peck of a a peppers picked wheres picked the the
S, D, I: 0 0 44
Decode time: 3.1672589778900146
Backtrace time: 0.0006430149078369141
Total time: 3.1679019927978516
Forward computations: 111378
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: the the peppers picked wheres picked the the the the of peck of peppers peppers pickled piper the the the the of peck of the the peter piper wheres the the peppers picked wheres picked of peck of the the a a peter piper wheres peppers picked wheres picked the the the the
S, D, I: 2 0 45
Decode time: 3.3026070594787598
Backtrace time: 0.0006756782531738281
Total time: 3.3032827377319336
Forward computations: 113058
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: the the peppers picked wheres picked peppers picked of pickled peter piper wheres of peck of peppers picked wheres picked peter piper wheres peppers picked of pickled peppers picked wheres picked peter piper wheres peppers peter picked peck the the the the peppers picked wheres picked peppers peppers pickled piper peppers picked wheres picked a a peppers picked wheres picked the the peppers picked wheres picked
S, D, I: 1 0 57
Decode time: 3.093677520751953
Backtrace time: 0.0007338523864746094
Total time: 3.0944113731384277
Forward computations: 129228
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: peppers peter picked peck peppers picked wheres picked peter piper wheres the the the the of peck of of peck of a a peppers picked wheres picked of peck of peppers picked wheres picked a a a a the the peppers peppers pickled piper a a peppers picked wheres picked peppers picked of pickled the the a a peppers picked of pickled peppers picked wheres picked the the a a peter piper wheres peppers picked wheres picked the the
S, D, I: 0 0 72
Decode time: 3.477386236190796
Backtrace time: 0.0008454322814941406
Total time: 3.47823166847229
Forward computations: 154218
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: peppers picked wheres picked peppers peppers pickled piper the the the the the the of peck of peppers picked wheres picked a a peppers picked wheres picked the the a a peppers picked wheres picked peter piper wheres the the peppers picked of pickled peppers picked wheres picked the the a a peter piper wheres peppers picked wheres picked the the
S, D, I: 1 0 55
Decode time: 2.821295976638794
Backtrace time: 0.0007021427154541016
Total time: 2.821998119354248
Forward computations: 123768
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: the the peppers peter picked peck the the the the of peck of peppers picked wheres picked a a peppers picked wheres picked peppers picked wheres picked a a a a peter piper wheres the the peter piper wheres peppers peter picked peck the the of peck of peter piper wheres peppers picked wheres picked the the
S, D, I: 1 0 52
Decode time: 2.714669942855835
Backtrace time: 0.0006787776947021484
Total time: 2.715348720550537
Forward computations: 118518
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: the the peppers picked wheres picked peter piper wheres the the the the of peck of peppers picked wheres picked a a peppers picked wheres picked peppers peter peppers pickled piper peppers peppers picked wheres picked of peck of peppers peppers pickled piper peppers picked wheres picked a a peppers picked wheres picked peppers peter peppers pickled piper peppers peppers picked wheres picked the the
S, D, I: 0 0 59
Decode time: 3.5063424110412598
Backtrace time: 0.0008091926574707031
Total time: 3.5071516036987305
Forward computations: 154218
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: the the peppers picked wheres picked peter piper wheres the the the the the the of peck of peppers picked wheres picked peppers peppers pickled piper peppers picked wheres picked a a the the of peck of a a peppers picked wheres picked the the
S, D, I: 0 0 40
Decode time: 2.801478385925293
Backtrace time: 0.0006287097930908203
Total time: 2.802107095718384
Forward computations: 114948
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: peppers peter picked peck peppers picked wheres picked the the the the of peck of a a the the of peck of peppers picked wheres picked a a a a peppers picked wheres picked peppers peppers pickled piper peppers picked of pickled a a of peck of peppers picked wheres picked peppers picked wheres picked
S, D, I: 0 0 48
Decode time: 2.5905497074127197
Backtrace time: 0.0006239414215087891
Total time: 2.5911736488342285
Forward computations: 105918
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: the the the the the the of peck of peppers picked wheres picked peter piper wheres peppers picked wheres picked peppers picked wheres picked a a of peck of the the a a peter piper wheres peter piper wheres peppers peppers pickled piper of peck of peppers picked wheres picked the the a a peppers picked wheres picked of peck of the the of peck of peppers picked wheres picked peter piper wheres the the
S, D, I: 0 0 63
Decode time: 3.250654697418213
Backtrace time: 0.0008094310760498047
Total time: 3.2514641284942627
Forward computations: 138258
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: the the peppers picked wheres picked peter piper wheres of peck of the the peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peter piper wheres peppers picked of pickled the the peppers picked wheres picked the the the the the the the the the the peppers picked wheres picked peppers picked wheres picked
S, D, I: 2 0 51
Decode time: 2.0296576023101807
Backtrace time: 0.0006170272827148438
Total time: 2.0302746295928955
Forward computations: 88068
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked the the the the of peck of peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked the the peter piper wheres peppers picked wheres picked peppers picked of pickled peppers picked wheres picked of peck of peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked of peck of peppers picked wheres picked peppers picked wheres picked the the
S, D, I: 1 0 83
Decode time: 3.1930251121520996
Backtrace time: 0.0008075237274169922
Total time: 3.1938326358795166
Forward computations: 138258

============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked peppers picked wheres picked peter piper wheres peter piper wheres peter piper wheres the the peter piper wheres peppers peppers pickled piper the the of peck of peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked the the peter piper wheres the the of peck of a a peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked
S, D, I: 1 0 62
Decode time: 3.3828887939453125
Backtrace time: 0.00077056884765625
Total time: 3.3836593627929688
Forward computations: 141828
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: peppers picked wheres picked the the of peck of of peck of peter piper wheres of peck of of peck of of peck of of peck of the the peter piper wheres peppers peppers pickled piper peter piper wheres peppers picked wheres picked peppers picked wheres picked peppers peppers pickled piper the the peppers picked wheres picked peppers peter picked peck peter piper wheres the the peppers picked of pickled peppers picked wheres picked the the of peck of peter piper wheres peppers peter picked peck peppers picked wheres picked peppers picked wheres picked
S, D, I: 1 0 86
Decode time: 3.3298680782318115
Backtrace time: 0.0008661746978759766
Total time: 3.3307342529296875
Forward computations: 145398
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: the the peppers picked wheres picked peter piper wheres of peck of the the of peck of peppers picked wheres picked the the the the a a the the peppers peppers pickled piper the the a a peppers picked wheres picked the the peppers picked wheres picked of peck of the the a a peter piper wheres peppers picked wheres picked peppers picked wheres picked peter piper wheres peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked a a a a peppers picked wheres picked
S, D, I: 1 0 81
Decode time: 3.8899288177490234
Backtrace time: 0.0009794235229492188
Total time: 3.8909082412719727
Forward computations: 172278
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peppers picked wheres picked peter piper wheres of peck of the the peter piper wheres of peck of a a peppers picked wheres picked peppers picked wheres picked peppers picked wheres picked of peck of peppers picked wheres picked of peck of peter piper wheres peppers peter picked peck peppers picked wheres picked peppers peppers pickled piper peppers picked wheres picked
S, D, I: 0 0 57
Decode time: 2.9702670574188232
Backtrace time: 0.0007398128509521484
Total time: 2.9710068702697754
Forward computations: 127338
============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: of peck of the the of peck of of peck of a a the the of peck of peppers picked wheres picked the the peppers picked wheres picked peter piper wheres peppers picked wheres picked the the the the the the peppers picked wheres picked the the peppers picked wheres picked peter piper wheres peppers picked wheres picked
S, D, I: 1 0 53
Decode time: 2.934251070022583
Backtrace time: 0.0007622241973876953
Total time: 2.9350132942199707
Forward computations: 129228
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked peppers picked wheres picked peter piper wheres peter piper wheres the the the the peppers picked wheres picked peppers picked wheres picked peppers peppers pickled piper peppers picked wheres picked peppers picked wheres picked of peck of peppers picked wheres picked peppers picked wheres picked the the
S, D, I: 1 0 46
Decode time: 3.1478464603424072
Backtrace time: 0.0007166862487792969
Total time: 3.1485631465911865
Forward computations: 138258
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: peppers picked wheres picked peter piper wheres peter piper wheres of peck of a a peppers peter picked peck peppers picked wheres picked the the the the peppers peter picked peck peppers picked wheres picked peppers peter picked peck peppers picked wheres picked the the peppers peppers pickled piper a a peppers peppers pickled piper peppers picked wheres picked peppers picked wheres picked peppers picked of pickled
S, D, I: 0 0 62
Decode time: 3.7051985263824463
Backtrace time: 0.0008373260498046875
Total time: 3.706035852432251
Forward computations: 157788
experiment_name: Task 2: loop penalty
num_states: 116
num_arcs: 230
total_S: 38
total_D: 0
total_I: 1966
total_N: 237
WER: 8.455696202531646
total_time_sec: 108.93721461296082
avg_time_sec: 2.2695253044366837
total_decode_time_sec: 108.90635633468628
avg_decode_time_sec: 2.2688824236392975
total_backtrace_time_sec: 0.030858278274536133
avg_backtrace_time_sec: 0.0006428807973861694
total_forward_computations: 4588254
avg_forward_computations: 95588.625
empty_hypothesis_count: 0
pruning_threshold: None
continue_prob: 0.1
self_loop_prob: 0.1
use_unigram: False
use_silence: False

######################################################################
Task 2: self-loop 0.4
######################################################################
============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: the the the the of peck of peppers peppers pickled piper of peck of the the a a
S, D, I: 2 0 15
Decode time: 1.6275136470794678
Backtrace time: 0.000438690185546875
Total time: 1.6279523372650146
Forward computations: 71898
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: peppers peter picked peck the the of peck of peppers picked wheres picked a a
S, D, I: 1 0 12
Decode time: 1.162283182144165
Backtrace time: 0.0004112720489501953
Total time: 1.1626944541931152
Forward computations: 52158
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 11
Decode time: 1.2443315982818604
Backtrace time: 0.00039196014404296875
Total time: 1.2447235584259033
Forward computations: 52158
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: of peck of the the peter piper wheres a a
S, D, I: 1 0 7
Decode time: 1.179361343383789
Backtrace time: 0.00038170814514160156
Total time: 1.1797430515289307
Forward computations: 46698
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: peppers peter picked peck the the of peck of the the of peck of the the
S, D, I: 1 0 13
Decode time: 1.217404842376709
Backtrace time: 0.00040650367736816406
Total time: 1.2178113460540771
Forward computations: 54048
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: of peck of the the peppers picked wheres picked peter piper wheres a a
S, D, I: 1 0 11
Decode time: 1.2458314895629883
Backtrace time: 0.0003952980041503906
Total time: 1.2462267875671387
Forward computations: 54048
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: peppers picked wheres picked of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 14
Decode time: 1.8254873752593994
Backtrace time: 0.00046515464782714844
Total time: 1.8259525299072266
Forward computations: 80928
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: peter piper wheres the the of peck of peppers peppers pickled piper a a
S, D, I: 1 0 11
Decode time: 1.3823039531707764
Backtrace time: 0.00038933753967285156
Total time: 1.3826932907104492
Forward computations: 55728

============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: the the peppers picked wheres picked a a of peck of peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 16
Decode time: 2.4250121116638184
Backtrace time: 0.0005664825439453125
Total time: 2.4255785942077637
Forward computations: 96888
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 20
Decode time: 1.5570080280303955
Backtrace time: 0.00045180320739746094
Total time: 1.557459831237793
Forward computations: 68328
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a peppers picked wheres picked a a
S, D, I: 2 0 19
Decode time: 1.5306651592254639
Backtrace time: 0.0004582405090332031
Total time: 1.531123399734497
Forward computations: 66438
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: a a of peck of the the of peck of of peck of a a peter piper wheres a a
S, D, I: 1 1 16
Decode time: 2.0005693435668945
Backtrace time: 0.0004982948303222656
Total time: 2.001067638397217
Forward computations: 88068
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: the the peter piper wheres of peck of the the of peck of the the of peck of a a
S, D, I: 3 0 15
Decode time: 1.5618326663970947
Backtrace time: 0.0004572868347167969
Total time: 1.5622899532318115
Forward computations: 70008
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: the the the the of peck of peter piper wheres of peck of peter piper wheres the the
S, D, I: 3 0 13
Decode time: 1.801004409790039
Backtrace time: 0.0004763603210449219
Total time: 1.801480770111084
Forward computations: 80928
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: the the the the of peck of a a of peck of a a peppers picked wheres picked a a
S, D, I: 2 0 16
Decode time: 1.76442289352417
Backtrace time: 0.00046539306640625
Total time: 1.7648882865905762
Forward computations: 79038
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: peter piper wheres the the of peck of the the the the
S, D, I: 2 0 8
Decode time: 1.208021879196167
Backtrace time: 0.0003819465637207031
Total time: 1.2084038257598877
Forward computations: 54048
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: the the the the of peck of a a the the peppers picked wheres picked the the peter piper wheres the the
S, D, I: 3 0 18
Decode time: 1.5898189544677734
Backtrace time: 0.0004763603210449219
Total time: 1.5902953147888184
Forward computations: 70008
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: a a of peck of a a the the peppers picked wheres picked the the peter piper wheres the the
S, D, I: 3 0 16
Decode time: 1.9318771362304688
Backtrace time: 0.00047969818115234375
Total time: 1.932356834411621
Forward computations: 80928
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: the the the the of peck of peppers peppers pickled piper the the peter piper wheres
S, D, I: 3 0 12
Decode time: 1.3860838413238525
Backtrace time: 0.0004341602325439453
Total time: 1.3865180015563965
Forward computations: 61188
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: the the of peck of peter piper wheres the the the the of peck of peter piper wheres the the
S, D, I: 2 0 16
Decode time: 1.7492642402648926
Backtrace time: 0.0004725456237792969
Total time: 1.7497367858886719
Forward computations: 75468
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: peppers peter picked peck peter piper wheres the the of peck of a a a a
S, D, I: 0 0 13
Decode time: 1.3332757949829102
Backtrace time: 0.0003886222839355469
Total time: 1.3336644172668457
Forward computations: 59298
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: peter piper wheres of peck of a a of peck of the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 2 0 19
Decode time: 2.037616729736328
Backtrace time: 0.0005087852478027344
Total time: 2.038125514984131
Forward computations: 88068
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: peter piper wheres of peck of of peck of a a peppers the wheres pickled peter a a the the
S, D, I: 2 0 15
Decode time: 2.20167875289917
Backtrace time: 0.0005755424499511719
Total time: 2.202254295349121
Forward computations: 96888
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: the the peter piper wheres the the of peck of a a the the peter piper wheres a a
S, D, I: 1 0 14
Decode time: 1.9481868743896484
Backtrace time: 0.0004851818084716797
Total time: 1.9486720561981201
Forward computations: 86178
============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: peter piper wheres of peck of a a of peck of peppers peppers pickled piper a a a a
S, D, I: 2 0 14
Decode time: 2.1602041721343994
Backtrace time: 0.0004940032958984375
Total time: 2.160698175430298
Forward computations: 95208
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: peter piper wheres peppers the wheres pickled peter of peck of peppers peppers pickled piper the the
S, D, I: 0 0 14
Decode time: 1.7314424514770508
Backtrace time: 0.0004324913024902344
Total time: 1.731874942779541
Forward computations: 71898
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: peter piper wheres of peck of the the peppers picked wheres picked of peck of a a a a
S, D, I: 1 0 15
Decode time: 1.957556962966919
Backtrace time: 0.00048828125
Total time: 1.958045244216919
Forward computations: 86178
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: peter piper wheres of peck of of peck of the the the the peppers picked wheres picked a a
S, D, I: 2 0 14
Decode time: 1.837932825088501
Backtrace time: 0.00047850608825683594
Total time: 1.8384113311767578
Forward computations: 77148
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: peter piper wheres of peck of of peck of of peck of peter piper wheres a a
S, D, I: 2 0 14
Decode time: 1.6385376453399658
Backtrace time: 0.00044035911560058594
Total time: 1.6389780044555664
Forward computations: 66438
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: peter piper wheres of peck of a a the the peppers peter peppers pickled piper peppers peppers the wheres pickled peter of peck of a a a a
S, D, I: 2 0 21
Decode time: 2.575986623764038
Backtrace time: 0.0005893707275390625
Total time: 2.576575994491577
Forward computations: 111378

============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: the the the the of peck of peppers peppers pickled piper the the of peck of the the of peck of the the peppers picked wheres picked of peck of the the peter piper wheres the the
S, D, I: 4 0 29
Decode time: 2.7035889625549316
Backtrace time: 0.0006384849548339844
Total time: 2.7042274475097656
Forward computations: 113058
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: the the peter piper wheres of peck of a a of peck of peppers picked of pickled peppers picked wheres picked peter piper wheres the the peppers picked wheres picked peppers peppers pickled piper a a a a
S, D, I: 1 0 29
Decode time: 3.190463066101074
Backtrace time: 0.0006444454193115234
Total time: 3.1911075115203857
Forward computations: 129228
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: the the the the of peck of a a peppers picked wheres picked of peck of a a peppers peppers pickled piper a a peppers picked wheres picked peppers picked of pickled a a peppers picked wheres picked a a peter piper wheres the the
S, D, I: 2 0 38
Decode time: 3.582874298095703
Backtrace time: 0.0007603168487548828
Total time: 3.583634614944458
Forward computations: 154218
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: peppers peppers pickled piper the the of peck of a a a a the the peppers picked of pickled a a peter piper wheres a a
S, D, I: 2 0 20
Decode time: 2.98504638671875
Backtrace time: 0.0006110668182373047
Total time: 2.9856574535369873
Forward computations: 123768
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: the the the the of peck of a a peppers picked wheres picked a a peter piper wheres the the peter piper wheres of peck of peter piper wheres a a
S, D, I: 3 0 26
Decode time: 2.770697832107544
Backtrace time: 0.0006146430969238281
Total time: 2.7713124752044678
Forward computations: 118518
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: the the the the of peck of a a peppers peter peppers pickled piper peppers of peck of peppers peppers pickled piper a a peter piper wheres the the
S, D, I: 3 0 23
Decode time: 3.546421766281128
Backtrace time: 0.0007245540618896484
Total time: 3.5471463203430176
Forward computations: 154218
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: the the the the of peck of peppers peppers pickled piper a a a a a a
S, D, I: 3 0 12
Decode time: 2.770822525024414
Backtrace time: 0.0008394718170166016
Total time: 2.7716619968414307
Forward computations: 114948
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: peppers picked wheres picked the the the the of peck of a a the the of peck of a a peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 22
Decode time: 2.564650297164917
Backtrace time: 0.0005686283111572266
Total time: 2.565218925476074
Forward computations: 105918
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: the the the the of peck of the the peppers peter picked peck a a of peck of a a peter piper wheres peter piper wheres peppers peppers pickled piper of peck of a a of peck of a a of peck of peppers picked wheres picked peter piper wheres the the
S, D, I: 1 0 40
Decode time: 3.1114277839660645
Backtrace time: 0.0007221698760986328
Total time: 3.112149953842163
Forward computations: 138258
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: peppers the wheres pickled peter peter piper wheres of peck of the the peppers picked wheres picked of peck of the the
S, D, I: 2 0 16
Decode time: 1.9973430633544922
Backtrace time: 0.0004885196685791016
Total time: 1.9978315830230713
Forward computations: 88068
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked the the of peck of peppers picked of pickled peppers picked wheres picked of peck of peppers picked wheres picked of peck of peppers picked wheres picked the the
S, D, I: 3 0 28
Decode time: 3.208930492401123
Backtrace time: 0.0006966590881347656
Total time: 3.209627151489258
Forward computations: 138258
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked the the peter piper wheres of peck of the the of peck of the the peter piper wheres of peck of a a peppers picked wheres picked peppers picked wheres picked
S, D, I: 2 0 30
Decode time: 3.1966116428375244
Backtrace time: 0.0006811618804931641
Total time: 3.1972928047180176
Forward computations: 141828
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: the the of peck of of peck of of peck of of peck of the the peppers peppers pickled piper peppers peter picked peck peppers peppers pickled piper the the peppers picked wheres picked the the peppers picked wheres picked of peck of peter piper wheres peppers picked wheres picked
S, D, I: 2 0 42
Decode time: 3.3172879219055176
Backtrace time: 0.0007107257843017578
Total time: 3.3179986476898193
Forward computations: 145398
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: of peck of the the peppers picked wheres picked a a peppers peppers pickled piper the the a a the the peter piper wheres the the peter piper wheres peter piper wheres peppers picked wheres picked
S, D, I: 3 0 29
Decode time: 4.527723073959351
Backtrace time: 0.0007846355438232422
Total time: 4.528507709503174
Forward computations: 172278
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: peter piper wheres peter piper wheres of peck of a a peppers picked wheres picked of peck of a a of peck of peter piper wheres peppers peppers pickled piper a a
S, D, I: 2 0 26
Decode time: 4.795729398727417
Backtrace time: 0.0006597042083740234
Total time: 4.796389102935791
Forward computations: 127338
============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: the the of peck of of peck of a a of peck of the the peter piper wheres the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 2 0 26
Decode time: 2.9400277137756348
Backtrace time: 0.0006413459777832031
Total time: 2.940669059753418
Forward computations: 129228
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: the the the the peppers picked wheres picked peppers peppers pickled piper peppers picked wheres picked of peck of peppers picked wheres picked the the
S, D, I: 2 0 20
Decode time: 3.384223222732544
Backtrace time: 0.0006546974182128906
Total time: 3.384877920150757
Forward computations: 138258
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a peppers peppers pickled piper peppers picked wheres picked
S, D, I: 0 0 31
Decode time: 3.5689496994018555
Backtrace time: 0.0007462501525878906
Total time: 3.5696959495544434
Forward computations: 157788
experiment_name: Task 2: self-loop 0.4
num_states: 116
num_arcs: 230
total_S: 88
total_D: 1
total_I: 919
total_N: 237
WER: 4.253164556962025
total_time_sec: 109.00130319595337
avg_time_sec: 2.2708604832490287
total_decode_time_sec: 108.9753360748291
avg_decode_time_sec: 2.2703195015589395
total_backtrace_time_sec: 0.025967121124267578
avg_backtrace_time_sec: 0.0005409816900889078
total_forward_computations: 4588254
avg_forward_computations: 95588.625
empty_hypothesis_count: 0
pruning_threshold: None
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: False
use_silence: False

######################################################################
Task 2: + silence
######################################################################

============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: a a the the the the of peck of peppers peppers pickled piper of peck of a a
S, D, I: 2 0 15
Decode time: 2.3976993560791016
Backtrace time: 0.0005567073822021484
Total time: 2.3982560634613037
Forward computations: 105448
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: a a the the of peck of a a
S, D, I: 1 0 6
Decode time: 1.751002311706543
Backtrace time: 0.00048232078552246094
Total time: 1.7514846324920654
Forward computations: 76308
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 1.7240819931030273
Backtrace time: 0.0004830360412597656
Total time: 1.724565029144287
Forward computations: 76308
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 1.546687126159668
Backtrace time: 0.00045108795166015625
Total time: 1.5471382141113281
Forward computations: 68248
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: a a the the of peck of the the of peck of a a
S, D, I: 1 0 11
Decode time: 1.815680980682373
Backtrace time: 0.0004837512969970703
Total time: 1.8161647319793701
Forward computations: 79098
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: a a of peck of the the peppers picked wheres picked peter piper wheres a a
S, D, I: 1 0 13
Decode time: 1.819056749343872
Backtrace time: 0.0004725456237792969
Total time: 1.8195292949676514
Forward computations: 79098
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 2.763646364212036
Backtrace time: 0.0005645751953125
Total time: 2.7642109394073486
Forward computations: 118778
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 1.8690929412841797
Backtrace time: 0.0004875659942626953
Total time: 1.8695805072784424
Forward computations: 81578
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: a a the the peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 9
Decode time: 3.26090931892395
Backtrace time: 0.0006167888641357422
Total time: 3.261526107788086
Forward computations: 142338
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 2.418588161468506
Backtrace time: 0.0005555152893066406
Total time: 2.4191436767578125
Forward computations: 100178
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 2.2301881313323975
Backtrace time: 0.0005273818969726562
Total time: 2.23071551322937
Forward computations: 97388
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: a a a a of peck of the the of peck of a a of peck of a a
S, D, I: 2 0 14
Decode time: 2.9594228267669678
Backtrace time: 0.0006227493286132812
Total time: 2.960045576095581
Forward computations: 129318
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: a a the the of peck of the the of peck of the the of peck of a a
S, D, I: 2 0 14
Decode time: 2.4121878147125244
Backtrace time: 0.000579833984375
Total time: 2.4127676486968994
Forward computations: 102658
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a the the the the of peck of peter piper wheres of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.7765095233917236
Backtrace time: 0.0005624294281005859
Total time: 2.777071952819824
Forward computations: 118778
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 2.7386159896850586
Backtrace time: 0.0005352497100830078
Total time: 2.7391512393951416
Forward computations: 115988
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peter piper wheres of peck of the the a a
S, D, I: 2 0 8
Decode time: 1.7962629795074463
Backtrace time: 0.00048613548278808594
Total time: 1.7967491149902344
Forward computations: 79098
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 20
Decode time: 2.3207993507385254
Backtrace time: 0.0005488395690917969
Total time: 2.321348190307617
Forward computations: 102658
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: a a a a of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 18
Decode time: 2.8518548011779785
Backtrace time: 0.0005877017974853516
Total time: 2.852442502975464
Forward computations: 118778
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 2.1626572608947754
Backtrace time: 0.0005609989166259766
Total time: 2.1632182598114014
Forward computations: 89638
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: a a the the peter piper wheres the the the the of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.5528664588928223
Backtrace time: 0.000560760498046875
Total time: 2.553427219390869
Forward computations: 110718
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: a a peter piper wheres the the of peck of a a a a
S, D, I: 0 0 11
Decode time: 1.985496997833252
Backtrace time: 0.0005435943603515625
Total time: 1.9860405921936035
Forward computations: 86848
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of a a the the peppers picked wheres picked peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.9610657691955566
Backtrace time: 0.0005939006805419922
Total time: 2.9616596698760986
Forward computations: 129318
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of of peck of a a peppers the wheres pickled peter a a a a
S, D, I: 2 0 17
Decode time: 3.278702974319458
Backtrace time: 0.0006494522094726562
Total time: 3.2793524265289307
Forward computations: 142338
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: a a the the peter piper wheres the the of peck of a a a a a a
S, D, I: 1 0 13
Decode time: 3.0306005477905273
Backtrace time: 0.0005803108215332031
Total time: 3.0311808586120605
Forward computations: 126528

============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: a a peter piper wheres of peck of a a peppers peppers pickled piper a a a a
S, D, I: 2 0 13
Decode time: 3.2368011474609375
Backtrace time: 0.0006256103515625
Total time: 3.2374267578125
Forward computations: 139858
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: a a peter piper wheres peppers the wheres pickled peter peppers peppers pickled piper a a
S, D, I: 0 0 13
Decode time: 2.441105842590332
Backtrace time: 0.0005781650543212891
Total time: 2.4416840076446533
Forward computations: 105448
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of the the peppers picked wheres picked a a a a
S, D, I: 2 0 14
Decode time: 2.8570547103881836
Backtrace time: 0.0005929470062255859
Total time: 2.857647657394409
Forward computations: 126528
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: a a peter piper wheres of peck of of peck of the the the the a a
S, D, I: 2 0 12
Decode time: 2.6397929191589355
Backtrace time: 0.0005452632904052734
Total time: 2.640338182449341
Forward computations: 113198
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: a a peter piper wheres of peck of a a a a
S, D, I: 2 0 9
Decode time: 2.2526981830596924
Backtrace time: 0.0005066394805908203
Total time: 2.253204822540283
Forward computations: 97388
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: a a peter piper wheres of peck of a a peppers peter peppers pickled piper peppers peppers the wheres pickled peter a a a a
S, D, I: 2 0 18
Decode time: 3.7598135471343994
Backtrace time: 0.0006773471832275391
Total time: 3.760490894317627
Forward computations: 163728
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper the the of peck of the the the the peppers picked wheres picked of peck of the the peter piper wheres a a
S, D, I: 4 0 28
Decode time: 3.8488025665283203
Backtrace time: 0.0007088184356689453
Total time: 3.8495113849639893
Forward computations: 166208
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked of peck of peter piper wheres the the peppers peppers pickled piper a a a a
S, D, I: 2 1 20
Decode time: 4.4240403175354
Backtrace time: 0.0007483959197998047
Total time: 4.4247887134552
Forward computations: 190078
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of a a peppers picked wheres picked a a a a a a peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 1 26
Decode time: 5.410681486129761
Backtrace time: 0.0008456707000732422
Total time: 5.411527156829834
Forward computations: 226968
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: a a peppers peppers pickled piper the the of peck of a a a a the the peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 0 22
Decode time: 4.222472190856934
Backtrace time: 0.0007150173187255859
Total time: 4.223187208175659
Forward computations: 182018
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the a a the the peter piper wheres of peck of peter piper wheres a a
S, D, I: 3 0 23
Decode time: 4.001405954360962
Backtrace time: 0.000732421875
Total time: 4.002138376235962
Forward computations: 174268
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 5.262089490890503
Backtrace time: 0.0008165836334228516
Total time: 5.262906074523926
Forward computations: 226968
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the of peck of peppers peppers pickled piper a a a a a a
S, D, I: 3 0 14
Decode time: 3.881791830062866
Backtrace time: 0.0006890296936035156
Total time: 3.8824808597564697
Forward computations: 168998
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: a a the the the the of peck of a a the the of peck of a a peppers peppers pickled piper peter piper wheres a a
S, D, I: 3 0 20
Decode time: 3.6250710487365723
Backtrace time: 0.0006663799285888672
Total time: 3.625737428665161
Forward computations: 155668
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: a a the the of peck of a a a a of peck of a a peter piper wheres peppers peppers pickled piper a a a a of peck of peppers picked wheres picked a a
S, D, I: 3 0 24
Decode time: 4.733012437820435
Backtrace time: 0.0008184909820556641
Total time: 4.73383092880249
Forward computations: 203408
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 3.0195608139038086
Backtrace time: 0.0005881786346435547
Total time: 3.020148992538452
Forward computations: 129318
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 4.801141262054443
Backtrace time: 0.0007677078247070312
Total time: 4.80190896987915
Forward computations: 203408
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of the the of peck of the the of peck of a a a a
S, D, I: 2 0 19
Decode time: 4.86200213432312
Backtrace time: 0.0007679462432861328
Total time: 4.862770080566406
Forward computations: 208678
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 5.012830972671509
Backtrace time: 0.0008165836334228516
Total time: 5.013647556304932
Forward computations: 213948
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 6.222620964050293
Backtrace time: 0.0008835792541503906
Total time: 6.223504543304443
Forward computations: 253628
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 4.467790603637695
Backtrace time: 0.00072479248046875
Total time: 4.468515396118164
Forward computations: 187288

============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 4.40380334854126
Backtrace time: 0.0007402896881103516
Total time: 4.40454363822937
Forward computations: 190078
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 4.717184066772461
Backtrace time: 0.0007536411285400391
Total time: 4.717937707901001
Forward computations: 203408
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a peppers peppers pickled piper a a
S, D, I: 0 0 31
Decode time: 5.274071216583252
Backtrace time: 0.0008409023284912109
Total time: 5.274912118911743
Forward computations: 232238
experiment_name: Task 2: + silence
num_states: 176
num_arcs: 350
total_S: 99
total_D: 2
total_I: 761
total_N: 237
WER: 3.6371308016877637
total_time_sec: 156.83155941963196
avg_time_sec: 3.267324154575666
total_decode_time_sec: 156.80131578445435
avg_decode_time_sec: 3.2666940788427987
total_backtrace_time_sec: 0.030243635177612305
avg_backtrace_time_sec: 0.000630075732866923
total_forward_computations: 6740154
avg_forward_computations: 140419.875
empty_hypothesis_count: 0
pruning_threshold: None
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: False
use_silence: True

In [14]:
task3_experiments = [
    {"name": "Task 3: no pruning", "pruning_threshold": None},
    {"name": "Task 3: pruning 50", "pruning_threshold": 50},
    {"name": "Task 3: pruning 100", "pruning_threshold": 100},
    {"name": "Task 3: pruning 200", "pruning_threshold": 200},
    {"name": "Task 3: pruning 500", "pruning_threshold": 500},
]

task3_summaries = []

for exp in task3_experiments:
    print("\n" + "#" * 70)
    print(exp["name"])
    print("#" * 70)

    results, summary = evaluate_dataset(
        audio_to_reference,
        continue_prob=0.1,
        self_loop_prob=0.4,
        use_unigram=False,
        use_silence=True,
        pruning_threshold=exp["pruning_threshold"],
        unigram_probs=None,
        experiment_name=exp["name"]
    )

    task3_summaries.append(summary)

    for k, v in summary.items():
        print(f"{k}: {v}")

######################################################################
Task 3: no pruning
######################################################################
============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: a a the the the the of peck of peppers peppers pickled piper of peck of a a
S, D, I: 2 0 15
Decode time: 2.459665298461914
Backtrace time: 0.0005469322204589844
Total time: 2.460212230682373
Forward computations: 105448
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: a a the the of peck of a a
S, D, I: 1 0 6
Decode time: 1.7204513549804688
Backtrace time: 0.0004677772521972656
Total time: 1.720919132232666
Forward computations: 76308
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 1.7126917839050293
Backtrace time: 0.0004730224609375
Total time: 1.7131648063659668
Forward computations: 76308
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 1.590635061264038
Backtrace time: 0.0004630088806152344
Total time: 1.5910980701446533
Forward computations: 68248
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: a a the the of peck of the the of peck of a a
S, D, I: 1 0 11
Decode time: 1.8073313236236572
Backtrace time: 0.00048828125
Total time: 1.8078196048736572
Forward computations: 79098
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: a a of peck of the the peppers picked wheres picked peter piper wheres a a
S, D, I: 1 0 13
Decode time: 1.8112201690673828
Backtrace time: 0.0005161762237548828
Total time: 1.8117363452911377
Forward computations: 79098
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 2.749946117401123
Backtrace time: 0.0005669593811035156
Total time: 2.7505130767822266
Forward computations: 118778
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 1.913381576538086
Backtrace time: 0.0005092620849609375
Total time: 1.9138908386230469
Forward computations: 81578
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: a a the the peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 9
Decode time: 3.265376329421997
Backtrace time: 0.0006036758422851562
Total time: 3.2659800052642822
Forward computations: 142338
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 2.338683605194092
Backtrace time: 0.0005407333374023438
Total time: 2.339224338531494
Forward computations: 100178
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 2.2966408729553223
Backtrace time: 0.0005247592926025391
Total time: 2.297165632247925
Forward computations: 97388
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: a a a a of peck of the the of peck of a a of peck of a a
S, D, I: 2 0 14
Decode time: 3.024284839630127
Backtrace time: 0.0006022453308105469
Total time: 3.0248870849609375
Forward computations: 129318
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: a a the the of peck of the the of peck of the the of peck of a a
S, D, I: 2 0 14
Decode time: 2.3654210567474365
Backtrace time: 0.0005540847778320312
Total time: 2.3659751415252686
Forward computations: 102658
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a the the the the of peck of peter piper wheres of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 3.1424355506896973
Backtrace time: 0.0005712509155273438
Total time: 3.1430068016052246
Forward computations: 118778
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 2.7112679481506348
Backtrace time: 0.0005428791046142578
Total time: 2.711810827255249
Forward computations: 115988
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peter piper wheres of peck of the the a a
S, D, I: 2 0 8
Decode time: 1.8404200077056885
Backtrace time: 0.00047135353088378906
Total time: 1.8408913612365723
Forward computations: 79098
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 20
Decode time: 2.39176869392395
Backtrace time: 0.0005512237548828125
Total time: 2.392319917678833
Forward computations: 102658
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: a a a a of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 18
Decode time: 2.754580020904541
Backtrace time: 0.0005843639373779297
Total time: 2.755164384841919
Forward computations: 118778
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 2.0566635131835938
Backtrace time: 0.0005238056182861328
Total time: 2.05718731880188
Forward computations: 89638
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: a a the the peter piper wheres the the the the of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.57804536819458
Backtrace time: 0.0005681514739990234
Total time: 2.578613519668579
Forward computations: 110718
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: a a peter piper wheres the the of peck of a a a a
S, D, I: 0 0 11
Decode time: 2.029707908630371
Backtrace time: 0.0005738735198974609
Total time: 2.0302817821502686
Forward computations: 86848
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of a a the the peppers picked wheres picked peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.9977970123291016
Backtrace time: 0.000591278076171875
Total time: 2.9983882904052734
Forward computations: 129318
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of of peck of a a peppers the wheres pickled peter a a a a
S, D, I: 2 0 17
Decode time: 3.2902278900146484
Backtrace time: 0.0006120204925537109
Total time: 3.290839910507202
Forward computations: 142338

============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: a a the the peter piper wheres the the of peck of a a a a a a
S, D, I: 1 0 13
Decode time: 2.8741228580474854
Backtrace time: 0.0006089210510253906
Total time: 2.8747317790985107
Forward computations: 126528
============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: a a peter piper wheres of peck of a a peppers peppers pickled piper a a a a
S, D, I: 2 0 13
Decode time: 3.3496310710906982
Backtrace time: 0.0006165504455566406
Total time: 3.350247621536255
Forward computations: 139858
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: a a peter piper wheres peppers the wheres pickled peter peppers peppers pickled piper a a
S, D, I: 0 0 13
Decode time: 2.5372066497802734
Backtrace time: 0.0005393028259277344
Total time: 2.537745952606201
Forward computations: 105448
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of the the peppers picked wheres picked a a a a
S, D, I: 2 0 14
Decode time: 3.461575984954834
Backtrace time: 0.0006015300750732422
Total time: 3.4621775150299072
Forward computations: 126528
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: a a peter piper wheres of peck of of peck of the the the the a a
S, D, I: 2 0 12
Decode time: 2.5939788818359375
Backtrace time: 0.0005710124969482422
Total time: 2.5945498943328857
Forward computations: 113198
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: a a peter piper wheres of peck of a a a a
S, D, I: 2 0 9
Decode time: 2.2228424549102783
Backtrace time: 0.0005211830139160156
Total time: 2.2233636379241943
Forward computations: 97388
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: a a peter piper wheres of peck of a a peppers peter peppers pickled piper peppers peppers the wheres pickled peter a a a a
S, D, I: 2 0 18
Decode time: 3.9216721057891846
Backtrace time: 0.0007038116455078125
Total time: 3.9223759174346924
Forward computations: 163728
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper the the of peck of the the the the peppers picked wheres picked of peck of the the peter piper wheres a a
S, D, I: 4 0 28
Decode time: 4.180622577667236
Backtrace time: 0.0007374286651611328
Total time: 4.1813600063323975
Forward computations: 166208
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked of peck of peter piper wheres the the peppers peppers pickled piper a a a a
S, D, I: 2 1 20
Decode time: 4.343444347381592
Backtrace time: 0.0007283687591552734
Total time: 4.344172716140747
Forward computations: 190078
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of a a peppers picked wheres picked a a a a a a peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 1 26
Decode time: 5.153025388717651
Backtrace time: 0.0008311271667480469
Total time: 5.153856515884399
Forward computations: 226968
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: a a peppers peppers pickled piper the the of peck of a a a a the the peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 0 22
Decode time: 4.167138576507568
Backtrace time: 0.0007295608520507812
Total time: 4.167868137359619
Forward computations: 182018
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the a a the the peter piper wheres of peck of peter piper wheres a a
S, D, I: 3 0 23
Decode time: 4.303104400634766
Backtrace time: 0.001186370849609375
Total time: 4.304290771484375
Forward computations: 174268
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 5.527455568313599
Backtrace time: 0.0008223056793212891
Total time: 5.52827787399292
Forward computations: 226968
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the of peck of peppers peppers pickled piper a a a a a a
S, D, I: 3 0 14
Decode time: 3.8611319065093994
Backtrace time: 0.0007033348083496094
Total time: 3.861835241317749
Forward computations: 168998
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: a a the the the the of peck of a a the the of peck of a a peppers peppers pickled piper peter piper wheres a a
S, D, I: 3 0 20
Decode time: 3.644455671310425
Backtrace time: 0.0006692409515380859
Total time: 3.645124912261963
Forward computations: 155668
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: a a the the of peck of a a a a of peck of a a peter piper wheres peppers peppers pickled piper a a a a of peck of peppers picked wheres picked a a
S, D, I: 3 0 24
Decode time: 4.770796537399292
Backtrace time: 0.0009913444519042969
Total time: 4.771787881851196
Forward computations: 203408
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 3.0985898971557617
Backtrace time: 0.0005831718444824219
Total time: 3.099173069000244
Forward computations: 129318
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 4.948245048522949
Backtrace time: 0.0008146762847900391
Total time: 4.949059724807739
Forward computations: 203408
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of the the of peck of the the of peck of a a a a
S, D, I: 2 0 19
Decode time: 4.77847695350647
Backtrace time: 0.0007927417755126953
Total time: 4.779269695281982
Forward computations: 208678
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 5.015165328979492
Backtrace time: 0.0007913112640380859
Total time: 5.01595664024353
Forward computations: 213948
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 5.848130941390991
Backtrace time: 0.0008633136749267578
Total time: 5.848994255065918
Forward computations: 253628

============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 4.531806468963623
Backtrace time: 0.0007297992706298828
Total time: 4.532536268234253
Forward computations: 187288
============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 4.285018682479858
Backtrace time: 0.0007402896881103516
Total time: 4.285758972167969
Forward computations: 190078
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 4.593876123428345
Backtrace time: 0.0007674694061279297
Total time: 4.594643592834473
Forward computations: 203408
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a peppers peppers pickled piper a a
S, D, I: 0 0 31
Decode time: 5.5035083293914795
Backtrace time: 0.0008447170257568359
Total time: 5.504353046417236
Forward computations: 232238
experiment_name: Task 3: no pruning
num_states: 176
num_arcs: 350
total_S: 99
total_D: 2
total_I: 761
total_N: 237
WER: 3.6371308016877637
total_time_sec: 158.394602060318
avg_time_sec: 3.2998875429232917
total_decode_time_sec: 158.36366605758667
avg_decode_time_sec: 3.299243042866389
total_backtrace_time_sec: 0.030936002731323242
avg_backtrace_time_sec: 0.0006445000569025675
total_forward_computations: 6740154
avg_forward_computations: 140419.875
empty_hypothesis_count: 0
pruning_threshold: None
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: False
use_silence: True

######################################################################
Task 3: pruning 50
######################################################################
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis:
S, D, I: 0 3 0
Decode time: 1.1312336921691895
Backtrace time: 0.0002982616424560547
Total time: 1.1315319538116455
Forward computations: 46176
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis:
S, D, I: 0 3 0
Decode time: 0.669257640838623
Backtrace time: 0.000331878662109375
Total time: 0.6695895195007324
Forward computations: 27324
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 0.9493229389190674
Backtrace time: 0.0004923343658447266
Total time: 0.9498152732849121
Forward computations: 37520
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 0.6877861022949219
Backtrace time: 0.0004668235778808594
Total time: 0.6882529258728027
Forward computations: 27752
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis:
S, D, I: 0 3 0
Decode time: 0.8023786544799805
Backtrace time: 0.0003085136413574219
Total time: 0.8026871681213379
Forward computations: 32982
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis:
S, D, I: 0 3 0
Decode time: 0.9446635246276855
Backtrace time: 0.0003266334533691406
Total time: 0.9449901580810547
Forward computations: 36400
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 1.3417987823486328
Backtrace time: 0.0006122589111328125
Total time: 1.3424110412597656
Forward computations: 50060
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 0.8444314002990723
Backtrace time: 0.0004887580871582031
Total time: 0.8449201583862305
Forward computations: 34164
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis:
S, D, I: 0 3 0
Decode time: 1.4607653617858887
Backtrace time: 0.00030732154846191406
Total time: 1.4610726833343506
Forward computations: 57728
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 1.4084012508392334
Backtrace time: 0.0007908344268798828
Total time: 1.4091920852661133
Forward computations: 58732
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 1.1058681011199951
Backtrace time: 0.00051116943359375
Total time: 1.1063792705535889
Forward computations: 42610
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.26906418800354
Backtrace time: 0.00029468536376953125
Total time: 1.2693588733673096
Forward computations: 52924
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.143439769744873
Backtrace time: 0.0003056526184082031
Total time: 1.1437454223632812
Forward computations: 46738
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.2701828479766846
Backtrace time: 0.00035691261291503906
Total time: 1.2705397605895996
Forward computations: 52714
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 1.2324504852294922
Backtrace time: 0.0005369186401367188
Total time: 1.232987403869629
Forward computations: 45284
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis:
S, D, I: 0 4 0
Decode time: 0.9026033878326416
Backtrace time: 0.0003151893615722656
Total time: 0.9029185771942139
Forward computations: 35660

No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis:
S, D, I: 0 4 0
Decode time: 1.1253960132598877
Backtrace time: 0.0002994537353515625
Total time: 1.1256954669952393
Forward computations: 46340
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis:
S, D, I: 0 4 0
Decode time: 1.2074017524719238
Backtrace time: 0.00034356117248535156
Total time: 1.2077453136444092
Forward computations: 50884
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 1.2743046283721924
Backtrace time: 0.0005311965942382812
Total time: 1.2748358249664307
Forward computations: 51120
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis:
S, D, I: 0 4 0
Decode time: 1.2364423274993896
Backtrace time: 0.0002963542938232422
Total time: 1.236738681793213
Forward computations: 49858
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis:
S, D, I: 0 3 0
Decode time: 0.7838954925537109
Backtrace time: 0.0002963542938232422
Total time: 0.7841918468475342
Forward computations: 31850
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis:
S, D, I: 0 6 0
Decode time: 1.427262783050537
Backtrace time: 0.0003299713134765625
Total time: 1.4275927543640137
Forward computations: 57962
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.4125409126281738
Backtrace time: 0.0003147125244140625
Total time: 1.412855625152588
Forward computations: 58134
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.419874906539917
Backtrace time: 0.00034809112548828125
Total time: 1.4202229976654053
Forward computations: 54412
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.3331024646759033
Backtrace time: 0.0003228187561035156
Total time: 1.3334252834320068
Forward computations: 53388
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis:
S, D, I: 0 3 0
Decode time: 0.9098708629608154
Backtrace time: 0.0003139972686767578
Total time: 0.9101848602294922
Forward computations: 36072
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of the the peppers picked wheres picked a a a a
S, D, I: 2 0 14
Decode time: 1.21108078956604
Backtrace time: 0.0005965232849121094
Total time: 1.2116773128509521
Forward computations: 49822
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.1130461692810059
Backtrace time: 0.0002980232238769531
Total time: 1.1133441925048828
Forward computations: 45304
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis:
S, D, I: 0 3 0
Decode time: 0.9690303802490234
Backtrace time: 0.0003197193145751953
Total time: 0.9693500995635986
Forward computations: 39892
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis:
S, D, I: 0 7 0
Decode time: 1.7168231010437012
Backtrace time: 0.00033020973205566406
Total time: 1.7171533107757568
Forward computations: 71200
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis:
S, D, I: 0 8 0
Decode time: 1.716895580291748
Backtrace time: 0.00030732154846191406
Total time: 1.71720290184021
Forward computations: 70034
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis:
S, D, I: 0 9 0
Decode time: 1.9440078735351562
Backtrace time: 0.00030303001403808594
Total time: 1.9443109035491943
Forward computations: 81788
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis:
S, D, I: 0 7 0
Decode time: 2.1268885135650635
Backtrace time: 0.0003266334533691406
Total time: 2.1272151470184326
Forward computations: 86022
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis:
S, D, I: 0 6 0
Decode time: 1.7118399143218994
Backtrace time: 0.0003018379211425781
Total time: 1.712141752243042
Forward computations: 71338
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.7946741580963135
Backtrace time: 0.0003077983856201172
Total time: 1.7949819564819336
Forward computations: 73936
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 1.9596424102783203
Backtrace time: 0.0008287429809570312
Total time: 1.9604711532592773
Forward computations: 79356
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.4339854717254639
Backtrace time: 0.00029921531677246094
Total time: 1.4342846870422363
Forward computations: 58750

No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis:
S, D, I: 0 7 0
Decode time: 1.663578748703003
Backtrace time: 0.00031638145446777344
Total time: 1.6638951301574707
Forward computations: 66376
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis:
S, D, I: 0 12 0
Decode time: 2.276033878326416
Backtrace time: 0.00042819976806640625
Total time: 2.2764620780944824
Forward computations: 93216
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 1.331096887588501
Backtrace time: 0.0005695819854736328
Total time: 1.3316664695739746
Forward computations: 53346
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 1.9414160251617432
Backtrace time: 0.0007565021514892578
Total time: 1.9421725273132324
Forward computations: 81042
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of the the of peck of the the of peck of a a a a
S, D, I: 2 0 19
Decode time: 1.8212828636169434
Backtrace time: 0.0007865428924560547
Total time: 1.8220694065093994
Forward computations: 75522
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 2.3860104084014893
Backtrace time: 0.0008370876312255859
Total time: 2.386847496032715
Forward computations: 99376
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 2.5525784492492676
Backtrace time: 0.0008780956268310547
Total time: 2.5534565448760986
Forward computations: 103756
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 1.8190679550170898
Backtrace time: 0.0007703304290771484
Total time: 1.819838285446167
Forward computations: 72662
============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 1.9685606956481934
Backtrace time: 0.0007212162017822266
Total time: 1.9692819118499756
Forward computations: 81128
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 1.7357618808746338
Backtrace time: 0.000766754150390625
Total time: 1.7365286350250244
Forward computations: 68692
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a peppers peppers pickled piper a a
S, D, I: 0 0 31
Decode time: 2.1788923740386963
Backtrace time: 0.0008831024169921875
Total time: 2.1797754764556885
Forward computations: 89594
experiment_name: Task 3: pruning 50
num_states: 176
num_arcs: 350
total_S: 42
total_D: 147
total_I: 305
total_N: 237
WER: 2.0843881856540083
total_time_sec: 68.68800830841064
avg_time_sec: 1.4310001730918884
total_decode_time_sec: 68.66593480110168
avg_decode_time_sec: 1.430540308356285
total_backtrace_time_sec: 0.02207350730895996
avg_backtrace_time_sec: 0.0004598647356033325
total_forward_computations: 2786940
avg_forward_computations: 58061.25
empty_hypothesis_count: 29
pruning_threshold: 50
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: False
use_silence: True

######################################################################
Task 3: pruning 100
######################################################################
============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: a a the the the the of peck of peppers peppers pickled piper of peck of a a
S, D, I: 2 0 15
Decode time: 1.846330165863037
Backtrace time: 0.0005512237548828125
Total time: 1.84688138961792
Forward computations: 75248
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: a a the the of peck of a a
S, D, I: 1 0 6
Decode time: 1.2220659255981445
Backtrace time: 0.0004756450653076172
Total time: 1.2225415706634521
Forward computations: 50560
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 1.4574882984161377
Backtrace time: 0.0005168914794921875
Total time: 1.4580051898956299
Forward computations: 61200
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 1.2322258949279785
Backtrace time: 0.0004520416259765625
Total time: 1.232677936553955
Forward computations: 50442
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: a a the the of peck of the the of peck of a a
S, D, I: 1 0 11
Decode time: 1.3432464599609375
Backtrace time: 0.00047087669372558594
Total time: 1.343717336654663
Forward computations: 55742
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: a a of peck of the the peppers picked wheres picked peter piper wheres a a
S, D, I: 1 0 13
Decode time: 1.6341793537139893
Backtrace time: 0.0005223751068115234
Total time: 1.6347017288208008
Forward computations: 61500
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 2.206604480743408
Backtrace time: 0.0005700588226318359
Total time: 2.20717453956604
Forward computations: 81044
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 1.3636846542358398
Backtrace time: 0.0004968643188476562
Total time: 1.3641815185546875
Forward computations: 57866
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: a a the the peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 9
Decode time: 2.252448320388794
Backtrace time: 0.0006308555603027344
Total time: 2.2530791759490967
Forward computations: 92790
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 2.0667850971221924
Backtrace time: 0.0006160736083984375
Total time: 2.067401170730591
Forward computations: 86390

============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 1.7156298160552979
Backtrace time: 0.0005319118499755859
Total time: 1.7161617279052734
Forward computations: 71334
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: a a a a of peck of the the of peck of a a of peck of a a
S, D, I: 2 0 14
Decode time: 2.438964605331421
Backtrace time: 0.0013880729675292969
Total time: 2.44035267829895
Forward computations: 89052
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: a a the the of peck of the the of peck of the the of peck of a a
S, D, I: 2 0 14
Decode time: 1.8588027954101562
Backtrace time: 0.0005321502685546875
Total time: 1.859334945678711
Forward computations: 76860
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a the the the the of peck of peter piper wheres of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.108286142349243
Backtrace time: 0.0005886554718017578
Total time: 2.108874797821045
Forward computations: 85408
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 1.8279542922973633
Backtrace time: 0.0005552768707275391
Total time: 1.8285095691680908
Forward computations: 76602
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peter piper wheres of peck of the the a a
S, D, I: 2 0 8
Decode time: 1.4338865280151367
Backtrace time: 0.00048828125
Total time: 1.4343748092651367
Forward computations: 59808
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 20
Decode time: 1.814511775970459
Backtrace time: 0.0005435943603515625
Total time: 1.8150553703308105
Forward computations: 76920
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: a a a a of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 18
Decode time: 2.157721996307373
Backtrace time: 0.0005671977996826172
Total time: 2.1582891941070557
Forward computations: 85598
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 1.813081979751587
Backtrace time: 0.0005145072937011719
Total time: 1.813596487045288
Forward computations: 77432
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: a a the the peter piper wheres the the the the of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.040729522705078
Backtrace time: 0.0005578994750976562
Total time: 2.041287422180176
Forward computations: 83970
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: a a peter piper wheres the the of peck of a a a a
S, D, I: 0 0 11
Decode time: 1.4593744277954102
Backtrace time: 0.0005064010620117188
Total time: 1.4598808288574219
Forward computations: 59054
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of a a the the peppers picked wheres picked peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.321021795272827
Backtrace time: 0.000614166259765625
Total time: 2.3216359615325928
Forward computations: 98988
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of of peck of a a peppers the wheres pickled peter a a a a
S, D, I: 2 0 17
Decode time: 2.470658540725708
Backtrace time: 0.0006351470947265625
Total time: 2.4712936878204346
Forward computations: 102396
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: a a the the peter piper wheres the the of peck of a a a a a a
S, D, I: 1 0 13
Decode time: 2.4521405696868896
Backtrace time: 0.0006227493286132812
Total time: 2.452763319015503
Forward computations: 92408
============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: a a peter piper wheres of peck of a a peppers peppers pickled piper a a a a
S, D, I: 2 0 13
Decode time: 2.299412965774536
Backtrace time: 0.0006351470947265625
Total time: 2.3000481128692627
Forward computations: 96408
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: a a peter piper wheres peppers the wheres pickled peter peppers peppers pickled piper a a
S, D, I: 0 0 13
Decode time: 1.695314884185791
Backtrace time: 0.0005471706390380859
Total time: 1.695862054824829
Forward computations: 66392
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of the the peppers picked wheres picked a a a a
S, D, I: 2 0 14
Decode time: 2.1113762855529785
Backtrace time: 0.0006573200225830078
Total time: 2.1120336055755615
Forward computations: 86710
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: a a peter piper wheres of peck of of peck of the the the the a a
S, D, I: 2 0 12
Decode time: 1.9905641078948975
Backtrace time: 0.0005710124969482422
Total time: 1.9911351203918457
Forward computations: 81146
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: a a peter piper wheres of peck of a a a a
S, D, I: 2 0 9
Decode time: 1.7217516899108887
Backtrace time: 0.0005047321319580078
Total time: 1.7222564220428467
Forward computations: 68474
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: a a peter piper wheres of peck of a a peppers peter peppers pickled piper peppers peppers the wheres pickled peter a a a a
S, D, I: 2 0 18
Decode time: 2.8940541744232178
Backtrace time: 0.0006797313690185547
Total time: 2.8947339057922363
Forward computations: 121988
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper the the of peck of the the the the peppers picked wheres picked of peck of the the peter piper wheres a a
S, D, I: 4 0 28
Decode time: 2.8906807899475098
Backtrace time: 0.0007081031799316406
Total time: 2.8913888931274414
Forward computations: 121558
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked of peck of peter piper wheres the the peppers peppers pickled piper a a a a
S, D, I: 2 1 20
Decode time: 3.2869718074798584
Backtrace time: 0.0007483959197998047
Total time: 3.287720203399658
Forward computations: 139200
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of a a peppers picked wheres picked a a a a a a peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 1 26
Decode time: 3.7433831691741943
Backtrace time: 0.0008521080017089844
Total time: 3.7442352771759033
Forward computations: 155144

============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: a a peppers peppers pickled piper the the of peck of a a a a the the peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 0 22
Decode time: 2.9508473873138428
Backtrace time: 0.0007185935974121094
Total time: 2.951565980911255
Forward computations: 122676
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the a a the the peter piper wheres of peck of peter piper wheres a a
S, D, I: 3 0 23
Decode time: 2.8706982135772705
Backtrace time: 0.0007014274597167969
Total time: 2.8713996410369873
Forward computations: 121234
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 3.5038182735443115
Backtrace time: 0.0008292198181152344
Total time: 3.5046474933624268
Forward computations: 143660
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the of peck of peppers peppers pickled piper a a a a a a
S, D, I: 3 0 14
Decode time: 2.5697383880615234
Backtrace time: 0.0006852149963378906
Total time: 2.5704236030578613
Forward computations: 105584
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: a a the the the the of peck of a a the the of peck of a a peppers peppers pickled piper peter piper wheres a a
S, D, I: 3 0 20
Decode time: 2.8558754920959473
Backtrace time: 0.0006666183471679688
Total time: 2.8565421104431152
Forward computations: 111600
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: a a the the of peck of a a a a of peck of a a peter piper wheres peppers peppers pickled piper a a a a of peck of peppers picked wheres picked a a
S, D, I: 3 0 24
Decode time: 3.770205497741699
Backtrace time: 0.0007789134979248047
Total time: 3.770984411239624
Forward computations: 158782
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 2.2241172790527344
Backtrace time: 0.0005850791931152344
Total time: 2.2247023582458496
Forward computations: 92614
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 3.3809735774993896
Backtrace time: 0.0007507801055908203
Total time: 3.3817243576049805
Forward computations: 143036
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of the the of peck of the the of peck of a a a a
S, D, I: 2 0 19
Decode time: 3.386080741882324
Backtrace time: 0.0007894039154052734
Total time: 3.3868701457977295
Forward computations: 138782
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 3.8904945850372314
Backtrace time: 0.0007994174957275391
Total time: 3.891294002532959
Forward computations: 160448
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 4.340498924255371
Backtrace time: 0.0009219646453857422
Total time: 4.341420888900757
Forward computations: 177534
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 3.109187364578247
Backtrace time: 0.0007197856903076172
Total time: 3.1099071502685547
Forward computations: 131172
============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 3.31192946434021
Backtrace time: 0.0007412433624267578
Total time: 3.3126707077026367
Forward computations: 136036
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 3.30102276802063
Backtrace time: 0.0007550716400146484
Total time: 3.3017778396606445
Forward computations: 126610
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a peppers peppers pickled piper a a
S, D, I: 0 0 31
Decode time: 3.980968952178955
Backtrace time: 0.0008590221405029297
Total time: 3.981827974319458
Forward computations: 166778
experiment_name: Task 3: pruning 100
num_states: 176
num_arcs: 350
total_S: 99
total_D: 2
total_I: 761
total_N: 237
WER: 3.6371308016877637
total_time_sec: 116.64894461631775
avg_time_sec: 2.4301863461732864
total_decode_time_sec: 116.61779022216797
avg_decode_time_sec: 2.429537296295166
total_backtrace_time_sec: 0.031154394149780273
avg_backtrace_time_sec: 0.0006490498781204224
total_forward_computations: 4782178
avg_forward_computations: 99628.70833333333
empty_hypothesis_count: 0
pruning_threshold: 100
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: False
use_silence: True

######################################################################
Task 3: pruning 200
######################################################################
============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: a a the the the the of peck of peppers peppers pickled piper of peck of a a
S, D, I: 2 0 15
Decode time: 2.3137972354888916
Backtrace time: 0.0005350112915039062
Total time: 2.3143322467803955
Forward computations: 96056
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: a a the the of peck of a a
S, D, I: 1 0 6
Decode time: 1.6202232837677002
Backtrace time: 0.0004794597625732422
Total time: 1.6207027435302734
Forward computations: 68882
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 1.8708319664001465
Backtrace time: 0.0004906654357910156
Total time: 1.8713226318359375
Forward computations: 74082
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 1.5597214698791504
Backtrace time: 0.00044155120849609375
Total time: 1.5601630210876465
Forward computations: 64588
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: a a the the of peck of the the of peck of a a
S, D, I: 1 0 11
Decode time: 1.769031286239624
Backtrace time: 0.0005335807800292969
Total time: 1.7695648670196533
Forward computations: 72192

============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: a a of peck of the the peppers picked wheres picked peter piper wheres a a
S, D, I: 1 0 13
Decode time: 1.866734504699707
Backtrace time: 0.00048422813415527344
Total time: 1.8672187328338623
Forward computations: 77096
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 2.559109687805176
Backtrace time: 0.0005645751953125
Total time: 2.5596742630004883
Forward computations: 106418
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 1.8519620895385742
Backtrace time: 0.0007643699645996094
Total time: 1.8527264595031738
Forward computations: 76272
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: a a the the peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 9
Decode time: 3.000767707824707
Backtrace time: 0.0010921955108642578
Total time: 3.0018599033355713
Forward computations: 123824
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 2.3824973106384277
Backtrace time: 0.0005478858947753906
Total time: 2.383045196533203
Forward computations: 98254
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 2.148738145828247
Backtrace time: 0.0005450248718261719
Total time: 2.1492831707000732
Forward computations: 91060
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: a a a a of peck of the the of peck of a a of peck of a a
S, D, I: 2 0 14
Decode time: 2.8698904514312744
Backtrace time: 0.0005965232849121094
Total time: 2.8704869747161865
Forward computations: 118030
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: a a the the of peck of the the of peck of the the of peck of a a
S, D, I: 2 0 14
Decode time: 2.361402750015259
Backtrace time: 0.0005600452423095703
Total time: 2.3619627952575684
Forward computations: 94896
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a the the the the of peck of peter piper wheres of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.5861358642578125
Backtrace time: 0.0005908012390136719
Total time: 2.586726665496826
Forward computations: 107510
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 2.4978549480438232
Backtrace time: 0.0005562305450439453
Total time: 2.498411178588867
Forward computations: 101654
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peter piper wheres of peck of the the a a
S, D, I: 2 0 8
Decode time: 1.7529332637786865
Backtrace time: 0.00048542022705078125
Total time: 1.7534186840057373
Forward computations: 74744
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 20
Decode time: 2.32997465133667
Backtrace time: 0.0005474090576171875
Total time: 2.330522060394287
Forward computations: 97950
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: a a a a of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 18
Decode time: 2.6643691062927246
Backtrace time: 0.00058746337890625
Total time: 2.664956569671631
Forward computations: 111866
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 2.1281368732452393
Backtrace time: 0.0005033016204833984
Total time: 2.1286401748657227
Forward computations: 89336
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: a a the the peter piper wheres the the the the of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.4871597290039062
Backtrace time: 0.0005917549133300781
Total time: 2.4877514839172363
Forward computations: 104648
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: a a peter piper wheres the the of peck of a a a a
S, D, I: 0 0 11
Decode time: 1.884718894958496
Backtrace time: 0.0005125999450683594
Total time: 1.8852314949035645
Forward computations: 78456
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of a a the the peppers picked wheres picked peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.9044926166534424
Backtrace time: 0.0006048679351806641
Total time: 2.905097484588623
Forward computations: 123170
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of of peck of a a peppers the wheres pickled peter a a a a
S, D, I: 2 0 17
Decode time: 3.156928777694702
Backtrace time: 0.0006556510925292969
Total time: 3.1575844287872314
Forward computations: 134242
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: a a the the peter piper wheres the the of peck of a a a a a a
S, D, I: 1 0 13
Decode time: 2.878204107284546
Backtrace time: 0.0005884170532226562
Total time: 2.8787925243377686
Forward computations: 119494
============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: a a peter piper wheres of peck of a a peppers peppers pickled piper a a a a
S, D, I: 2 0 13
Decode time: 3.1545357704162598
Backtrace time: 0.0006191730499267578
Total time: 3.1551549434661865
Forward computations: 131276
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: a a peter piper wheres peppers the wheres pickled peter peppers peppers pickled piper a a
S, D, I: 0 0 13
Decode time: 2.250253200531006
Backtrace time: 0.0005469322204589844
Total time: 2.250800132751465
Forward computations: 95206
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of the the peppers picked wheres picked a a a a
S, D, I: 2 0 14
Decode time: 2.718437671661377
Backtrace time: 0.0005929470062255859
Total time: 2.7190306186676025
Forward computations: 115292
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: a a peter piper wheres of peck of of peck of the the the the a a
S, D, I: 2 0 12
Decode time: 2.4951400756835938
Backtrace time: 0.0005578994750976562
Total time: 2.4956979751586914
Forward computations: 105612

============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: a a peter piper wheres of peck of a a a a
S, D, I: 2 0 9
Decode time: 2.1450908184051514
Backtrace time: 0.0005354881286621094
Total time: 2.1456263065338135
Forward computations: 87136
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: a a peter piper wheres of peck of a a peppers peter peppers pickled piper peppers peppers the wheres pickled peter a a a a
S, D, I: 2 0 18
Decode time: 3.617438554763794
Backtrace time: 0.0006632804870605469
Total time: 3.6181018352508545
Forward computations: 156014
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper the the of peck of the the the the peppers picked wheres picked of peck of the the peter piper wheres a a
S, D, I: 4 0 28
Decode time: 3.7897913455963135
Backtrace time: 0.0007317066192626953
Total time: 3.790523052215576
Forward computations: 158082
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked of peck of peter piper wheres the the peppers peppers pickled piper a a a a
S, D, I: 2 1 20
Decode time: 4.193150043487549
Backtrace time: 0.0007371902465820312
Total time: 4.193887233734131
Forward computations: 177732
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of a a peppers picked wheres picked a a a a a a peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 1 26
Decode time: 5.353782415390015
Backtrace time: 0.0008089542388916016
Total time: 5.354591369628906
Forward computations: 214278
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: a a peppers peppers pickled piper the the of peck of a a a a the the peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 0 22
Decode time: 4.052415132522583
Backtrace time: 0.0007331371307373047
Total time: 4.05314826965332
Forward computations: 170066
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the a a the the peter piper wheres of peck of peter piper wheres a a
S, D, I: 3 0 23
Decode time: 3.976936101913452
Backtrace time: 0.000713348388671875
Total time: 3.977649450302124
Forward computations: 164334
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 5.123021364212036
Backtrace time: 0.0008015632629394531
Total time: 5.123822927474976
Forward computations: 206772
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the of peck of peppers peppers pickled piper a a a a a a
S, D, I: 3 0 14
Decode time: 3.6301393508911133
Backtrace time: 0.0006740093231201172
Total time: 3.6308133602142334
Forward computations: 151582
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: a a the the the the of peck of a a the the of peck of a a peppers peppers pickled piper peter piper wheres a a
S, D, I: 3 0 20
Decode time: 3.563530683517456
Backtrace time: 0.0006728172302246094
Total time: 3.5642035007476807
Forward computations: 148780
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: a a the the of peck of a a a a of peck of a a peter piper wheres peppers peppers pickled piper a a a a of peck of peppers picked wheres picked a a
S, D, I: 3 0 24
Decode time: 4.838207960128784
Backtrace time: 0.0009598731994628906
Total time: 4.839167833328247
Forward computations: 195880
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 2.921598196029663
Backtrace time: 0.0005743503570556641
Total time: 2.9221725463867188
Forward computations: 123280
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 4.583111524581909
Backtrace time: 0.0007622241973876953
Total time: 4.583873748779297
Forward computations: 192568
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of the the of peck of the the of peck of a a a a
S, D, I: 2 0 19
Decode time: 4.658786296844482
Backtrace time: 0.0007731914520263672
Total time: 4.659559488296509
Forward computations: 194034
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 4.849880933761597
Backtrace time: 0.0007879734039306641
Total time: 4.850668907165527
Forward computations: 204734
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 5.833780288696289
Backtrace time: 0.0008792877197265625
Total time: 5.834659576416016
Forward computations: 243158
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 4.300800323486328
Backtrace time: 0.000728607177734375
Total time: 4.3015289306640625
Forward computations: 178258
============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 4.275585889816284
Backtrace time: 0.0007233619689941406
Total time: 4.276309251785278
Forward computations: 180562
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 4.509003400802612
Backtrace time: 0.0007462501525878906
Total time: 4.5097496509552
Forward computations: 184750
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a peppers peppers pickled piper a a
S, D, I: 0 0 31
Decode time: 5.2455034255981445
Backtrace time: 0.000835418701171875
Total time: 5.246338844299316
Forward computations: 222012
experiment_name: Task 3: pruning 200
num_states: 176
num_arcs: 350
total_S: 99
total_D: 2
total_I: 761
total_N: 237
WER: 3.6371308016877637
total_time_sec: 151.55655550956726
avg_time_sec: 3.1574282397826514
total_decode_time_sec: 151.52553749084473
avg_decode_time_sec: 3.156782031059265
total_backtrace_time_sec: 0.03101801872253418
avg_backtrace_time_sec: 0.0006462087233861288
total_forward_computations: 6306118
avg_forward_computations: 131377.45833333334
empty_hypothesis_count: 0
pruning_threshold: 200
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: False
use_silence: True

######################################################################
Task 3: pruning 500
######################################################################

============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: a a the the the the of peck of peppers peppers pickled piper of peck of a a
S, D, I: 2 0 15
Decode time: 2.4837899208068848
Backtrace time: 0.0005750656127929688
Total time: 2.4843649864196777
Forward computations: 105448
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: a a the the of peck of a a
S, D, I: 1 0 6
Decode time: 1.8035783767700195
Backtrace time: 0.0004627704620361328
Total time: 1.8040411472320557
Forward computations: 76308
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 1.8212053775787354
Backtrace time: 0.0004887580871582031
Total time: 1.8216941356658936
Forward computations: 76308
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 1.6021926403045654
Backtrace time: 0.0004630088806152344
Total time: 1.6026556491851807
Forward computations: 68248
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: a a the the of peck of the the of peck of a a
S, D, I: 1 0 11
Decode time: 1.891289472579956
Backtrace time: 0.0005064010620117188
Total time: 1.8917958736419678
Forward computations: 79098
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: a a of peck of the the peppers picked wheres picked peter piper wheres a a
S, D, I: 1 0 13
Decode time: 1.8687183856964111
Backtrace time: 0.0005078315734863281
Total time: 1.8692262172698975
Forward computations: 79098
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 2.7863028049468994
Backtrace time: 0.0005469322204589844
Total time: 2.7868497371673584
Forward computations: 118778
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 2.0098657608032227
Backtrace time: 0.0005390644073486328
Total time: 2.0104048252105713
Forward computations: 81578
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: a a the the peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 9
Decode time: 3.5498263835906982
Backtrace time: 0.0006434917449951172
Total time: 3.5504698753356934
Forward computations: 142338
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 2.3961563110351562
Backtrace time: 0.000537872314453125
Total time: 2.3966941833496094
Forward computations: 100178
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 2.295901298522949
Backtrace time: 0.0005388259887695312
Total time: 2.2964401245117188
Forward computations: 97388
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: a a a a of peck of the the of peck of a a of peck of a a
S, D, I: 2 0 14
Decode time: 3.392237901687622
Backtrace time: 0.0005960464477539062
Total time: 3.392833948135376
Forward computations: 129318
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: a a the the of peck of the the of peck of the the of peck of a a
S, D, I: 2 0 14
Decode time: 2.7037160396575928
Backtrace time: 0.0005686283111572266
Total time: 2.70428466796875
Forward computations: 102658
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a the the the the of peck of peter piper wheres of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 3.1661975383758545
Backtrace time: 0.0005700588226318359
Total time: 3.1667675971984863
Forward computations: 118778
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 2.7931442260742188
Backtrace time: 0.0005669593811035156
Total time: 2.7937111854553223
Forward computations: 115988
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peter piper wheres of peck of the the a a
S, D, I: 2 0 8
Decode time: 1.9169175624847412
Backtrace time: 0.0004940032958984375
Total time: 1.9174115657806396
Forward computations: 79098
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 20
Decode time: 2.4645423889160156
Backtrace time: 0.0005476474761962891
Total time: 2.465090036392212
Forward computations: 102658
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: a a a a of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 18
Decode time: 2.811359405517578
Backtrace time: 0.0005943775177001953
Total time: 2.8119537830352783
Forward computations: 118778
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 2.129072666168213
Backtrace time: 0.0005087852478027344
Total time: 2.1295814514160156
Forward computations: 89638
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: a a the the peter piper wheres the the the the of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.6247146129608154
Backtrace time: 0.0005557537078857422
Total time: 2.625270366668701
Forward computations: 110718
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: a a peter piper wheres the the of peck of a a a a
S, D, I: 0 0 11
Decode time: 2.0595107078552246
Backtrace time: 0.0004780292510986328
Total time: 2.0599887371063232
Forward computations: 86848
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of a a the the peppers picked wheres picked peter piper wheres a a
S, D, I: 2 0 15
Decode time: 3.0494911670684814
Backtrace time: 0.0005896091461181641
Total time: 3.0500807762145996
Forward computations: 129318
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of of peck of a a peppers the wheres pickled peter a a a a
S, D, I: 2 0 17
Decode time: 3.405501365661621
Backtrace time: 0.0006093978881835938
Total time: 3.4061107635498047
Forward computations: 142338
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: a a the the peter piper wheres the the of peck of a a a a a a
S, D, I: 1 0 13
Decode time: 3.2491230964660645
Backtrace time: 0.0005958080291748047
Total time: 3.2497189044952393
Forward computations: 126528

============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: a a peter piper wheres of peck of a a peppers peppers pickled piper a a a a
S, D, I: 2 0 13
Decode time: 3.4747092723846436
Backtrace time: 0.0006213188171386719
Total time: 3.4753305912017822
Forward computations: 139858
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: a a peter piper wheres peppers the wheres pickled peter peppers peppers pickled piper a a
S, D, I: 0 0 13
Decode time: 2.4598701000213623
Backtrace time: 0.0006325244903564453
Total time: 2.4605026245117188
Forward computations: 105448
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of the the peppers picked wheres picked a a a a
S, D, I: 2 0 14
Decode time: 3.202761173248291
Backtrace time: 0.0006422996520996094
Total time: 3.2034034729003906
Forward computations: 126528
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: a a peter piper wheres of peck of of peck of the the the the a a
S, D, I: 2 0 12
Decode time: 2.667344808578491
Backtrace time: 0.0005660057067871094
Total time: 2.6679108142852783
Forward computations: 113198
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: a a peter piper wheres of peck of a a a a
S, D, I: 2 0 9
Decode time: 2.3349382877349854
Backtrace time: 0.0005230903625488281
Total time: 2.335461378097534
Forward computations: 97388
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: a a peter piper wheres of peck of a a peppers peter peppers pickled piper peppers peppers the wheres pickled peter a a a a
S, D, I: 2 0 18
Decode time: 3.895101547241211
Backtrace time: 0.00067138671875
Total time: 3.895772933959961
Forward computations: 163728
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper the the of peck of the the the the peppers picked wheres picked of peck of the the peter piper wheres a a
S, D, I: 4 0 28
Decode time: 4.038199186325073
Backtrace time: 0.0007159709930419922
Total time: 4.038915157318115
Forward computations: 166208
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked of peck of peter piper wheres the the peppers peppers pickled piper a a a a
S, D, I: 2 1 20
Decode time: 4.482024192810059
Backtrace time: 0.0007376670837402344
Total time: 4.482761859893799
Forward computations: 190078
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of a a peppers picked wheres picked a a a a a a peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 1 26
Decode time: 5.67296290397644
Backtrace time: 0.0008158683776855469
Total time: 5.673778772354126
Forward computations: 226968
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: a a peppers peppers pickled piper the the of peck of a a a a the the peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 0 22
Decode time: 4.388808250427246
Backtrace time: 0.0007228851318359375
Total time: 4.389531135559082
Forward computations: 182018
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the a a the the peter piper wheres of peck of peter piper wheres a a
S, D, I: 3 0 23
Decode time: 4.1637492179870605
Backtrace time: 0.0007107257843017578
Total time: 4.164459943771362
Forward computations: 174268
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 5.364665985107422
Backtrace time: 0.0008299350738525391
Total time: 5.365495920181274
Forward computations: 226968
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the of peck of peppers peppers pickled piper a a a a a a
S, D, I: 3 0 14
Decode time: 4.270896911621094
Backtrace time: 0.0006668567657470703
Total time: 4.271563768386841
Forward computations: 168998
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: a a the the the the of peck of a a the the of peck of a a peppers peppers pickled piper peter piper wheres a a
S, D, I: 3 0 20
Decode time: 3.7054998874664307
Backtrace time: 0.0006842613220214844
Total time: 3.706184148788452
Forward computations: 155668
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: a a the the of peck of a a a a of peck of a a peter piper wheres peppers peppers pickled piper a a a a of peck of peppers picked wheres picked a a
S, D, I: 3 0 24
Decode time: 4.785566329956055
Backtrace time: 0.0007922649383544922
Total time: 4.786358594894409
Forward computations: 203408
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 3.0772781372070312
Backtrace time: 0.0006020069122314453
Total time: 3.0778801441192627
Forward computations: 129318
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 4.821786880493164
Backtrace time: 0.0007572174072265625
Total time: 4.822544097900391
Forward computations: 203408
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of the the of peck of the the of peck of a a a a
S, D, I: 2 0 19
Decode time: 4.948795557022095
Backtrace time: 0.0007719993591308594
Total time: 4.949567556381226
Forward computations: 208678
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 5.157684087753296
Backtrace time: 0.0007951259613037109
Total time: 5.1584792137146
Forward computations: 213948
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 6.090795040130615
Backtrace time: 0.0008637905120849609
Total time: 6.0916588306427
Forward computations: 253628
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 4.446713447570801
Backtrace time: 0.0007114410400390625
Total time: 4.44742488861084
Forward computations: 187288

============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 4.438750267028809
Backtrace time: 0.0007486343383789062
Total time: 4.4394989013671875
Forward computations: 190078
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 4.884815454483032
Backtrace time: 0.0007443428039550781
Total time: 4.885559797286987
Forward computations: 203408
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a peppers peppers pickled piper a a
S, D, I: 0 0 31
Decode time: 5.730734586715698
Backtrace time: 0.0008432865142822266
Total time: 5.7315778732299805
Forward computations: 232238
experiment_name: Task 3: pruning 500
num_states: 176
num_arcs: 350
total_S: 99
total_D: 2
total_I: 761
total_N: 237
WER: 3.6371308016877637
total_time_sec: 162.80906295776367
avg_time_sec: 3.391855478286743
total_decode_time_sec: 162.77880692481995
avg_decode_time_sec: 3.391225144267082
total_backtrace_time_sec: 0.030256032943725586
avg_backtrace_time_sec: 0.0006303340196609497
total_forward_computations: 6740154
avg_forward_computations: 140419.875
empty_hypothesis_count: 0
pruning_threshold: 500
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: False
use_silence: True

In [15]:
unigram_probs = build_unigram_model(audio_to_reference, smoothing=1.0)

print("Estimated unigram probabilities:")
for word, prob in sorted(unigram_probs.items(), key=lambda x: x[1], reverse=True):
    print(f"{word:10s} -> {prob:.4f}")

Estimated unigram probabilities:
picked     -> 0.1498
peck       -> 0.1377
peppers    -> 0.1215
peter      -> 0.1134
piper      -> 0.1093
a          -> 0.0891
of         -> 0.0891
pickled    -> 0.0810
wheres     -> 0.0567
the        -> 0.0526

In [16]:
uniform_unigram_probs = {word: 1.0 / len(lex) for word in lex.keys()}

task4_experiments = [
    {
        "name": "No word prior",
        "use_unigram": False,
        "unigram_probs": None
    },
    {
        "name": "Uniform word prior",
        "use_unigram": True,
        "unigram_probs": uniform_unigram_probs
    },
    {
        "name": "Estimated unigram prior",
        "use_unigram": True,
        "unigram_probs": unigram_probs
    }
]

task4_summaries = []
task4_results = []

for exp in task4_experiments:
    print("\n" + "#" * 70)
    print(exp["name"])
    print("#" * 70)

    results, summary = evaluate_dataset(
        audio_to_reference,
        continue_prob=0.1,
        self_loop_prob=0.4,
        use_unigram=exp["use_unigram"],
        use_silence=True,
        pruning_threshold=None,
        unigram_probs=exp["unigram_probs"],
        experiment_name=exp["name"]
    )

    task4_summaries.append(summary)

    for r in results:
        row = dict(r)
        row["experiment_name"] = exp["name"]
        task4_results.append(row)

    for k, v in summary.items():
        print(f"{k}: {v}")

######################################################################
No word prior
######################################################################
============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: a a the the the the of peck of peppers peppers pickled piper of peck of a a
S, D, I: 2 0 15
Decode time: 2.429277181625366
Backtrace time: 0.0005593299865722656
Total time: 2.4298365116119385
Forward computations: 105448
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: a a the the of peck of a a
S, D, I: 1 0 6
Decode time: 1.7328307628631592
Backtrace time: 0.0005056858062744141
Total time: 1.7333364486694336
Forward computations: 76308
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 1.7243783473968506
Backtrace time: 0.0004932880401611328
Total time: 1.7248716354370117
Forward computations: 76308
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 1.5371301174163818
Backtrace time: 0.00044083595275878906
Total time: 1.5375709533691406
Forward computations: 68248
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: a a the the of peck of the the of peck of a a
S, D, I: 1 0 11
Decode time: 1.8742403984069824
Backtrace time: 0.0004799365997314453
Total time: 1.8747203350067139
Forward computations: 79098
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: a a of peck of the the peppers picked wheres picked peter piper wheres a a
S, D, I: 1 0 13
Decode time: 1.7862756252288818
Backtrace time: 0.00047969818115234375
Total time: 1.7867553234100342
Forward computations: 79098
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 2.7009329795837402
Backtrace time: 0.0005776882171630859
Total time: 2.7015106678009033
Forward computations: 118778
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 1.9653918743133545
Backtrace time: 0.0005075931549072266
Total time: 1.9658994674682617
Forward computations: 81578
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: a a the the peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 9
Decode time: 3.3183717727661133
Backtrace time: 0.0006175041198730469
Total time: 3.3189892768859863
Forward computations: 142338
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 2.302466630935669
Backtrace time: 0.0005600452423095703
Total time: 2.3030266761779785
Forward computations: 100178
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 2.2504091262817383
Backtrace time: 0.0005440711975097656
Total time: 2.250953197479248
Forward computations: 97388
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: a a a a of peck of the the of peck of a a of peck of a a
S, D, I: 2 0 14
Decode time: 2.9108195304870605
Backtrace time: 0.0006082057952880859
Total time: 2.9114277362823486
Forward computations: 129318
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: a a the the of peck of the the of peck of the the of peck of a a
S, D, I: 2 0 14
Decode time: 2.3606011867523193
Backtrace time: 0.0005767345428466797
Total time: 2.361177921295166
Forward computations: 102658
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a the the the the of peck of peter piper wheres of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.6609585285186768
Backtrace time: 0.0005686283111572266
Total time: 2.661527156829834
Forward computations: 118778
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 2.6421844959259033
Backtrace time: 0.000537872314453125
Total time: 2.6427223682403564
Forward computations: 115988
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peter piper wheres of peck of the the a a
S, D, I: 2 0 8
Decode time: 1.7730355262756348
Backtrace time: 0.0004904270172119141
Total time: 1.7735259532928467
Forward computations: 79098
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 20
Decode time: 2.3194081783294678
Backtrace time: 0.0005731582641601562
Total time: 2.319981336593628
Forward computations: 102658
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: a a a a of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 18
Decode time: 2.660456418991089
Backtrace time: 0.0005822181701660156
Total time: 2.661038637161255
Forward computations: 118778
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 2.0331838130950928
Backtrace time: 0.0005311965942382812
Total time: 2.033715009689331
Forward computations: 89638
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: a a the the peter piper wheres the the the the of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.5404515266418457
Backtrace time: 0.000553131103515625
Total time: 2.5410046577453613
Forward computations: 110718
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: a a peter piper wheres the the of peck of a a a a
S, D, I: 0 0 11
Decode time: 1.9847655296325684
Backtrace time: 0.0005104541778564453
Total time: 1.9852759838104248
Forward computations: 86848
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of a a the the peppers picked wheres picked peter piper wheres a a
S, D, I: 2 0 15
Decode time: 3.050539493560791
Backtrace time: 0.0006079673767089844
Total time: 3.0511474609375
Forward computations: 129318
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of of peck of a a peppers the wheres pickled peter a a a a
S, D, I: 2 0 17
Decode time: 3.293210506439209
Backtrace time: 0.0006473064422607422
Total time: 3.2938578128814697
Forward computations: 142338

============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: a a the the peter piper wheres the the of peck of a a a a a a
S, D, I: 1 0 13
Decode time: 3.097372055053711
Backtrace time: 0.0006589889526367188
Total time: 3.0980310440063477
Forward computations: 126528
============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: a a peter piper wheres of peck of a a peppers peppers pickled piper a a a a
S, D, I: 2 0 13
Decode time: 3.2767601013183594
Backtrace time: 0.0006270408630371094
Total time: 3.2773871421813965
Forward computations: 139858
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: a a peter piper wheres peppers the wheres pickled peter peppers peppers pickled piper a a
S, D, I: 0 0 13
Decode time: 2.4099934101104736
Backtrace time: 0.0005447864532470703
Total time: 2.4105381965637207
Forward computations: 105448
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of the the peppers picked wheres picked a a a a
S, D, I: 2 0 14
Decode time: 2.965546131134033
Backtrace time: 0.0005896091461181641
Total time: 2.9661357402801514
Forward computations: 126528
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: a a peter piper wheres of peck of of peck of the the the the a a
S, D, I: 2 0 12
Decode time: 2.6000211238861084
Backtrace time: 0.0005552768707275391
Total time: 2.600576400756836
Forward computations: 113198
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: a a peter piper wheres of peck of a a a a
S, D, I: 2 0 9
Decode time: 2.3043594360351562
Backtrace time: 0.0005249977111816406
Total time: 2.304884433746338
Forward computations: 97388
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: a a peter piper wheres of peck of a a peppers peter peppers pickled piper peppers peppers the wheres pickled peter a a a a
S, D, I: 2 0 18
Decode time: 3.7802531719207764
Backtrace time: 0.0006756782531738281
Total time: 3.78092885017395
Forward computations: 163728
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper the the of peck of the the the the peppers picked wheres picked of peck of the the peter piper wheres a a
S, D, I: 4 0 28
Decode time: 3.8787307739257812
Backtrace time: 0.0007174015045166016
Total time: 3.879448175430298
Forward computations: 166208
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked of peck of peter piper wheres the the peppers peppers pickled piper a a a a
S, D, I: 2 1 20
Decode time: 4.2729172706604
Backtrace time: 0.0007543563842773438
Total time: 4.273671627044678
Forward computations: 190078
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of a a peppers picked wheres picked a a a a a a peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 1 26
Decode time: 5.107813119888306
Backtrace time: 0.0008246898651123047
Total time: 5.108637809753418
Forward computations: 226968
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: a a peppers peppers pickled piper the the of peck of a a a a the the peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 0 22
Decode time: 4.109216213226318
Backtrace time: 0.000705718994140625
Total time: 4.109921932220459
Forward computations: 182018
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the a a the the peter piper wheres of peck of peter piper wheres a a
S, D, I: 3 0 23
Decode time: 4.029568195343018
Backtrace time: 0.0006957054138183594
Total time: 4.030263900756836
Forward computations: 174268
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 5.153672933578491
Backtrace time: 0.0008611679077148438
Total time: 5.154534101486206
Forward computations: 226968
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the of peck of peppers peppers pickled piper a a a a a a
S, D, I: 3 0 14
Decode time: 3.900864839553833
Backtrace time: 0.0006661415100097656
Total time: 3.9015309810638428
Forward computations: 168998
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: a a the the the the of peck of a a the the of peck of a a peppers peppers pickled piper peter piper wheres a a
S, D, I: 3 0 20
Decode time: 3.564493179321289
Backtrace time: 0.0006668567657470703
Total time: 3.565160036087036
Forward computations: 155668
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: a a the the of peck of a a a a of peck of a a peter piper wheres peppers peppers pickled piper a a a a of peck of peppers picked wheres picked a a
S, D, I: 3 0 24
Decode time: 4.662054061889648
Backtrace time: 0.0007863044738769531
Total time: 4.662840366363525
Forward computations: 203408
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 2.950873374938965
Backtrace time: 0.0005998611450195312
Total time: 2.9514732360839844
Forward computations: 129318
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 4.620595455169678
Backtrace time: 0.0007627010345458984
Total time: 4.621358156204224
Forward computations: 203408
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of the the of peck of the the of peck of a a a a
S, D, I: 2 0 19
Decode time: 4.9976301193237305
Backtrace time: 0.0007450580596923828
Total time: 4.998375177383423
Forward computations: 208678
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 4.898696422576904
Backtrace time: 0.0008001327514648438
Total time: 4.899496555328369
Forward computations: 213948
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 6.169086933135986
Backtrace time: 0.0009031295776367188
Total time: 6.169990062713623
Forward computations: 253628

============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 4.332897186279297
Backtrace time: 0.0007202625274658203
Total time: 4.333617448806763
Forward computations: 187288
============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 4.252820730209351
Backtrace time: 0.0007393360137939453
Total time: 4.2535600662231445
Forward computations: 190078
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 4.759558200836182
Backtrace time: 0.0007412433624267578
Total time: 4.760299444198608
Forward computations: 203408
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a peppers peppers pickled piper a a
S, D, I: 0 0 31
Decode time: 5.646082162857056
Backtrace time: 0.0008413791656494141
Total time: 5.646923542022705
Forward computations: 232238
experiment_name: No word prior
num_states: 176
num_arcs: 350
total_S: 99
total_D: 2
total_I: 761
total_N: 237
WER: 3.6371308016877637
total_time_sec: 155.62345695495605
avg_time_sec: 3.242155353228251
total_decode_time_sec: 155.59319615364075
avg_decode_time_sec: 3.2415249198675156
total_backtrace_time_sec: 0.030260801315307617
avg_backtrace_time_sec: 0.0006304333607355753
total_forward_computations: 6740154
avg_forward_computations: 140419.875
empty_hypothesis_count: 0
pruning_threshold: None
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: False
use_silence: True

######################################################################
Uniform word prior
######################################################################
============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: a a the the the the of peck of peppers peppers pickled piper of peck of a a
S, D, I: 2 0 15
Decode time: 2.445784330368042
Backtrace time: 0.0005831718444824219
Total time: 2.4463675022125244
Forward computations: 105448
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: a a the the of peck of a a
S, D, I: 1 0 6
Decode time: 1.7993700504302979
Backtrace time: 0.0004608631134033203
Total time: 1.7998309135437012
Forward computations: 76308
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 1.7517554759979248
Backtrace time: 0.00048470497131347656
Total time: 1.7522401809692383
Forward computations: 76308
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 1.5798909664154053
Backtrace time: 0.0004417896270751953
Total time: 1.5803327560424805
Forward computations: 68248
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: a a the the of peck of the the of peck of a a
S, D, I: 1 0 11
Decode time: 1.8040099143981934
Backtrace time: 0.00048279762268066406
Total time: 1.804492712020874
Forward computations: 79098
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: a a of peck of the the peppers picked wheres picked peter piper wheres a a
S, D, I: 1 0 13
Decode time: 1.8454856872558594
Backtrace time: 0.0005347728729248047
Total time: 1.8460204601287842
Forward computations: 79098
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 2.8115265369415283
Backtrace time: 0.0006151199340820312
Total time: 2.8121416568756104
Forward computations: 118778
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 1.987619400024414
Backtrace time: 0.0005042552947998047
Total time: 1.9881236553192139
Forward computations: 81578
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: a a the the peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 9
Decode time: 3.238345146179199
Backtrace time: 0.0006098747253417969
Total time: 3.238955020904541
Forward computations: 142338
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 2.2855947017669678
Backtrace time: 0.0005667209625244141
Total time: 2.286161422729492
Forward computations: 100178
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 2.345351457595825
Backtrace time: 0.0005354881286621094
Total time: 2.3458869457244873
Forward computations: 97388
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: a a a a of peck of the the of peck of a a of peck of a a
S, D, I: 2 0 14
Decode time: 2.9641191959381104
Backtrace time: 0.0005815029144287109
Total time: 2.964700698852539
Forward computations: 129318
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: a a the the of peck of the the of peck of the the of peck of a a
S, D, I: 2 0 14
Decode time: 2.4098381996154785
Backtrace time: 0.0005400180816650391
Total time: 2.4103782176971436
Forward computations: 102658
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peter peppers pickled piper peppers a a
S, D, I: 0 0 12
Decode time: 2.6784377098083496
Backtrace time: 0.0005633831024169922
Total time: 2.6790010929107666
Forward computations: 118778
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 2.6627109050750732
Backtrace time: 0.0005664825439453125
Total time: 2.6632773876190186
Forward computations: 115988
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peter piper wheres of peck of the the a a
S, D, I: 2 0 8
Decode time: 1.813631296157837
Backtrace time: 0.000476837158203125
Total time: 1.81410813331604
Forward computations: 79098
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 20
Decode time: 2.394526720046997
Backtrace time: 0.0005471706390380859
Total time: 2.395073890686035
Forward computations: 102658

============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: a a a a of peck of a a the the peppers picked wheres picked peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 19
Decode time: 2.687964677810669
Backtrace time: 0.0005741119384765625
Total time: 2.6885387897491455
Forward computations: 118778
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 2.177520990371704
Backtrace time: 0.0005109310150146484
Total time: 2.1780319213867188
Forward computations: 89638
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: a a the the peter piper wheres the the the the of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.552290678024292
Backtrace time: 0.0005559921264648438
Total time: 2.552846670150757
Forward computations: 110718
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: a a peter piper wheres the the of peck of a a a a
S, D, I: 0 0 11
Decode time: 2.0467402935028076
Backtrace time: 0.0005080699920654297
Total time: 2.047248363494873
Forward computations: 86848
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of a a the the peppers picked wheres picked peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.9916675090789795
Backtrace time: 0.0005946159362792969
Total time: 2.992262125015259
Forward computations: 129318
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of of peck of a a peppers the wheres pickled peter a a a a
S, D, I: 2 0 17
Decode time: 3.2457823753356934
Backtrace time: 0.0006558895111083984
Total time: 3.2464382648468018
Forward computations: 142338
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: a a the the peter piper wheres the the of peck of a a a a a a
S, D, I: 1 0 13
Decode time: 2.8837196826934814
Backtrace time: 0.0005855560302734375
Total time: 2.884305238723755
Forward computations: 126528
============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: a a peter piper wheres of peck of a a peppers peppers pickled piper a a a a
S, D, I: 2 0 13
Decode time: 3.1841325759887695
Backtrace time: 0.000606536865234375
Total time: 3.184739112854004
Forward computations: 139858
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: a a peter piper wheres peppers the wheres pickled peter peppers peppers pickled piper a a
S, D, I: 0 0 13
Decode time: 2.6175594329833984
Backtrace time: 0.0006690025329589844
Total time: 2.6182284355163574
Forward computations: 105448
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of the the peppers picked wheres picked a a a a
S, D, I: 2 0 14
Decode time: 3.0069291591644287
Backtrace time: 0.0005877017974853516
Total time: 3.007516860961914
Forward computations: 126528
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: a a peter piper wheres of peck of of peck of the the the the a a
S, D, I: 2 0 12
Decode time: 2.5605084896087646
Backtrace time: 0.0005588531494140625
Total time: 2.5610673427581787
Forward computations: 113198
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: a a peter piper wheres of peck of a a a a
S, D, I: 2 0 9
Decode time: 2.193972587585449
Backtrace time: 0.0005242824554443359
Total time: 2.1944968700408936
Forward computations: 97388
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: a a peter piper wheres of peck of a a peppers peter peppers pickled piper peppers peppers the wheres pickled peter a a a a
S, D, I: 2 0 18
Decode time: 3.7003002166748047
Backtrace time: 0.0006804466247558594
Total time: 3.7009806632995605
Forward computations: 163728
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper the the of peck of the the peppers picked wheres picked of peck of the the peter piper wheres a a
S, D, I: 4 0 26
Decode time: 3.7758090496063232
Backtrace time: 0.0007038116455078125
Total time: 3.776512861251831
Forward computations: 166208
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked of peck of peter piper wheres the the peppers peppers pickled piper a a a a
S, D, I: 2 1 20
Decode time: 4.435538291931152
Backtrace time: 0.0007469654083251953
Total time: 4.4362852573394775
Forward computations: 190078
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of a a peppers picked wheres picked a a a a a a peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 1 26
Decode time: 5.244144439697266
Backtrace time: 0.0008847713470458984
Total time: 5.2450292110443115
Forward computations: 226968
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: a a peppers peppers pickled piper the the of peck of a a a a the the peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 0 22
Decode time: 4.148491382598877
Backtrace time: 0.0007522106170654297
Total time: 4.149243593215942
Forward computations: 182018
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the a a the the peter piper wheres of peck of peter piper wheres a a
S, D, I: 3 0 23
Decode time: 4.191016674041748
Backtrace time: 0.0007040500640869141
Total time: 4.191720724105835
Forward computations: 174268
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 5.2181761264801025
Backtrace time: 0.0008533000946044922
Total time: 5.219029426574707
Forward computations: 226968
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the of peck of peppers peppers pickled piper a a a a a a
S, D, I: 3 0 14
Decode time: 4.006039381027222
Backtrace time: 0.0006835460662841797
Total time: 4.006722927093506
Forward computations: 168998
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: a a the the the the of peck of a a the the of peck of a a peppers peppers pickled piper peter piper wheres a a
S, D, I: 3 0 20
Decode time: 3.5565025806427
Backtrace time: 0.0006835460662841797
Total time: 3.5571861267089844
Forward computations: 155668
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: a a the the of peck of a a a a of peck of a a peter piper wheres peppers peppers pickled piper a a a a of peck of peppers picked wheres picked a a
S, D, I: 3 0 24
Decode time: 4.825933933258057
Backtrace time: 0.0008656978607177734
Total time: 4.826799631118774
Forward computations: 203408

============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 2.9493210315704346
Backtrace time: 0.0006005764007568359
Total time: 2.9499216079711914
Forward computations: 129318
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 4.926682472229004
Backtrace time: 0.0008082389831542969
Total time: 4.927490711212158
Forward computations: 203408
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of of peck of the the of peck of a a a a
S, D, I: 2 0 17
Decode time: 4.777697801589966
Backtrace time: 0.0007469654083251953
Total time: 4.778444766998291
Forward computations: 208678
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 4.878556728363037
Backtrace time: 0.0007932186126708984
Total time: 4.879349946975708
Forward computations: 213948
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 5.768596887588501
Backtrace time: 0.0009093284606933594
Total time: 5.769506216049194
Forward computations: 253628
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 4.25216817855835
Backtrace time: 0.0007207393646240234
Total time: 4.252888917922974
Forward computations: 187288
============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 4.383520126342773
Backtrace time: 0.0007536411285400391
Total time: 4.3842737674713135
Forward computations: 190078
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 4.6493823528289795
Backtrace time: 0.0007660388946533203
Total time: 4.650148391723633
Forward computations: 203408
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a
S, D, I: 0 0 25
Decode time: 5.345489025115967
Backtrace time: 0.0008409023284912109
Total time: 5.346329927444458
Forward computations: 232238
experiment_name: Uniform word prior
num_states: 176
num_arcs: 350
total_S: 95
total_D: 2
total_I: 749
total_N: 237
WER: 3.569620253164557
total_time_sec: 156.030677318573
avg_time_sec: 3.250639110803604
total_decode_time_sec: 156.0001528263092
avg_decode_time_sec: 3.2500031838814416
total_backtrace_time_sec: 0.030524492263793945
avg_backtrace_time_sec: 0.0006359269221623739
total_forward_computations: 6740154
avg_forward_computations: 140419.875
empty_hypothesis_count: 0
pruning_threshold: None
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: True
use_silence: True

######################################################################
Estimated unigram prior
######################################################################
============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: a a the the the the of peck of peppers peppers pickled piper of peck of a a
S, D, I: 2 0 15
Decode time: 2.439161777496338
Backtrace time: 0.0005822181701660156
Total time: 2.439743995666504
Forward computations: 105448
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: a a the the of peck of a a
S, D, I: 1 0 6
Decode time: 1.8204669952392578
Backtrace time: 0.0004897117614746094
Total time: 1.8209567070007324
Forward computations: 76308
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 1.838597297668457
Backtrace time: 0.00046563148498535156
Total time: 1.8390629291534424
Forward computations: 76308
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 1.5812690258026123
Backtrace time: 0.0004699230194091797
Total time: 1.5817389488220215
Forward computations: 68248
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: a a the the of peck of the the of peck of a a
S, D, I: 1 0 11
Decode time: 1.8601832389831543
Backtrace time: 0.0005018711090087891
Total time: 1.860685110092163
Forward computations: 79098
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: a a of peck of the the peppers picked wheres picked peter piper wheres a a
S, D, I: 1 0 13
Decode time: 1.8453655242919922
Backtrace time: 0.0004947185516357422
Total time: 1.845860242843628
Forward computations: 79098
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 2.7969467639923096
Backtrace time: 0.0006251335144042969
Total time: 2.797571897506714
Forward computations: 118778
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 1.979741096496582
Backtrace time: 0.0005049705505371094
Total time: 1.9802460670471191
Forward computations: 81578
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: a a the the peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 9
Decode time: 3.2844624519348145
Backtrace time: 0.0006301403045654297
Total time: 3.28509259223938
Forward computations: 142338
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 2.336099624633789
Backtrace time: 0.0005540847778320312
Total time: 2.336653709411621
Forward computations: 100178
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 2.2472565174102783
Backtrace time: 0.00052642822265625
Total time: 2.2477829456329346
Forward computations: 97388
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: a a a a of peck of the the of peck of a a of peck of a a
S, D, I: 2 0 14
Decode time: 3.039663791656494
Backtrace time: 0.0006000995635986328
Total time: 3.0402638912200928
Forward computations: 129318

============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: a a the the of peck of the the of peck of the the of peck of a a
S, D, I: 2 0 14
Decode time: 2.357884168624878
Backtrace time: 0.0005390644073486328
Total time: 2.3584232330322266
Forward computations: 102658
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peter peppers pickled piper peppers a a
S, D, I: 0 0 12
Decode time: 2.894395589828491
Backtrace time: 0.0005710124969482422
Total time: 2.8949666023254395
Forward computations: 118778
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 2.744166612625122
Backtrace time: 0.0005731582641601562
Total time: 2.7447397708892822
Forward computations: 115988
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peter piper wheres of peck of the the a a
S, D, I: 2 0 8
Decode time: 2.037896156311035
Backtrace time: 0.0005562305450439453
Total time: 2.038452386856079
Forward computations: 79098
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 20
Decode time: 3.1138737201690674
Backtrace time: 0.0006239414215087891
Total time: 3.114497661590576
Forward computations: 102658
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: a a a a of peck of a a the the peppers picked wheres picked peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 19
Decode time: 3.870898962020874
Backtrace time: 0.001203775405883789
Total time: 3.872102737426758
Forward computations: 118778
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 3.0798416137695312
Backtrace time: 0.0008304119110107422
Total time: 3.080672025680542
Forward computations: 89638
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: a a the the peter piper wheres the the the the of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 4.110186815261841
Backtrace time: 0.0006122589111328125
Total time: 4.110799074172974
Forward computations: 110718
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: a a peter piper wheres the the of peck of a a a a
S, D, I: 0 0 11
Decode time: 2.5952134132385254
Backtrace time: 0.0005471706390380859
Total time: 2.5957605838775635
Forward computations: 86848
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of a a the the peppers picked wheres picked peter piper wheres a a
S, D, I: 2 0 15
Decode time: 3.6355957984924316
Backtrace time: 0.0010492801666259766
Total time: 3.6366450786590576
Forward computations: 129318
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of of peck of a a peppers the wheres pickled peter a a a a
S, D, I: 2 0 17
Decode time: 5.196420907974243
Backtrace time: 0.0006985664367675781
Total time: 5.197119474411011
Forward computations: 142338
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: a a the the peter piper wheres the the of peck of a a a a a a
S, D, I: 1 0 13
Decode time: 4.297733306884766
Backtrace time: 0.0006392002105712891
Total time: 4.298372507095337
Forward computations: 126528
============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: a a peter piper wheres of peck of a a peppers peppers pickled piper a a a a
S, D, I: 2 0 13
Decode time: 3.8160903453826904
Backtrace time: 0.0006458759307861328
Total time: 3.8167362213134766
Forward computations: 139858
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: a a peter piper wheres peppers the wheres pickled peter peppers peppers pickled piper a a
S, D, I: 0 0 13
Decode time: 2.877786636352539
Backtrace time: 0.0006673336029052734
Total time: 2.8784539699554443
Forward computations: 105448
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked a a a a
S, D, I: 3 0 12
Decode time: 3.9606995582580566
Backtrace time: 0.0006346702575683594
Total time: 3.961334228515625
Forward computations: 126528
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: a a peter piper wheres of peck of of peck of the the the the a a
S, D, I: 2 0 12
Decode time: 3.2072222232818604
Backtrace time: 0.0006165504455566406
Total time: 3.207838773727417
Forward computations: 113198
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: a a peter piper wheres of peck of a a a a
S, D, I: 2 0 9
Decode time: 3.377318859100342
Backtrace time: 0.0014996528625488281
Total time: 3.3788185119628906
Forward computations: 97388
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: a a peter piper wheres of peck of a a peppers peter peppers pickled piper peppers peppers the wheres pickled peter a a a a
S, D, I: 2 0 18
Decode time: 4.857679605484009
Backtrace time: 0.0007538795471191406
Total time: 4.858433485031128
Forward computations: 163728
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper the the of peck of the the peppers picked wheres picked of peck of the the peter piper wheres a a
S, D, I: 4 0 26
Decode time: 4.466896295547485
Backtrace time: 0.0007905960083007812
Total time: 4.467686891555786
Forward computations: 166208
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked of peck of peter piper wheres the the peppers peppers pickled piper a a a a
S, D, I: 2 1 20
Decode time: 6.308465242385864
Backtrace time: 0.0008158683776855469
Total time: 6.30928111076355
Forward computations: 190078
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of a a peppers picked wheres picked a a a a a a peppers picked wheres picked peppers peter peppers pickled piper peppers a a
S, D, I: 1 1 27
Decode time: 6.226244211196899
Backtrace time: 0.0008907318115234375
Total time: 6.227134943008423
Forward computations: 226968
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: a a peppers peppers pickled piper the the of peck of a a a a peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 0 20
Decode time: 5.718480348587036
Backtrace time: 0.0018396377563476562
Total time: 5.720319986343384
Forward computations: 182018

============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the a a the the peter piper wheres of peck of peter piper wheres a a
S, D, I: 3 0 23
Decode time: 4.565529823303223
Backtrace time: 0.0007460117340087891
Total time: 4.5662758350372314
Forward computations: 174268
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 6.346116304397583
Backtrace time: 0.0009188652038574219
Total time: 6.34703516960144
Forward computations: 226968
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the of peck of peppers peppers pickled piper a a a a a a
S, D, I: 3 0 14
Decode time: 5.370919942855835
Backtrace time: 0.0009148120880126953
Total time: 5.371834754943848
Forward computations: 168998
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: a a the the the the of peck of a a the the of peck of a a peppers peppers pickled piper peter piper wheres a a
S, D, I: 3 0 20
Decode time: 6.512351751327515
Backtrace time: 0.0008234977722167969
Total time: 6.5131752490997314
Forward computations: 155668
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: a a the the of peck of a a a a of peck of a a peter piper wheres peppers peppers pickled piper a a a a of peck of peppers picked wheres picked a a
S, D, I: 3 0 24
Decode time: 6.0094993114471436
Backtrace time: 0.001077413558959961
Total time: 6.0105767250061035
Forward computations: 203408
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 4.198260307312012
Backtrace time: 0.0007195472717285156
Total time: 4.19897985458374
Forward computations: 129318
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 5.7767815589904785
Backtrace time: 0.0007960796356201172
Total time: 5.777577638626099
Forward computations: 203408
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of of peck of the the of peck of a a a a
S, D, I: 2 0 17
Decode time: 5.454006910324097
Backtrace time: 0.0008409023284912109
Total time: 5.454847812652588
Forward computations: 208678
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 5.73218035697937
Backtrace time: 0.0008630752563476562
Total time: 5.733043432235718
Forward computations: 213948
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 6.62352442741394
Backtrace time: 0.0009918212890625
Total time: 6.624516248703003
Forward computations: 253628
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 5.509298324584961
Backtrace time: 0.0007610321044921875
Total time: 5.510059356689453
Forward computations: 187288
============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 6.140270471572876
Backtrace time: 0.0014579296112060547
Total time: 6.141728401184082
Forward computations: 190078
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 5.2204461097717285
Backtrace time: 0.0007679462432861328
Total time: 5.221214056015015
Forward computations: 203408
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a
S, D, I: 0 0 25
Decode time: 6.424221038818359
Backtrace time: 0.0008711814880371094
Total time: 6.4250922203063965
Forward computations: 232238
experiment_name: Estimated unigram prior
num_states: 176
num_arcs: 350
total_S: 95
total_D: 2
total_I: 746
total_N: 237
WER: 3.5569620253164556
total_time_sec: 191.74020504951477
avg_time_sec: 3.9945876051982245
total_decode_time_sec: 191.7036111354828
avg_decode_time_sec: 3.993825231989225
total_backtrace_time_sec: 0.03659391403198242
avg_backtrace_time_sec: 0.0007623732089996338
total_forward_computations: 6740154
avg_forward_computations: 140419.875
empty_hypothesis_count: 0
pruning_threshold: None
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: True
use_silence: True

In [17]:
import pandas as pd

exp_summary_df = pd.DataFrame(experiment_summaries)
task3_summary_df = pd.DataFrame(task3_summaries)
task4_summary_df = pd.DataFrame(task4_summaries)

display_cols = [
    "experiment_name",
    "WER",
    "total_S",
    "total_D",
    "total_I",
    "num_states",
    "num_arcs",
    "avg_decode_time_sec",
    "avg_backtrace_time_sec",
    "avg_time_sec",
    "avg_forward_computations",
    "empty_hypothesis_count"
]

print("Tasks 1-2 summary")
display(exp_summary_df[display_cols].sort_values("WER"))

print("Task 3 summary")
display(task3_summary_df[display_cols].sort_values("WER"))

print("Task 4 summary")
display(task4_summary_df[display_cols].sort_values("WER"))

Tasks 1-2 summary

,experiment_name,WER,total_S,total_D,total_I,num_states,num_arcs,avg_decode_time_sec,avg_backtrace_time_sec,avg_time_sec,avg_forward_computations,empty_hypothesis_count
3,Task 2: + silence,3.637131,99,2,761,176,350,3.266694,0.000630,3.267324,140419.875,0
2,Task 2: self-loop 0.4,4.253165,88,1,919,116,230,2.270320,0.000541,2.270860,95588.625,0
1,Task 2: loop penalty,8.455696,38,0,1966,116,230,2.268882,0.000643,2.269525,95588.625,0
0,Task 1 baseline,11.177215,32,0,2617,116,230,2.175276,0.000656,2.175932,95588.625,0

Task 3 summary

,experiment_name,WER,total_S,total_D,total_I,num_states,num_arcs,avg_decode_time_sec,avg_backtrace_time_sec,avg_time_sec,avg_forward_computations,empty_hypothesis_count
1,Task 3: pruning 50,2.084388,42,147,305,176,350,1.430540,0.000460,1.431000,58061.250000,29
0,Task 3: no pruning,3.637131,99,2,761,176,350,3.299243,0.000645,3.299888,140419.875000,0
2,Task 3: pruning 100,3.637131,99,2,761,176,350,2.429537,0.000649,2.430186,99628.708333,0
3,Task 3: pruning 200,3.637131,99,2,761,176,350,3.156782,0.000646,3.157428,131377.458333,0
4,Task 3: pruning 500,3.637131,99,2,761,176,350,3.391225,0.000630,3.391855,140419.875000,0

Task 4 summary

,experiment_name,WER,total_S,total_D,total_I,num_states,num_arcs,avg_decode_time_sec,avg_backtrace_time_sec,avg_time_sec,avg_forward_computations,empty_hypothesis_count
2,Estimated unigram prior,3.556962,95,2,746,176,350,3.993825,0.000762,3.994588,140419.875,0
1,Uniform word prior,3.569620,95,2,749,176,350,3.250003,0.000636,3.250639,140419.875,0
0,No word prior,3.637131,99,2,761,176,350,3.241525,0.000630,3.242155,140419.875,0

In [18]:
results, summary = evaluate_dataset(
    audio_to_reference,
    continue_prob=0.1,
    self_loop_prob=0.4,
    use_unigram=True,
    use_silence=True,
    pruning_threshold=50,
    unigram_probs=unigram_probs,
    experiment_name="Task 4: pruning 50 + estimated unigram"
)

for k, v in summary.items():
    print(f"{k}: {v}")

No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis:
S, D, I: 0 3 0
Decode time: 1.1195390224456787
Backtrace time: 0.000324249267578125
Total time: 1.1198632717132568
Forward computations: 45662
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis:
S, D, I: 0 3 0
Decode time: 0.6395905017852783
Backtrace time: 0.0003821849822998047
Total time: 0.6399726867675781
Forward computations: 27124
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 0.8971960544586182
Backtrace time: 0.00046443939208984375
Total time: 0.897660493850708
Forward computations: 36990
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 0.6541454792022705
Backtrace time: 0.0004634857177734375
Total time: 0.654608964920044
Forward computations: 27622
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis:
S, D, I: 0 3 0
Decode time: 0.8075776100158691
Backtrace time: 0.0003063678741455078
Total time: 0.8078839778900146
Forward computations: 32626
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis:
S, D, I: 0 3 0
Decode time: 0.8653717041015625
Backtrace time: 0.00030493736267089844
Total time: 0.8656766414642334
Forward computations: 35534
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 1.2253930568695068
Backtrace time: 0.0005929470062255859
Total time: 1.2259860038757324
Forward computations: 49456
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 0.8361358642578125
Backtrace time: 0.00048041343688964844
Total time: 0.8366162776947021
Forward computations: 33416
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis:
S, D, I: 0 3 0
Decode time: 1.413517951965332
Backtrace time: 0.0003173351287841797
Total time: 1.4138352870941162
Forward computations: 57370
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 1.425306797027588
Backtrace time: 0.0005605220794677734
Total time: 1.4258673191070557
Forward computations: 57066
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 1.033456802368164
Backtrace time: 0.0005662441253662109
Total time: 1.0340230464935303
Forward computations: 41638
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.2801413536071777
Backtrace time: 0.0003209114074707031
Total time: 1.2804622650146484
Forward computations: 52700
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.1398696899414062
Backtrace time: 0.0003070831298828125
Total time: 1.140176773071289
Forward computations: 45978
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.2978599071502686
Backtrace time: 0.0002989768981933594
Total time: 1.298158884048462
Forward computations: 52176
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 1.1400158405303955
Backtrace time: 0.0006299018859863281
Total time: 1.1406457424163818
Forward computations: 45108
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis:
S, D, I: 0 4 0
Decode time: 0.8779482841491699
Backtrace time: 0.0003085136413574219
Total time: 0.8782567977905273
Forward computations: 34930
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis:
S, D, I: 0 4 0
Decode time: 1.435600757598877
Backtrace time: 0.0003273487091064453
Total time: 1.4359281063079834
Forward computations: 45840
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis:
S, D, I: 0 4 0
Decode time: 1.4210638999938965
Backtrace time: 0.0003178119659423828
Total time: 1.4213817119598389
Forward computations: 49034
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 1.3603465557098389
Backtrace time: 0.00055694580078125
Total time: 1.3609035015106201
Forward computations: 50164
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis:
S, D, I: 0 4 0
Decode time: 1.9041430950164795
Backtrace time: 0.0003871917724609375
Total time: 1.9045302867889404
Forward computations: 48752
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis:
S, D, I: 0 3 0
Decode time: 0.9782669544219971
Backtrace time: 0.0009953975677490234
Total time: 0.9792623519897461
Forward computations: 31448
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis:
S, D, I: 0 6 0
Decode time: 1.4038069248199463
Backtrace time: 0.00030159950256347656
Total time: 1.4041085243225098
Forward computations: 56932

No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.6813600063323975
Backtrace time: 0.0003151893615722656
Total time: 1.6816751956939697
Forward computations: 56952
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.3465871810913086
Backtrace time: 0.000308990478515625
Total time: 1.3468961715698242
Forward computations: 52860
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.3001184463500977
Backtrace time: 0.00039005279541015625
Total time: 1.3005084991455078
Forward computations: 52164
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis:
S, D, I: 0 3 0
Decode time: 0.8405227661132812
Backtrace time: 0.00034928321838378906
Total time: 0.840872049331665
Forward computations: 34986
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked a a a a
S, D, I: 3 0 12
Decode time: 1.2099874019622803
Backtrace time: 0.0005936622619628906
Total time: 1.2105810642242432
Forward computations: 49170
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.0782456398010254
Backtrace time: 0.0003120899200439453
Total time: 1.0785577297210693
Forward computations: 44388
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis:
S, D, I: 0 3 0
Decode time: 0.9601542949676514
Backtrace time: 0.0003228187561035156
Total time: 0.9604771137237549
Forward computations: 39312
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis:
S, D, I: 0 7 0
Decode time: 2.7551445960998535
Backtrace time: 0.00038743019104003906
Total time: 2.7555320262908936
Forward computations: 69678
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis:
S, D, I: 0 8 0
Decode time: 1.7005219459533691
Backtrace time: 0.00030493736267089844
Total time: 1.70082688331604
Forward computations: 68968
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis:
S, D, I: 0 9 0
Decode time: 2.222648859024048
Backtrace time: 0.0003001689910888672
Total time: 2.2229490280151367
Forward computations: 80428
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis:
S, D, I: 0 7 0
Decode time: 2.720229148864746
Backtrace time: 0.0003159046173095703
Total time: 2.7205450534820557
Forward computations: 84544
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis:
S, D, I: 0 6 0
Decode time: 1.806103229522705
Backtrace time: 0.0003077983856201172
Total time: 1.8064110279083252
Forward computations: 70306
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.7352499961853027
Backtrace time: 0.0003154277801513672
Total time: 1.735565423965454
Forward computations: 73050
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 1.925661325454712
Backtrace time: 0.0008406639099121094
Total time: 1.926501989364624
Forward computations: 77756
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis:
S, D, I: 0 5 0
Decode time: 1.6560099124908447
Backtrace time: 0.00031256675720214844
Total time: 1.6563224792480469
Forward computations: 58160
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis:
S, D, I: 0 7 0
Decode time: 1.625687599182129
Backtrace time: 0.0003113746643066406
Total time: 1.6259989738464355
Forward computations: 65798
No path got to the end of the observations.
Warning: pruning removed all valid final paths for this utterance.
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis:
S, D, I: 0 12 0
Decode time: 2.2254719734191895
Backtrace time: 0.0003478527069091797
Total time: 2.2258198261260986
Forward computations: 91812
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 1.331918478012085
Backtrace time: 0.0006120204925537109
Total time: 1.3325304985046387
Forward computations: 52788
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 1.9673445224761963
Backtrace time: 0.0008039474487304688
Total time: 1.9681484699249268
Forward computations: 80436
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of of peck of the the of peck of a a a a
S, D, I: 2 0 17
Decode time: 1.887983798980713
Backtrace time: 0.0007803440093994141
Total time: 1.8887641429901123
Forward computations: 74804
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 2.3446285724639893
Backtrace time: 0.0008482933044433594
Total time: 2.3454768657684326
Forward computations: 98586

============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 2.460639238357544
Backtrace time: 0.0009171962738037109
Total time: 2.4615564346313477
Forward computations: 102912
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 1.7151291370391846
Backtrace time: 0.0007340908050537109
Total time: 1.7158632278442383
Forward computations: 71764
============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 1.8912222385406494
Backtrace time: 0.0007646083831787109
Total time: 1.8919868469238281
Forward computations: 79874
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 1.6939201354980469
Backtrace time: 0.0008080005645751953
Total time: 1.694728136062622
Forward computations: 67886
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a
S, D, I: 0 0 25
Decode time: 2.1245296001434326
Backtrace time: 0.0008444786071777344
Total time: 2.1253740787506104
Forward computations: 87388
experiment_name: Task 4: pruning 50 + estimated unigram
num_states: 176
num_arcs: 350
total_S: 43
total_D: 147
total_I: 295
total_N: 237
WER: 2.0464135021097047
total_time_sec: 71.38627815246582
avg_time_sec: 1.4872141281763713
total_decode_time_sec: 71.36331415176392
avg_decode_time_sec: 1.4867357114950817
total_backtrace_time_sec: 0.022964000701904297
avg_backtrace_time_sec: 0.00047841668128967285
total_forward_computations: 2744336
avg_forward_computations: 57173.666666666664
empty_hypothesis_count: 29
pruning_threshold: 50
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: True
use_silence: True

In [19]:
results, summary = evaluate_dataset(
    audio_to_reference,
    continue_prob=0.1,
    self_loop_prob=0.4,
    use_unigram=True,
    use_silence=True,
    pruning_threshold=100,
    unigram_probs=unigram_probs,
    experiment_name="Task 4: pruning 100 + estimated unigram"
)

for k, v in summary.items():
    print(f"{k}: {v}")

============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: a a the the the the of peck of peppers peppers pickled piper of peck of a a
S, D, I: 2 0 15
Decode time: 1.8375275135040283
Backtrace time: 0.0005464553833007812
Total time: 1.838073968887329
Forward computations: 74682
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: a a the the of peck of a a
S, D, I: 1 0 6
Decode time: 1.4195804595947266
Backtrace time: 0.0004630088806152344
Total time: 1.4200434684753418
Forward computations: 50362
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 1.4923932552337646
Backtrace time: 0.0005214214324951172
Total time: 1.4929146766662598
Forward computations: 61066
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 1.2857394218444824
Backtrace time: 0.0005059242248535156
Total time: 1.286245346069336
Forward computations: 49850
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: a a the the of peck of the the of peck of a a
S, D, I: 1 0 11
Decode time: 1.3661141395568848
Backtrace time: 0.0005142688751220703
Total time: 1.3666284084320068
Forward computations: 55580
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: a a of peck of the the peppers picked wheres picked peter piper wheres a a
S, D, I: 1 0 13
Decode time: 1.64530348777771
Backtrace time: 0.0005276203155517578
Total time: 1.6458311080932617
Forward computations: 61024
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 1.9033396244049072
Backtrace time: 0.0005834102630615234
Total time: 1.9039230346679688
Forward computations: 80698
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 1.3467013835906982
Backtrace time: 0.000492095947265625
Total time: 1.3471934795379639
Forward computations: 57464
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: a a the the peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 9
Decode time: 2.211290121078491
Backtrace time: 0.0006506443023681641
Total time: 2.2119407653808594
Forward computations: 92552
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 2.0284082889556885
Backtrace time: 0.000591278076171875
Total time: 2.0289995670318604
Forward computations: 85916
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 1.7152135372161865
Backtrace time: 0.0006830692291259766
Total time: 1.7158966064453125
Forward computations: 70960
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: a a a a of peck of the the of peck of a a of peck of a a
S, D, I: 2 0 14
Decode time: 2.1037209033966064
Backtrace time: 0.0006086826324462891
Total time: 2.1043295860290527
Forward computations: 88754
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: a a the the of peck of the the of peck of the the of peck of a a
S, D, I: 2 0 14
Decode time: 1.8018567562103271
Backtrace time: 0.000545501708984375
Total time: 1.8024022579193115
Forward computations: 76586
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peter peppers pickled piper peppers a a
S, D, I: 0 0 12
Decode time: 2.156562089920044
Backtrace time: 0.0005881786346435547
Total time: 2.1571502685546875
Forward computations: 84904
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 2.0663979053497314
Backtrace time: 0.0005860328674316406
Total time: 2.066983938217163
Forward computations: 76380
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peter piper wheres of peck of the the a a
S, D, I: 2 0 8
Decode time: 1.4058430194854736
Backtrace time: 0.0005588531494140625
Total time: 1.4064018726348877
Forward computations: 59574
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 20
Decode time: 1.9297516345977783
Backtrace time: 0.0005574226379394531
Total time: 1.9303090572357178
Forward computations: 76590
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: a a a a of peck of a a the the peppers picked wheres picked peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 19
Decode time: 2.0013320446014404
Backtrace time: 0.0005891323089599609
Total time: 2.0019211769104004
Forward computations: 84854
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 1.8287222385406494
Backtrace time: 0.0006756782531738281
Total time: 1.8293979167938232
Forward computations: 77092
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: a a the the peter piper wheres the the the the of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.097269296646118
Backtrace time: 0.0006086826324462891
Total time: 2.0978779792785645
Forward computations: 83644
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: a a peter piper wheres the the of peck of a a a a
S, D, I: 0 0 11
Decode time: 1.4228718280792236
Backtrace time: 0.0004818439483642578
Total time: 1.423353672027588
Forward computations: 58768
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of a a the the peppers picked wheres picked peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.369983434677124
Backtrace time: 0.0006055831909179688
Total time: 2.370589017868042
Forward computations: 98234
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of of peck of a a peppers the wheres pickled peter a a a a
S, D, I: 2 0 17
Decode time: 2.4296863079071045
Backtrace time: 0.0006458759307861328
Total time: 2.4303321838378906
Forward computations: 101926
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: a a the the peter piper wheres the the of peck of a a a a a a
S, D, I: 1 0 13
Decode time: 2.2546560764312744
Backtrace time: 0.0006139278411865234
Total time: 2.255270004272461
Forward computations: 92300

============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: a a peter piper wheres of peck of a a peppers peppers pickled piper a a a a
S, D, I: 2 0 13
Decode time: 2.2952189445495605
Backtrace time: 0.0006594657897949219
Total time: 2.2958784103393555
Forward computations: 95366
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: a a peter piper wheres peppers the wheres pickled peter peppers peppers pickled piper a a
S, D, I: 0 0 13
Decode time: 1.6454167366027832
Backtrace time: 0.0005626678466796875
Total time: 1.645979404449463
Forward computations: 65830
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked a a a a
S, D, I: 3 0 12
Decode time: 2.049598455429077
Backtrace time: 0.0006093978881835938
Total time: 2.0502078533172607
Forward computations: 86204
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: a a peter piper wheres of peck of of peck of the the the the a a
S, D, I: 2 0 12
Decode time: 1.9550070762634277
Backtrace time: 0.0005791187286376953
Total time: 1.9555861949920654
Forward computations: 80536
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: a a peter piper wheres of peck of a a a a
S, D, I: 2 0 9
Decode time: 1.6018760204315186
Backtrace time: 0.0005156993865966797
Total time: 1.6023917198181152
Forward computations: 68114
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: a a peter piper wheres of peck of a a peppers peter peppers pickled piper peppers peppers the wheres pickled peter a a a a
S, D, I: 2 0 18
Decode time: 2.890601634979248
Backtrace time: 0.0006997585296630859
Total time: 2.891301393508911
Forward computations: 121212
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper the the of peck of the the peppers picked wheres picked of peck of the the peter piper wheres a a
S, D, I: 4 0 26
Decode time: 2.9956533908843994
Backtrace time: 0.0007185935974121094
Total time: 2.9963719844818115
Forward computations: 120780
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked of peck of peter piper wheres the the peppers peppers pickled piper a a a a
S, D, I: 2 1 20
Decode time: 3.49308443069458
Backtrace time: 0.0007715225219726562
Total time: 3.4938559532165527
Forward computations: 138162
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of a a peppers picked wheres picked a a a a a a peppers picked wheres picked peppers peter peppers pickled piper peppers a a
S, D, I: 1 1 27
Decode time: 3.728355884552002
Backtrace time: 0.0008666515350341797
Total time: 3.729222536087036
Forward computations: 153902
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: a a peppers peppers pickled piper the the of peck of a a a a peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 0 20
Decode time: 2.968736410140991
Backtrace time: 0.0007529258728027344
Total time: 2.969489336013794
Forward computations: 121972
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the a a the the peter piper wheres of peck of peter piper wheres a a
S, D, I: 3 0 23
Decode time: 2.9599218368530273
Backtrace time: 0.0007700920104980469
Total time: 2.9606919288635254
Forward computations: 120558
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 3.5330843925476074
Backtrace time: 0.0008387565612792969
Total time: 3.5339231491088867
Forward computations: 142122
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the of peck of peppers peppers pickled piper a a a a a a
S, D, I: 3 0 14
Decode time: 2.541579008102417
Backtrace time: 0.0006861686706542969
Total time: 2.5422651767730713
Forward computations: 104594
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: a a the the the the of peck of a a the the of peck of a a peppers peppers pickled piper peter piper wheres a a
S, D, I: 3 0 20
Decode time: 2.8414177894592285
Backtrace time: 0.0008513927459716797
Total time: 2.8422691822052
Forward computations: 111148
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: a a the the of peck of a a a a of peck of a a peter piper wheres peppers peppers pickled piper a a a a of peck of peppers picked wheres picked a a
S, D, I: 3 0 24
Decode time: 3.754422664642334
Backtrace time: 0.0008091926574707031
Total time: 3.7552318572998047
Forward computations: 157554
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 2.17661452293396
Backtrace time: 0.0005860328674316406
Total time: 2.1772005558013916
Forward computations: 92194
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 3.472816228866577
Backtrace time: 0.0008039474487304688
Total time: 3.4736201763153076
Forward computations: 142554
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of of peck of the the of peck of a a a a
S, D, I: 2 0 17
Decode time: 3.8050272464752197
Backtrace time: 0.0007891654968261719
Total time: 3.805816411972046
Forward computations: 138184
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 3.7921035289764404
Backtrace time: 0.0008158683776855469
Total time: 3.792919397354126
Forward computations: 159734
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 4.274750471115112
Backtrace time: 0.0009121894836425781
Total time: 4.275662660598755
Forward computations: 176698
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 3.1844327449798584
Backtrace time: 0.0007355213165283203
Total time: 3.1851682662963867
Forward computations: 130362

============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 3.616088390350342
Backtrace time: 0.0007700920104980469
Total time: 3.61685848236084
Forward computations: 135456
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 3.020778179168701
Backtrace time: 0.0007967948913574219
Total time: 3.0215749740600586
Forward computations: 125988
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a
S, D, I: 0 0 25
Decode time: 3.9913089275360107
Backtrace time: 0.0008671283721923828
Total time: 3.992176055908203
Forward computations: 165022
experiment_name: Task 4: pruning 100 + estimated unigram
num_states: 176
num_arcs: 350
total_S: 95
total_D: 2
total_I: 746
total_N: 237
WER: 3.5569620253164556
total_time_sec: 116.73967242240906
avg_time_sec: 2.4320765088001886
total_decode_time_sec: 116.70815968513489
avg_decode_time_sec: 2.43141999344031
total_backtrace_time_sec: 0.03151273727416992
avg_backtrace_time_sec: 0.00065651535987854
total_forward_computations: 4754006
avg_forward_computations: 99041.79166666667
empty_hypothesis_count: 0
pruning_threshold: 100
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: True
use_silence: True

In [20]:
results, summary = evaluate_dataset(
    audio_to_reference,
    continue_prob=0.1,
    self_loop_prob=0.4,
    use_unigram=True,
    use_silence=True,
    pruning_threshold=150,
    unigram_probs=unigram_probs,
    experiment_name="Task 4: pruning 150 + estimated unigram"
)

for k, v in summary.items():
    print(f"{k}: {v}")

============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: a a the the the the of peck of peppers peppers pickled piper of peck of a a
S, D, I: 2 0 15
Decode time: 2.2174737453460693
Backtrace time: 0.0006213188171386719
Total time: 2.218095064163208
Forward computations: 88830
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: a a the the of peck of a a
S, D, I: 1 0 6
Decode time: 1.5649993419647217
Backtrace time: 0.0004680156707763672
Total time: 1.565467357635498
Forward computations: 62514
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 1.6607258319854736
Backtrace time: 0.0004851818084716797
Total time: 1.6612110137939453
Forward computations: 69504
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 1.4719462394714355
Backtrace time: 0.0004589557647705078
Total time: 1.472405195236206
Forward computations: 60232
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: a a the the of peck of the the of peck of a a
S, D, I: 1 0 11
Decode time: 1.6159379482269287
Backtrace time: 0.0004949569702148438
Total time: 1.6164329051971436
Forward computations: 66248
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: a a of peck of the the peppers picked wheres picked peter piper wheres a a
S, D, I: 1 0 13
Decode time: 1.6941618919372559
Backtrace time: 0.0005068778991699219
Total time: 1.6946687698364258
Forward computations: 71898
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 2.3704068660736084
Backtrace time: 0.0005729198455810547
Total time: 2.3709797859191895
Forward computations: 96828
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 1.6286084651947021
Backtrace time: 0.0005645751953125
Total time: 1.6291730403900146
Forward computations: 70014
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: a a the the peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 9
Decode time: 2.7002251148223877
Backtrace time: 0.0006465911865234375
Total time: 2.700871706008911
Forward computations: 111820
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 2.2098965644836426
Backtrace time: 0.0005538463592529297
Total time: 2.2104504108428955
Forward computations: 94090
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 2.0096817016601562
Backtrace time: 0.0005502700805664062
Total time: 2.0102319717407227
Forward computations: 85138
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: a a a a of peck of the the of peck of a a of peck of a a
S, D, I: 2 0 14
Decode time: 2.5445175170898438
Backtrace time: 0.0005972385406494141
Total time: 2.545114755630493
Forward computations: 108770
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: a a the the of peck of the the of peck of the the of peck of a a
S, D, I: 2 0 14
Decode time: 2.101259231567383
Backtrace time: 0.0005712509155273438
Total time: 2.10183048248291
Forward computations: 89048
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peter peppers pickled piper peppers a a
S, D, I: 0 0 12
Decode time: 2.4903712272644043
Backtrace time: 0.0005755424499511719
Total time: 2.4909467697143555
Forward computations: 100598
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 2.146639108657837
Backtrace time: 0.0005505084991455078
Total time: 2.1471896171569824
Forward computations: 92134
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peter piper wheres of peck of the the a a
S, D, I: 2 0 8
Decode time: 2.2414941787719727
Backtrace time: 0.0006587505340576172
Total time: 2.2421529293060303
Forward computations: 70226
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 20
Decode time: 2.3093457221984863
Backtrace time: 0.0005848407745361328
Total time: 2.3099305629730225
Forward computations: 92514
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: a a a a of peck of a a the the peppers picked wheres picked peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 19
Decode time: 2.5134384632110596
Backtrace time: 0.0006020069122314453
Total time: 2.514040470123291
Forward computations: 103966
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 2.0474884510040283
Backtrace time: 0.0006606578826904297
Total time: 2.0481491088867188
Forward computations: 87078
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: a a the the peter piper wheres the the the the of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.354351043701172
Backtrace time: 0.0005667209625244141
Total time: 2.3549177646636963
Forward computations: 98320
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: a a peter piper wheres the the of peck of a a a a
S, D, I: 0 0 11
Decode time: 1.8312315940856934
Backtrace time: 0.0004923343658447266
Total time: 1.831723928451538
Forward computations: 72268
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of a a the the peppers picked wheres picked peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.8277032375335693
Backtrace time: 0.0006251335144042969
Total time: 2.8283283710479736
Forward computations: 116886
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of of peck of a a peppers the wheres pickled peter a a a a
S, D, I: 2 0 17
Decode time: 3.1552703380584717
Backtrace time: 0.0006594657897949219
Total time: 3.1559298038482666
Forward computations: 124422
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: a a the the peter piper wheres the the of peck of a a a a a a
S, D, I: 1 0 13
Decode time: 2.7737233638763428
Backtrace time: 0.00060272216796875
Total time: 2.7743260860443115
Forward computations: 111020

============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: a a peter piper wheres of peck of a a peppers peppers pickled piper a a a a
S, D, I: 2 0 13
Decode time: 2.9942851066589355
Backtrace time: 0.0006499290466308594
Total time: 2.9949350357055664
Forward computations: 119998
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: a a peter piper wheres peppers the wheres pickled peter peppers peppers pickled piper a a
S, D, I: 0 0 13
Decode time: 2.0113611221313477
Backtrace time: 0.0005729198455810547
Total time: 2.0119340419769287
Forward computations: 83594
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked a a a a
S, D, I: 3 0 12
Decode time: 2.5797741413116455
Backtrace time: 0.0006093978881835938
Total time: 2.580383539199829
Forward computations: 104868
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: a a peter piper wheres of peck of of peck of the the the the a a
S, D, I: 2 0 12
Decode time: 2.3317456245422363
Backtrace time: 0.0005643367767333984
Total time: 2.3323099613189697
Forward computations: 98452
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: a a peter piper wheres of peck of a a a a
S, D, I: 2 0 9
Decode time: 1.9725604057312012
Backtrace time: 0.0005311965942382812
Total time: 1.9730916023254395
Forward computations: 80732
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: a a peter piper wheres of peck of a a peppers peter peppers pickled piper peppers peppers the wheres pickled peter a a a a
S, D, I: 2 0 18
Decode time: 3.5517702102661133
Backtrace time: 0.00069427490234375
Total time: 3.552464485168457
Forward computations: 145362
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper the the of peck of the the peppers picked wheres picked of peck of the the peter piper wheres a a
S, D, I: 4 0 26
Decode time: 3.6476666927337646
Backtrace time: 0.0007619857788085938
Total time: 3.6484286785125732
Forward computations: 147330
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked of peck of peter piper wheres the the peppers peppers pickled piper a a a a
S, D, I: 2 1 20
Decode time: 4.008100748062134
Backtrace time: 0.0007612705230712891
Total time: 4.008862018585205
Forward computations: 165156
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of a a peppers picked wheres picked a a a a a a peppers picked wheres picked peppers peter peppers pickled piper peppers a a
S, D, I: 1 1 27
Decode time: 4.623380899429321
Backtrace time: 0.0008909702301025391
Total time: 4.624271869659424
Forward computations: 194092
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: a a peppers peppers pickled piper the the of peck of a a a a peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 0 20
Decode time: 3.686610460281372
Backtrace time: 0.0007405281066894531
Total time: 3.6873509883880615
Forward computations: 152518
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the a a the the peter piper wheres of peck of peter piper wheres a a
S, D, I: 3 0 23
Decode time: 3.802513599395752
Backtrace time: 0.0007789134979248047
Total time: 3.8032925128936768
Forward computations: 149144
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 4.45353627204895
Backtrace time: 0.0008466243743896484
Total time: 4.45438289642334
Forward computations: 183570
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the of peck of peppers peppers pickled piper a a a a a a
S, D, I: 3 0 14
Decode time: 3.223454475402832
Backtrace time: 0.0007281303405761719
Total time: 3.224182605743408
Forward computations: 135114
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: a a the the the the of peck of a a the the of peck of a a peppers peppers pickled piper peter piper wheres a a
S, D, I: 3 0 20
Decode time: 3.2662241458892822
Backtrace time: 0.0006918907165527344
Total time: 3.266916036605835
Forward computations: 135766
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: a a the the of peck of a a a a of peck of a a peter piper wheres peppers peppers pickled piper a a a a of peck of peppers picked wheres picked a a
S, D, I: 3 0 24
Decode time: 4.395206451416016
Backtrace time: 0.0008156299591064453
Total time: 4.396022081375122
Forward computations: 185664
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 2.79461932182312
Backtrace time: 0.0006139278411865234
Total time: 2.7952332496643066
Forward computations: 113120
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 4.433427333831787
Backtrace time: 0.0007908344268798828
Total time: 4.434218168258667
Forward computations: 176344
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of of peck of the the of peck of a a a a
S, D, I: 2 0 17
Decode time: 4.351718425750732
Backtrace time: 0.0008189678192138672
Total time: 4.352537393569946
Forward computations: 175420
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 4.581360340118408
Backtrace time: 0.0008182525634765625
Total time: 4.582178592681885
Forward computations: 191242
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 5.294790267944336
Backtrace time: 0.0009627342224121094
Total time: 5.295753002166748
Forward computations: 220318
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 4.002913475036621
Backtrace time: 0.0007650852203369141
Total time: 4.003678560256958
Forward computations: 163252

============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 4.072170734405518
Backtrace time: 0.0007746219635009766
Total time: 4.0729453563690186
Forward computations: 164794
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 3.8600990772247314
Backtrace time: 0.0007832050323486328
Total time: 3.86088228225708
Forward computations: 162580
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a
S, D, I: 0 0 25
Decode time: 5.068397283554077
Backtrace time: 0.000896453857421875
Total time: 5.069293737411499
Forward computations: 205694
experiment_name: Task 4: pruning 150 + estimated unigram
num_states: 176
num_arcs: 350
total_S: 95
total_D: 2
total_I: 746
total_N: 237
WER: 3.5569620253164556
total_time_sec: 141.5201165676117
avg_time_sec: 2.9483357618252435
total_decode_time_sec: 141.48858380317688
avg_decode_time_sec: 2.9476788292328515
total_backtrace_time_sec: 0.03153276443481445
avg_backtrace_time_sec: 0.0006569325923919678
total_forward_computations: 5798490
avg_forward_computations: 120801.875
empty_hypothesis_count: 0
pruning_threshold: 150
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: True
use_silence: True

In [21]:
results, summary = evaluate_dataset(
    audio_to_reference,
    continue_prob=0.1,
    self_loop_prob=0.4,
    use_unigram=True,
    use_silence=True,
    pruning_threshold=200,
    unigram_probs=unigram_probs,
    experiment_name="Task 4: pruning 200 + estimated unigram"
)

for k, v in summary.items():
    print(f"{k}: {v}")

============================================================
Audio: recordings_fixed/1.wav
Reference: peter piper picked
Hypothesis: a a the the the the of peck of peppers peppers pickled piper of peck of a a
S, D, I: 2 0 15
Decode time: 2.414669990539551
Backtrace time: 0.0005743503570556641
Total time: 2.4152443408966064
Forward computations: 95968
============================================================
Audio: recordings_fixed/2.wav
Reference: picked a peck
Hypothesis: a a the the of peck of a a
S, D, I: 1 0 6
Decode time: 1.632629632949829
Backtrace time: 0.0004985332489013672
Total time: 1.6331281661987305
Forward computations: 68802
============================================================
Audio: recordings_fixed/3.wav
Reference: piper picked a
Hypothesis: a a peter piper wheres of peck of the the the the a a a a
S, D, I: 1 0 13
Decode time: 1.762570858001709
Backtrace time: 0.0005228519439697266
Total time: 1.7630937099456787
Forward computations: 73938
============================================================
Audio: recordings_fixed/4.wav
Reference: a peck of
Hypothesis: a a of peck of the the a a a a
S, D, I: 0 0 8
Decode time: 1.5469207763671875
Backtrace time: 0.00048232078552246094
Total time: 1.54740309715271
Forward computations: 64534
============================================================
Audio: recordings_fixed/5.wav
Reference: peck of pickled
Hypothesis: a a the the of peck of the the of peck of a a
S, D, I: 1 0 11
Decode time: 1.6966941356658936
Backtrace time: 0.0004913806915283203
Total time: 1.6971855163574219
Forward computations: 72144
============================================================
Audio: recordings_fixed/6.wav
Reference: of pickled peppers
Hypothesis: a a of peck of the the peppers picked wheres picked peter piper wheres a a
S, D, I: 1 0 13
Decode time: 1.8722572326660156
Backtrace time: 0.0004956722259521484
Total time: 1.8727529048919678
Forward computations: 77016
============================================================
Audio: recordings_fixed/7.wav
Reference: pickled peppers peter
Hypothesis: a a of peck of peppers peter peppers pickled piper peppers the the a a
S, D, I: 1 0 12
Decode time: 2.539525270462036
Backtrace time: 0.0005769729614257812
Total time: 2.540102243423462
Forward computations: 106222
============================================================
Audio: recordings_fixed/8.wav
Reference: peppers peter piper
Hypothesis: a a peter piper wheres the the peppers peppers pickled piper a a
S, D, I: 1 0 10
Decode time: 1.8301849365234375
Backtrace time: 0.0005068778991699219
Total time: 1.8306918144226074
Forward computations: 76230
============================================================
Audio: recordings_fixed/9.wav
Reference: peter picked peppers
Hypothesis: a a the the peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 9
Decode time: 3.0240118503570557
Backtrace time: 0.0006663799285888672
Total time: 3.0246782302856445
Forward computations: 123736
============================================================
Audio: recordings_fixed/10.wav
Reference: piper picked peppers
Hypothesis: a a peter piper wheres peter piper wheres of peck of peppers picked wheres picked of peck of a a peter piper wheres a a
S, D, I: 1 0 22
Decode time: 2.427811861038208
Backtrace time: 0.0005767345428466797
Total time: 2.4283885955810547
Forward computations: 98126
============================================================
Audio: recordings_fixed/11.wav
Reference: peter piper picked a peck
Hypothesis: peppers picked wheres picked of peck of peppers peppers pickled piper the the of peck of a a a a
S, D, I: 3 0 15
Decode time: 2.295323133468628
Backtrace time: 0.0005557537078857422
Total time: 2.2958788871765137
Forward computations: 91012
============================================================
Audio: recordings_fixed/12.wav
Reference: piper picked a peck of
Hypothesis: a a a a of peck of the the of peck of a a of peck of a a
S, D, I: 2 0 14
Decode time: 2.8781285285949707
Backtrace time: 0.0006120204925537109
Total time: 2.8787405490875244
Forward computations: 117956
============================================================
Audio: recordings_fixed/13.wav
Reference: picked a peck of pickled
Hypothesis: a a the the of peck of the the of peck of the the of peck of a a
S, D, I: 2 0 14
Decode time: 2.330141067504883
Backtrace time: 0.0005483627319335938
Total time: 2.3306894302368164
Forward computations: 94872
============================================================
Audio: recordings_fixed/14.wav
Reference: a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peter peppers pickled piper peppers a a
S, D, I: 0 0 12
Decode time: 2.7152438163757324
Backtrace time: 0.0006148815155029297
Total time: 2.7158586978912354
Forward computations: 107452
============================================================
Audio: recordings_fixed/15.wav
Reference: peter picked a peck
Hypothesis: a a the the the the a a a a a a
S, D, I: 3 0 8
Decode time: 3.204341411590576
Backtrace time: 0.0006060600280761719
Total time: 3.2049474716186523
Forward computations: 101592
============================================================
Audio: recordings_fixed/16.wav
Reference: piper picked a peck
Hypothesis: a a peter piper wheres of peck of the the a a
S, D, I: 2 0 8
Decode time: 1.8826448917388916
Backtrace time: 0.00048351287841796875
Total time: 1.8831284046173096
Forward computations: 74698
============================================================
Audio: recordings_fixed/17.wav
Reference: peter picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 20
Decode time: 2.4623022079467773
Backtrace time: 0.0005862712860107422
Total time: 2.462888479232788
Forward computations: 97908
============================================================
Audio: recordings_fixed/18.wav
Reference: piper picked pickled peppers
Hypothesis: a a a a of peck of a a the the peppers picked wheres picked peppers peter peppers pickled piper peppers a a
S, D, I: 1 0 19
Decode time: 2.8720481395721436
Backtrace time: 0.0006093978881835938
Total time: 2.872657537460327
Forward computations: 111798
============================================================
Audio: recordings_fixed/19.wav
Reference: peter piper picked peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper peter piper wheres a a
S, D, I: 2 0 14
Decode time: 2.1867525577545166
Backtrace time: 0.0005366802215576172
Total time: 2.187289237976074
Forward computations: 89328
============================================================
Audio: recordings_fixed/20.wav
Reference: picked peppers peter piper
Hypothesis: a a the the peter piper wheres the the the the of peck of peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.446014881134033
Backtrace time: 0.0005679130554199219
Total time: 2.446582794189453
Forward computations: 104584
============================================================
Audio: recordings_fixed/21.wav
Reference: wheres the peck
Hypothesis: a a peter piper wheres the the of peck of a a a a
S, D, I: 0 0 11
Decode time: 1.8567183017730713
Backtrace time: 0.0005846023559570312
Total time: 1.8573029041290283
Forward computations: 78406
============================================================
Audio: recordings_fixed/22.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of a a the the peppers picked wheres picked peter piper wheres a a
S, D, I: 2 0 15
Decode time: 2.9872984886169434
Backtrace time: 0.0006203651428222656
Total time: 2.9879188537597656
Forward computations: 123086
============================================================
Audio: recordings_fixed/23.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of of peck of a a peppers the wheres pickled peter a a a a
S, D, I: 2 0 17
Decode time: 3.236196994781494
Backtrace time: 0.0007007122039794922
Total time: 3.2368977069854736
Forward computations: 134120
============================================================
Audio: recordings_fixed/24.wav
Reference: wheres the peck of peppers
Hypothesis: a a the the peter piper wheres the the of peck of a a a a a a
S, D, I: 1 0 13
Decode time: 2.853999614715576
Backtrace time: 0.0005915164947509766
Total time: 2.854591131210327
Forward computations: 119394

============================================================
Audio: recordings_fixed/25.wav
Reference: wheres the peck piper picked
Hypothesis: a a peter piper wheres of peck of a a peppers peppers pickled piper a a a a
S, D, I: 2 0 13
Decode time: 3.183412790298462
Backtrace time: 0.0006427764892578125
Total time: 3.1840555667877197
Forward computations: 131106
============================================================
Audio: recordings_fixed/26.wav
Reference: wheres peter piper
Hypothesis: a a peter piper wheres peppers the wheres pickled peter peppers peppers pickled piper a a
S, D, I: 0 0 13
Decode time: 2.2803564071655273
Backtrace time: 0.0005652904510498047
Total time: 2.280921697616577
Forward computations: 95102
============================================================
Audio: recordings_fixed/27.wav
Reference: wheres the pickled peck
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked a a a a
S, D, I: 3 0 12
Decode time: 2.7659709453582764
Backtrace time: 0.0005939006805419922
Total time: 2.7665648460388184
Forward computations: 115182
============================================================
Audio: recordings_fixed/28.wav
Reference: wheres the peck of pickled
Hypothesis: a a peter piper wheres of peck of of peck of the the the the a a
S, D, I: 2 0 12
Decode time: 2.5869457721710205
Backtrace time: 0.0006010532379150391
Total time: 2.5875468254089355
Forward computations: 105536
============================================================
Audio: recordings_fixed/29.wav
Reference: wheres the peppers
Hypothesis: a a peter piper wheres of peck of a a a a
S, D, I: 2 0 9
Decode time: 2.151848316192627
Backtrace time: 0.0005598068237304688
Total time: 2.1524081230163574
Forward computations: 87112
============================================================
Audio: recordings_fixed/30.wav
Reference: wheres the peck of peppers peter picked
Hypothesis: a a peter piper wheres of peck of a a peppers peter peppers pickled piper peppers peppers the wheres pickled peter a a a a
S, D, I: 2 0 18
Decode time: 3.835280656814575
Backtrace time: 0.000728607177734375
Total time: 3.8360092639923096
Forward computations: 155878
============================================================
Audio: recordings_fixed/31.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of peppers peppers pickled piper the the of peck of the the peppers picked wheres picked of peck of the the peter piper wheres a a
S, D, I: 4 0 26
Decode time: 4.390005350112915
Backtrace time: 0.0007736682891845703
Total time: 4.3907790184021
Forward computations: 158006
============================================================
Audio: recordings_fixed/32.wav
Reference: wheres the peck of pickled peppers peter piper picked
Hypothesis: a a peter piper wheres of peck of peppers picked wheres picked of peck of peter piper wheres the the peppers peppers pickled piper a a a a
S, D, I: 2 1 20
Decode time: 4.412735223770142
Backtrace time: 0.0007829666137695312
Total time: 4.413518190383911
Forward computations: 177636
============================================================
Audio: recordings_fixed/33.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the of peck of a a peppers picked wheres picked a a a a a a peppers picked wheres picked peppers peter peppers pickled piper peppers a a
S, D, I: 1 1 27
Decode time: 5.140809535980225
Backtrace time: 0.0008921623229980469
Total time: 5.141701698303223
Forward computations: 214036
============================================================
Audio: recordings_fixed/34.wav
Reference: piper picked peck of pickled peppers
Hypothesis: a a peppers peppers pickled piper the the of peck of a a a a peppers picked wheres picked a a peter piper wheres a a
S, D, I: 2 0 20
Decode time: 4.17760157585144
Backtrace time: 0.0007891654968261719
Total time: 4.178390741348267
Forward computations: 169852
============================================================
Audio: recordings_fixed/35.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a the the the the of peck of a a the the a a the the peter piper wheres of peck of peter piper wheres a a
S, D, I: 3 0 23
Decode time: 4.611392259597778
Backtrace time: 0.0007994174957275391
Total time: 4.612191677093506
Forward computations: 164042
============================================================
Audio: recordings_fixed/36.wav
Reference: peter picked peppers piper picked peppers
Hypothesis: a a the the the the of peck of a a peppers peter peppers pickled piper peppers peppers peppers pickled piper a a peter piper wheres a a
S, D, I: 3 0 22
Decode time: 5.444438219070435
Backtrace time: 0.0008556842803955078
Total time: 5.44529390335083
Forward computations: 206412
============================================================
Audio: recordings_fixed/37.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the of peck of peppers peppers pickled piper a a a a a a
S, D, I: 3 0 14
Decode time: 3.602564811706543
Backtrace time: 0.0007624626159667969
Total time: 3.6033272743225098
Forward computations: 151394
============================================================
Audio: recordings_fixed/38.wav
Reference: peter piper picked a peck of peppers
Hypothesis: a a the the the the of peck of a a the the of peck of a a peppers peppers pickled piper peter piper wheres a a
S, D, I: 3 0 20
Decode time: 3.591344118118286
Backtrace time: 0.0006744861602783203
Total time: 3.5920186042785645
Forward computations: 148592
============================================================
Audio: recordings_fixed/39.wav
Reference: peter picked a peck of peppers piper picked a peck of peppers
Hypothesis: a a the the of peck of a a a a of peck of a a peter piper wheres peppers peppers pickled piper a a a a of peck of peppers picked wheres picked a a
S, D, I: 3 0 24
Decode time: 4.770831108093262
Backtrace time: 0.0008378028869628906
Total time: 4.771668910980225
Forward computations: 195752
============================================================
Audio: recordings_fixed/40.wav
Reference: piper picked a peck of peppers
Hypothesis: a a peter piper wheres the the a a a a
S, D, I: 4 0 5
Decode time: 2.9423422813415527
Backtrace time: 0.0005831718444824219
Total time: 2.942925453186035
Forward computations: 123144
============================================================
Audio: recordings_fixed/41.wav
Reference: peter piper picked a peck
Hypothesis: a a the the of peck of a a peppers picked wheres picked of peck of a a peppers picked wheres picked a a
S, D, I: 3 0 19
Decode time: 4.838869094848633
Backtrace time: 0.0007722377777099609
Total time: 4.839641332626343
Forward computations: 192310
============================================================
Audio: recordings_fixed/42.wav
Reference: peter piper picked a peck
Hypothesis: a a the the peter piper wheres of peck of of peck of the the of peck of a a a a
S, D, I: 2 0 17
Decode time: 4.652032852172852
Backtrace time: 0.0007841587066650391
Total time: 4.652817010879517
Forward computations: 193668
============================================================
Audio: recordings_fixed/43.wav
Reference: peter piper picked a peck of pickled peppers
Hypothesis: a a of peck of of peck of of peck of the the a a the the the the peppers picked wheres picked of peck of peter piper wheres a a
S, D, I: 5 0 23
Decode time: 4.8894429206848145
Backtrace time: 0.0008540153503417969
Total time: 4.890296936035156
Forward computations: 204536
============================================================
Audio: recordings_fixed/44.wav
Reference: peter picked a peck of pickled peppers
Hypothesis: a a the the the the a a of peck of the the the the peppers picked wheres picked the the peter piper wheres a a
S, D, I: 3 0 19
Decode time: 6.549914360046387
Backtrace time: 0.0009374618530273438
Total time: 6.550851821899414
Forward computations: 242650
============================================================
Audio: recordings_fixed/45.wav
Reference: wheres the peck of pickled peppers
Hypothesis: a a peter piper wheres of peck of of peck of a a of peck of peter piper wheres a a a a
S, D, I: 3 0 17
Decode time: 5.002855062484741
Backtrace time: 0.0007510185241699219
Total time: 5.003606081008911
Forward computations: 178056

============================================================
Audio: recordings_fixed/46.wav
Reference: peter piper picked pickled peppers
Hypothesis: a a of peck of of peck of a a the the the the the the peppers picked wheres picked peter piper wheres a a
S, D, I: 3 0 20
Decode time: 4.331728219985962
Backtrace time: 0.0007848739624023438
Total time: 4.332513093948364
Forward computations: 180336
============================================================
Audio: recordings_fixed/47.wav
Reference: peter piper picked a peck
Hypothesis: a a the the the the peppers peppers pickled piper peppers picked wheres picked of peck of a a
S, D, I: 2 0 14
Decode time: 4.400898694992065
Backtrace time: 0.0008060932159423828
Total time: 4.401704788208008
Forward computations: 184366
============================================================
Audio: recordings_fixed/48.wav
Reference: wheres the peck peter picked
Hypothesis: a a peter piper wheres of peck of a a the the the the peppers peter picked peck peppers peter picked peck a a peppers peppers pickled piper a a
S, D, I: 0 0 25
Decode time: 5.284684658050537
Backtrace time: 0.0008885860443115234
Total time: 5.285573244094849
Forward computations: 221780
experiment_name: Task 4: pruning 200 + estimated unigram
num_states: 176
num_arcs: 350
total_S: 95
total_D: 2
total_I: 746
total_N: 237
WER: 3.5569620253164556
total_time_sec: 156.82436680793762
avg_time_sec: 3.2671743084987006
total_decode_time_sec: 156.79273581504822
avg_decode_time_sec: 3.266515329480171
total_backtrace_time_sec: 0.0316309928894043
avg_backtrace_time_sec: 0.0006589790185292562
total_forward_computations: 6299406
avg_forward_computations: 131237.625
empty_hypothesis_count: 0
pruning_threshold: 200
continue_prob: 0.1
self_loop_prob: 0.4
use_unigram: True
use_silence: True